# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addFunction.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from coquery.gui.pyqt_compat import QtCore, QtGui, frameShadow, frameShape

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FunctionsDialog(object):
    def setupUi(self, FunctionsDialog):
        FunctionsDialog.setObjectName(_fromUtf8("FunctionsDialog"))
        FunctionsDialog.resize(640, 480)
        self.verticalLayout_2 = QtGui.QVBoxLayout(FunctionsDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget_label = QtGui.QWidget(FunctionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_label.sizePolicy().hasHeightForWidth())
        self.widget_label.setSizePolicy(sizePolicy)
        self.widget_label.setObjectName(_fromUtf8("widget_label"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_label)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.widget_label)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.edit_label = QtGui.QLineEdit(self.widget_label)
        self.edit_label.setObjectName(_fromUtf8("edit_label"))
        self.horizontalLayout_3.addWidget(self.edit_label)
        self.verticalLayout_3.addWidget(self.widget_label)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.list_functions = QtGui.QListWidget(FunctionsDialog)
        self.list_functions.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.list_functions.setWordWrap(True)
        self.list_functions.setObjectName(_fromUtf8("list_functions"))
        self.verticalLayout.addWidget(self.list_functions)
        self.parameter_box = QtGui.QWidget(FunctionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameter_box.sizePolicy().hasHeightForWidth())
        self.parameter_box.setSizePolicy(sizePolicy)
        self.parameter_box.setObjectName(_fromUtf8("parameter_box"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.parameter_box)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.parameter_box)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.edit_function_value = QtGui.QLineEdit(self.parameter_box)
        self.edit_function_value.setObjectName(_fromUtf8("edit_function_value"))
        self.horizontalLayout_2.addWidget(self.edit_function_value)
        self.verticalLayout.addWidget(self.parameter_box)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.list_selected_columns = CoqListWidget(FunctionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_selected_columns.sizePolicy().hasHeightForWidth())
        self.list_selected_columns.setSizePolicy(sizePolicy)
        self.list_selected_columns.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.list_selected_columns.setObjectName(_fromUtf8("list_selected_columns"))
        self.gridLayout.addWidget(self.list_selected_columns, 1, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.button_up = QtGui.QToolButton(FunctionsDialog)
        self.button_up.setText(_fromUtf8(""))
        self.button_up.setObjectName(_fromUtf8("button_up"))
        self.verticalLayout_5.addWidget(self.button_up, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.button_add = QtGui.QToolButton(FunctionsDialog)
        self.button_add.setText(_fromUtf8(""))
        self.button_add.setObjectName(_fromUtf8("button_add"))
        self.horizontalLayout_6.addWidget(self.button_add)
        self.button_remove = QtGui.QToolButton(FunctionsDialog)
        self.button_remove.setText(_fromUtf8(""))
        self.button_remove.setObjectName(_fromUtf8("button_remove"))
        self.horizontalLayout_6.addWidget(self.button_remove, QtCore.Qt.AlignVCenter)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.button_down = QtGui.QToolButton(FunctionsDialog)
        self.button_down.setText(_fromUtf8(""))
        self.button_down.setObjectName(_fromUtf8("button_down"))
        self.verticalLayout_5.addWidget(self.button_down, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.list_available_columns = QtGui.QListWidget(FunctionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_available_columns.sizePolicy().hasHeightForWidth())
        self.list_available_columns.setSizePolicy(sizePolicy)
        self.list_available_columns.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.list_available_columns.setObjectName(_fromUtf8("list_available_columns"))
        self.gridLayout.addWidget(self.list_available_columns, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(FunctionsDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(FunctionsDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.box_combine = QtGui.QWidget(FunctionsDialog)
        self.box_combine.setObjectName(_fromUtf8("box_combine"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.box_combine)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.box_combine)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.combo_combine = QtGui.QComboBox(self.box_combine)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_combine.sizePolicy().hasHeightForWidth())
        self.combo_combine.setSizePolicy(sizePolicy)
        self.combo_combine.setObjectName(_fromUtf8("combo_combine"))
        self.horizontalLayout_4.addWidget(self.combo_combine)
        self.gridLayout.addWidget(self.box_combine, 2, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.buttonBox = QtGui.QDialogButtonBox(FunctionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label.setBuddy(self.edit_label)
        self.label_5.setBuddy(self.edit_function_value)
        self.label_2.setBuddy(self.list_available_columns)
        self.label_3.setBuddy(self.list_selected_columns)
        self.label_4.setBuddy(self.combo_combine)

        self.retranslateUi(FunctionsDialog)
        self.list_functions.setCurrentRow(-1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), FunctionsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), FunctionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FunctionsDialog)

    def retranslateUi(self, FunctionsDialog):
        FunctionsDialog.setWindowTitle(_translate("FunctionsDialog", "Add a function – Coquery", None))
        self.label.setText(_translate("FunctionsDialog", "&Label:", None))
        self.list_functions.setSortingEnabled(True)
        self.label_5.setText(_translate("FunctionsDialog", "Ar&gument:", None))
        self.edit_function_value.setPlaceholderText(_translate("FunctionsDialog", "(no value specified)", None))
        self.label_2.setText(_translate("FunctionsDialog", "&Available columns:", None))
        self.label_3.setText(_translate("FunctionsDialog", "&Selected columns:", None))
        self.label_4.setText(_translate("FunctionsDialog", "&Combine values:", None))

from ..classes import CoqListWidget

