# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectionConfiguration.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConnectionConfig(object):
    def setupUi(self, ConnectionConfig):
        ConnectionConfig.setObjectName("ConnectionConfig")
        ConnectionConfig.resize(800, 752)
        self.gridLayout_6 = QtWidgets.QGridLayout(ConnectionConfig)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.list_config = QtWidgets.QListWidget(ConnectionConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_config.sizePolicy().hasHeightForWidth())
        self.list_config.setSizePolicy(sizePolicy)
        self.list_config.setObjectName("list_config")
        self.gridLayout_3.addWidget(self.list_config, 0, 0, 1, 2)
        self.button_add = QtWidgets.QPushButton(ConnectionConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add.sizePolicy().hasHeightForWidth())
        self.button_add.setSizePolicy(sizePolicy)
        self.button_add.setObjectName("button_add")
        self.gridLayout_3.addWidget(self.button_add, 1, 0, 1, 1)
        self.button_remove = QtWidgets.QPushButton(ConnectionConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_remove.sizePolicy().hasHeightForWidth())
        self.button_remove.setSizePolicy(sizePolicy)
        self.button_remove.setObjectName("button_remove")
        self.gridLayout_3.addWidget(self.button_remove, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 3, 1)
        self.group_general = QtWidgets.QGroupBox(ConnectionConfig)
        self.group_general.setObjectName("group_general")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.group_general)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.group_general)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.connection_name = QtWidgets.QLineEdit(self.group_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_name.sizePolicy().hasHeightForWidth())
        self.connection_name.setSizePolicy(sizePolicy)
        self.connection_name.setClearButtonEnabled(True)
        self.connection_name.setObjectName("connection_name")
        self.gridLayout_4.addWidget(self.connection_name, 0, 1, 1, 3)
        self.label_mysql_server = QtWidgets.QLabel(self.group_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mysql_server.sizePolicy().hasHeightForWidth())
        self.label_mysql_server.setSizePolicy(sizePolicy)
        self.label_mysql_server.setObjectName("label_mysql_server")
        self.gridLayout_4.addWidget(self.label_mysql_server, 1, 0, 1, 2)
        self.radio_sqlite = QtWidgets.QRadioButton(self.group_general)
        self.radio_sqlite.setChecked(True)
        self.radio_sqlite.setObjectName("radio_sqlite")
        self.gridLayout_4.addWidget(self.radio_sqlite, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.radio_mysql = QtWidgets.QRadioButton(self.group_general)
        self.radio_mysql.setObjectName("radio_mysql")
        self.gridLayout_4.addWidget(self.radio_mysql, 1, 3, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_6.addWidget(self.group_general, 0, 1, 1, 1)
        self.frame_sqlite = QtWidgets.QFrame(ConnectionConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_sqlite.sizePolicy().hasHeightForWidth())
        self.frame_sqlite.setSizePolicy(sizePolicy)
        self.frame_sqlite.setObjectName("frame_sqlite")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_sqlite)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_db_path = QtWidgets.QPushButton(self.frame_sqlite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_db_path.sizePolicy().hasHeightForWidth())
        self.button_db_path.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("folder")
        self.button_db_path.setIcon(icon)
        self.button_db_path.setObjectName("button_db_path")
        self.gridLayout_5.addWidget(self.button_db_path, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 2, 0, 1, 1)
        self.input_db_path = QtWidgets.QLineEdit(self.frame_sqlite)
        self.input_db_path.setEnabled(True)
        self.input_db_path.setPlaceholderText("")
        self.input_db_path.setObjectName("input_db_path")
        self.gridLayout_5.addWidget(self.input_db_path, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_sqlite)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 2)
        self.gridLayout_6.addWidget(self.frame_sqlite, 1, 1, 1, 1)
        self.frame_mysql = QtWidgets.QWidget(ConnectionConfig)
        self.frame_mysql.setObjectName("frame_mysql")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_mysql)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.group_credentials = QtWidgets.QGroupBox(self.frame_mysql)
        self.group_credentials.setObjectName("group_credentials")
        self.gridLayout = QtWidgets.QGridLayout(self.group_credentials)
        self.gridLayout.setObjectName("gridLayout")
        self.button_create_user = QtWidgets.QPushButton(self.group_credentials)
        self.button_create_user.setObjectName("button_create_user")
        self.gridLayout.addWidget(self.button_create_user, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.group_credentials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.group_credentials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.group_credentials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)
        self.user = QtWidgets.QLineEdit(self.group_credentials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user.sizePolicy().hasHeightForWidth())
        self.user.setSizePolicy(sizePolicy)
        self.user.setClearButtonEnabled(True)
        self.user.setObjectName("user")
        self.gridLayout.addWidget(self.user, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.group_credentials)
        self.group_server = QtWidgets.QGroupBox(self.frame_mysql)
        self.group_server.setObjectName("group_server")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_server)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radio_local = QtWidgets.QRadioButton(self.group_server)
        self.radio_local.setChecked(True)
        self.radio_local.setObjectName("radio_local")
        self.gridLayout_2.addWidget(self.radio_local, 0, 0, 1, 2)
        self.radio_remote = QtWidgets.QRadioButton(self.group_server)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_remote.sizePolicy().hasHeightForWidth())
        self.radio_remote.setSizePolicy(sizePolicy)
        self.radio_remote.setObjectName("radio_remote")
        self.gridLayout_2.addWidget(self.radio_remote, 1, 0, 1, 1)
        self.hostname = QtWidgets.QLineEdit(self.group_server)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostname.sizePolicy().hasHeightForWidth())
        self.hostname.setSizePolicy(sizePolicy)
        self.hostname.setInputMask("")
        self.hostname.setText("")
        self.hostname.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.hostname.setClearButtonEnabled(True)
        self.hostname.setObjectName("hostname")
        self.gridLayout_2.addWidget(self.hostname, 1, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.group_server)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 2)
        self.port = QtWidgets.QSpinBox(self.group_server)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port.sizePolicy().hasHeightForWidth())
        self.port.setSizePolicy(sizePolicy)
        self.port.setMinimum(1)
        self.port.setMaximum(65535)
        self.port.setProperty("value", 3306)
        self.port.setObjectName("port")
        self.gridLayout_2.addWidget(self.port, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.group_server)
        self.connection_indicator = QtWidgets.QFrame(self.frame_mysql)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_indicator.sizePolicy().hasHeightForWidth())
        self.connection_indicator.setSizePolicy(sizePolicy)
        self.connection_indicator.setObjectName("connection_indicator")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.connection_indicator)
        self.gridLayout_7.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_6 = QtWidgets.QLabel(self.connection_indicator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.button_status = QtWidgets.QPushButton(self.connection_indicator)
        self.button_status.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_status.sizePolicy().hasHeightForWidth())
        self.button_status.setSizePolicy(sizePolicy)
        self.button_status.setText("")
        self.button_status.setAutoDefault(False)
        self.button_status.setObjectName("button_status")
        self.gridLayout_7.addWidget(self.button_status, 0, 1, 1, 1)
        self.text_status = QtWidgets.QTextEdit(self.connection_indicator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_status.sizePolicy().hasHeightForWidth())
        self.text_status.setSizePolicy(sizePolicy)
        self.text_status.setObjectName("text_status")
        self.gridLayout_7.addWidget(self.text_status, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.connection_indicator)
        self.verticalLayout_2.setStretch(2, 1)
        self.gridLayout_6.addWidget(self.frame_mysql, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConnectionConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_6.addWidget(self.buttonBox, 3, 1, 1, 1)
        self.label_3.setBuddy(self.connection_name)
        self.label_5.setBuddy(self.input_db_path)
        self.label.setBuddy(self.user)
        self.label_2.setBuddy(self.password)
        self.label_4.setBuddy(self.port)

        self.retranslateUi(ConnectionConfig)
        self.buttonBox.accepted.connect(ConnectionConfig.accept)
        self.buttonBox.rejected.connect(ConnectionConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(ConnectionConfig)
        ConnectionConfig.setTabOrder(self.connection_name, self.radio_sqlite)
        ConnectionConfig.setTabOrder(self.radio_sqlite, self.radio_mysql)
        ConnectionConfig.setTabOrder(self.radio_mysql, self.input_db_path)
        ConnectionConfig.setTabOrder(self.input_db_path, self.button_db_path)
        ConnectionConfig.setTabOrder(self.button_db_path, self.user)
        ConnectionConfig.setTabOrder(self.user, self.button_create_user)
        ConnectionConfig.setTabOrder(self.button_create_user, self.password)
        ConnectionConfig.setTabOrder(self.password, self.radio_local)
        ConnectionConfig.setTabOrder(self.radio_local, self.radio_remote)
        ConnectionConfig.setTabOrder(self.radio_remote, self.hostname)
        ConnectionConfig.setTabOrder(self.hostname, self.port)
        ConnectionConfig.setTabOrder(self.port, self.text_status)
        ConnectionConfig.setTabOrder(self.text_status, self.list_config)
        ConnectionConfig.setTabOrder(self.list_config, self.button_add)
        ConnectionConfig.setTabOrder(self.button_add, self.button_remove)
        ConnectionConfig.setTabOrder(self.button_remove, self.button_status)

    def retranslateUi(self, ConnectionConfig):
        _translate = QtCore.QCoreApplication.translate
        ConnectionConfig.setWindowTitle(_translate("ConnectionConfig", "Database connections – Coquery"))
        self.button_add.setText(_translate("ConnectionConfig", "A&dd"))
        self.button_remove.setText(_translate("ConnectionConfig", "Re&move"))
        self.group_general.setTitle(_translate("ConnectionConfig", "General settings"))
        self.label_3.setText(_translate("ConnectionConfig", "&Connection name:"))
        self.connection_name.setText(_translate("ConnectionConfig", "Default"))
        self.connection_name.setPlaceholderText(_translate("ConnectionConfig", "(untitled)"))
        self.label_mysql_server.setText(_translate("ConnectionConfig", "Use MySQL server:"))
        self.radio_sqlite.setText(_translate("ConnectionConfig", "&No"))
        self.radio_mysql.setText(_translate("ConnectionConfig", "&Yes"))
        self.button_db_path.setText(_translate("ConnectionConfig", "&Browse"))
        self.button_db_path.setShortcut(_translate("ConnectionConfig", "Alt+B"))
        self.label_5.setText(_translate("ConnectionConfig", "Da&tabase directory:"))
        self.group_credentials.setTitle(_translate("ConnectionConfig", "User credentials"))
        self.button_create_user.setText(_translate("ConnectionConfig", "&Create user"))
        self.label.setText(_translate("ConnectionConfig", "&User name:"))
        self.label_2.setText(_translate("ConnectionConfig", "Pass&word:"))
        self.password.setText(_translate("ConnectionConfig", "coquery"))
        self.user.setText(_translate("ConnectionConfig", "coquery"))
        self.group_server.setTitle(_translate("ConnectionConfig", "Server location"))
        self.radio_local.setText(_translate("ConnectionConfig", "Local server on &this computer"))
        self.radio_remote.setText(_translate("ConnectionConfig", "URL or IP address:"))
        self.hostname.setPlaceholderText(_translate("ConnectionConfig", "(URL or IP address)"))
        self.label_4.setText(_translate("ConnectionConfig", "&Port number:"))
        self.label_6.setText(_translate("ConnectionConfig", "Connection status:"))

