# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contextViewerAudio.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ContextViewAudio(object):
    def setupUi(self, ContextViewAudio):
        ContextViewAudio.setObjectName("ContextViewAudio")
        ContextViewAudio.resize(640, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ContextViewAudio)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tab_widget = QtWidgets.QTabWidget(ContextViewAudio)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget.setObjectName("tab_widget")
        self.tab_context = QtWidgets.QWidget()
        self.tab_context.setObjectName("tab_context")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_context)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_ids = CoqDetailBox(self.tab_context)
        self.button_ids.setObjectName("button_ids")
        self.verticalLayout_4.addWidget(self.button_ids)
        self.context_area = QtWidgets.QTextBrowser(self.tab_context)
        self.context_area.setAutoFillBackground(False)
        self.context_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.context_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.context_area.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.context_area.setObjectName("context_area")
        self.verticalLayout_4.addWidget(self.context_area)
        self.progress_bar = QtWidgets.QProgressBar(self.tab_context)
        self.progress_bar.setMaximum(0)
        self.progress_bar.setProperty("value", -1)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_4.addWidget(self.progress_bar)
        self.tab_widget.addTab(self.tab_context, "")
        self.tab_textgrid = QtWidgets.QWidget()
        self.tab_textgrid.setObjectName("tab_textgrid")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_textgrid)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textgrid_area = CoqTextgridView(self.tab_textgrid)
        self.textgrid_area.setObjectName("textgrid_area")
        self.verticalLayout.addWidget(self.textgrid_area)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_textgrid)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spin_dynamic_range = QtWidgets.QDoubleSpinBox(self.tab_textgrid)
        self.spin_dynamic_range.setMinimum(1.0)
        self.spin_dynamic_range.setProperty("value", 50.0)
        self.spin_dynamic_range.setObjectName("spin_dynamic_range")
        self.horizontalLayout_3.addWidget(self.spin_dynamic_range)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab_textgrid)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spin_window_length = QtWidgets.QDoubleSpinBox(self.tab_textgrid)
        self.spin_window_length.setDecimals(4)
        self.spin_window_length.setMinimum(0.001)
        self.spin_window_length.setMaximum(1.0)
        self.spin_window_length.setSingleStep(0.001)
        self.spin_window_length.setProperty("value", 0.005)
        self.spin_window_length.setObjectName("spin_window_length")
        self.horizontalLayout_4.addWidget(self.spin_window_length)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.tab_widget.addTab(self.tab_textgrid, "")
        self.verticalLayout_2.addWidget(self.tab_widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(4, -1, 4, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(ContextViewAudio)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spin_context_width = QtWidgets.QSpinBox(ContextViewAudio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_context_width.sizePolicy().hasHeightForWidth())
        self.spin_context_width.setSizePolicy(sizePolicy)
        self.spin_context_width.setFrame(True)
        self.spin_context_width.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spin_context_width.setMaximum(1000)
        self.spin_context_width.setProperty("value", 10)
        self.spin_context_width.setObjectName("spin_context_width")
        self.horizontalLayout.addWidget(self.spin_context_width)
        self.slider_context_width = QtWidgets.QSlider(ContextViewAudio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_context_width.sizePolicy().hasHeightForWidth())
        self.slider_context_width.setSizePolicy(sizePolicy)
        self.slider_context_width.setMinimum(0)
        self.slider_context_width.setMaximum(1000)
        self.slider_context_width.setPageStep(25)
        self.slider_context_width.setProperty("value", 10)
        self.slider_context_width.setSliderPosition(10)
        self.slider_context_width.setOrientation(QtCore.Qt.Horizontal)
        self.slider_context_width.setInvertedAppearance(False)
        self.slider_context_width.setInvertedControls(False)
        self.slider_context_width.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_context_width.setTickInterval(10)
        self.slider_context_width.setObjectName("slider_context_width")
        self.horizontalLayout.addWidget(self.slider_context_width)
        self.button_prev = QtWidgets.QPushButton(ContextViewAudio)
        self.button_prev.setObjectName("button_prev")
        self.horizontalLayout.addWidget(self.button_prev)
        self.button_next = QtWidgets.QPushButton(ContextViewAudio)
        self.button_next.setObjectName("button_next")
        self.horizontalLayout.addWidget(self.button_next)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.spin_dynamic_range)
        self.label_2.setBuddy(self.spin_window_length)
        self.label_4.setBuddy(self.spin_context_width)

        self.retranslateUi(ContextViewAudio)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ContextViewAudio)

    def retranslateUi(self, ContextViewAudio):
        _translate = QtCore.QCoreApplication.translate
        ContextViewAudio.setWindowTitle(_translate("ContextViewAudio", "Context view – Coquery"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_context), _translate("ContextViewAudio", "Text"))
        self.label.setText(_translate("ContextViewAudio", "Dyna&mic range:"))
        self.spin_dynamic_range.setSuffix(_translate("ContextViewAudio", " dB"))
        self.label_2.setText(_translate("ContextViewAudio", "Window &length:"))
        self.spin_window_length.setSuffix(_translate("ContextViewAudio", " s"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_textgrid), _translate("ContextViewAudio", "&Audio"))
        self.label_4.setText(_translate("ContextViewAudio", "&Context size:"))
        self.spin_context_width.setSpecialValueText(_translate("ContextViewAudio", "none"))
        self.spin_context_width.setSuffix(_translate("ContextViewAudio", " words"))
        self.button_prev.setToolTip(_translate("ContextViewAudio", "Show previous context"))
        self.button_prev.setText(_translate("ContextViewAudio", "Previous"))
        self.button_next.setToolTip(_translate("ContextViewAudio", "Show next context"))
        self.button_next.setText(_translate("ContextViewAudio", "Next"))

from ..classes import CoqDetailBox
from ..textgridview import CoqTextgridView
