# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coqEditFilters.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CoqEditFilters(object):
    def setupUi(self, CoqEditFilters):
        CoqEditFilters.setObjectName("CoqEditFilters")
        CoqEditFilters.resize(640, 480)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(CoqEditFilters)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table_filters = QtWidgets.QTableWidget(CoqEditFilters)
        self.table_filters.setShowGrid(False)
        self.table_filters.setColumnCount(1)
        self.table_filters.setObjectName("table_filters")
        self.table_filters.setRowCount(0)
        self.table_filters.horizontalHeader().setVisible(False)
        self.table_filters.horizontalHeader().setStretchLastSection(True)
        self.table_filters.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.table_filters)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(CoqEditFilters)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.list_columns = QtWidgets.QListWidget(CoqEditFilters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_columns.sizePolicy().hasHeightForWidth())
        self.list_columns.setSizePolicy(sizePolicy)
        self.list_columns.setObjectName("list_columns")
        self.verticalLayout_5.addWidget(self.list_columns)
        self.check_before_transformation = QtWidgets.QCheckBox(CoqEditFilters)
        self.check_before_transformation.setObjectName("check_before_transformation")
        self.verticalLayout_5.addWidget(self.check_before_transformation)
        self.verticalLayout_5.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(CoqEditFilters)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(CoqEditFilters)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.radio_OP_EQ = QtWidgets.QRadioButton(CoqEditFilters)
        self.radio_OP_EQ.setChecked(True)
        self.radio_OP_EQ.setObjectName("radio_OP_EQ")
        self.verticalLayout.addWidget(self.radio_OP_EQ)
        self.radio_OP_NE = QtWidgets.QRadioButton(CoqEditFilters)
        self.radio_OP_NE.setObjectName("radio_OP_NE")
        self.verticalLayout.addWidget(self.radio_OP_NE)
        self.radio_OP_LT = QtWidgets.QRadioButton(CoqEditFilters)
        self.radio_OP_LT.setObjectName("radio_OP_LT")
        self.verticalLayout.addWidget(self.radio_OP_LT)
        self.radio_OP_LE = QtWidgets.QRadioButton(CoqEditFilters)
        self.radio_OP_LE.setObjectName("radio_OP_LE")
        self.verticalLayout.addWidget(self.radio_OP_LE)
        self.radio_OP_GT = QtWidgets.QRadioButton(CoqEditFilters)
        self.radio_OP_GT.setObjectName("radio_OP_GT")
        self.verticalLayout.addWidget(self.radio_OP_GT)
        self.radio_OP_GE = QtWidgets.QRadioButton(CoqEditFilters)
        self.radio_OP_GE.setObjectName("radio_OP_GE")
        self.verticalLayout.addWidget(self.radio_OP_GE)
        self.radio_OP_MATCH = QtWidgets.QRadioButton(CoqEditFilters)
        self.radio_OP_MATCH.setObjectName("radio_OP_MATCH")
        self.verticalLayout.addWidget(self.radio_OP_MATCH)
        self.radio_OP_NMATCH = QtWidgets.QRadioButton(CoqEditFilters)
        self.radio_OP_NMATCH.setObjectName("radio_OP_NMATCH")
        self.verticalLayout.addWidget(self.radio_OP_NMATCH)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(CoqEditFilters)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(CoqEditFilters)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.edit_value = QtWidgets.QLineEdit(CoqEditFilters)
        self.edit_value.setObjectName("edit_value")
        self.gridLayout.addWidget(self.edit_value, 1, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(195, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 3)
        self.button_add = QtWidgets.QPushButton(CoqEditFilters)
        self.button_add.setObjectName("button_add")
        self.gridLayout.addWidget(self.button_add, 3, 1, 1, 1)
        self.button_remove = QtWidgets.QPushButton(CoqEditFilters)
        self.button_remove.setObjectName("button_remove")
        self.gridLayout.addWidget(self.button_remove, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(195, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 0, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 2, 2, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(5, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(0, 1)
        self.label_2.setBuddy(self.list_columns)
        self.label_3.setBuddy(self.radio_OP_EQ)
        self.label.setBuddy(self.edit_value)

        self.retranslateUi(CoqEditFilters)
        QtCore.QMetaObject.connectSlotsByName(CoqEditFilters)

    def retranslateUi(self, CoqEditFilters):
        _translate = QtCore.QCoreApplication.translate
        CoqEditFilters.setWindowTitle(_translate("CoqEditFilters", "Form"))
        self.label_2.setText(_translate("CoqEditFilters", "&Column:"))
        self.check_before_transformation.setText(_translate("CoqEditFilters", "&Apply before transformation"))
        self.label_3.setText(_translate("CoqEditFilters", "&Relation:"))
        self.radio_OP_EQ.setText(_translate("CoqEditFilters", "equals"))
        self.radio_OP_NE.setText(_translate("CoqEditFilters", "does not equal"))
        self.radio_OP_LT.setText(_translate("CoqEditFilters", "is less than"))
        self.radio_OP_LE.setText(_translate("CoqEditFilters", "is less or equal to"))
        self.radio_OP_GT.setText(_translate("CoqEditFilters", "is greater than"))
        self.radio_OP_GE.setText(_translate("CoqEditFilters", "is greater or equal to"))
        self.radio_OP_MATCH.setText(_translate("CoqEditFilters", "matches"))
        self.radio_OP_NMATCH.setText(_translate("CoqEditFilters", "does not match"))
        self.label.setText(_translate("CoqEditFilters", "&Value:"))
        self.button_add.setText(_translate("CoqEditFilters", "&Add"))
        self.button_remove.setText(_translate("CoqEditFilters", "&Remove"))

