# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coquery.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from coquery.gui.pyqt_compat import QtCore, QtGui, frameShadow, frameShape

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1113, 762)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.options_area = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.options_area.sizePolicy().hasHeightForWidth())
        self.options_area.setSizePolicy(sizePolicy)
        self.options_area.setObjectName(_fromUtf8("options_area"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.options_area)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.box_corpus_select = QtGui.QGroupBox(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_corpus_select.sizePolicy().hasHeightForWidth())
        self.box_corpus_select.setSizePolicy(sizePolicy)
        self.box_corpus_select.setObjectName(_fromUtf8("box_corpus_select"))
        self.output_columns = QtGui.QVBoxLayout(self.box_corpus_select)
        self.output_columns.setContentsMargins(8, 4, 8, 4)
        self.output_columns.setSpacing(0)
        self.output_columns.setObjectName(_fromUtf8("output_columns"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.combo_corpus = QtGui.QComboBox(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_corpus.sizePolicy().hasHeightForWidth())
        self.combo_corpus.setSizePolicy(sizePolicy)
        self.combo_corpus.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.combo_corpus.setEditable(False)
        self.combo_corpus.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.combo_corpus.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.combo_corpus.setFrame(True)
        self.combo_corpus.setObjectName(_fromUtf8("combo_corpus"))
        self.horizontalLayout_2.addWidget(self.combo_corpus)
        self.output_columns.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.box_corpus_select)
        self.frame_buttons = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons.sizePolicy().hasHeightForWidth())
        self.frame_buttons.setSizePolicy(sizePolicy)
        self.frame_buttons.setObjectName(_fromUtf8("frame_buttons"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_buttons)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout.addWidget(self.frame_buttons)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.box_input_settings = QtGui.QGroupBox(self.options_area)
        self.box_input_settings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.box_input_settings.setObjectName(_fromUtf8("box_input_settings"))
        self.gridLayout_3 = QtGui.QGridLayout(self.box_input_settings)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radio_query_string = QtGui.QRadioButton(self.box_input_settings)
        self.radio_query_string.setText(_fromUtf8(""))
        self.radio_query_string.setChecked(True)
        self.radio_query_string.setObjectName(_fromUtf8("radio_query_string"))
        self.gridLayout_3.addWidget(self.radio_query_string, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.edit_query_string = CoqTextEdit(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_query_string.sizePolicy().hasHeightForWidth())
        self.edit_query_string.setSizePolicy(sizePolicy)
        self.edit_query_string.setObjectName(_fromUtf8("edit_query_string"))
        self.gridLayout_3.addWidget(self.edit_query_string, 0, 1, 1, 1)
        self.radio_query_file = QtGui.QRadioButton(self.box_input_settings)
        self.radio_query_file.setText(_fromUtf8(""))
        self.radio_query_file.setObjectName(_fromUtf8("radio_query_file"))
        self.gridLayout_3.addWidget(self.radio_query_file, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.edit_file_name = QtGui.QLineEdit(self.box_input_settings)
        self.edit_file_name.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_file_name.sizePolicy().hasHeightForWidth())
        self.edit_file_name.setSizePolicy(sizePolicy)
        self.edit_file_name.setAccessibleDescription(_fromUtf8(""))
        self.edit_file_name.setReadOnly(True)
        self.edit_file_name.setObjectName(_fromUtf8("edit_file_name"))
        self.gridLayout_6.addWidget(self.edit_file_name, 0, 0, 1, 1)
        self.button_change_file = QtGui.QPushButton(self.box_input_settings)
        self.button_change_file.setObjectName(_fromUtf8("button_change_file"))
        self.gridLayout_6.addWidget(self.button_change_file, 0, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_3.addLayout(self.gridLayout_6, 1, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.box_input_settings)
        self.groupBox_2 = QtGui.QGroupBox(self.options_area)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.button_run_query = QtGui.QPushButton(self.groupBox_2)
        self.button_run_query.setAutoDefault(True)
        self.button_run_query.setDefault(True)
        self.button_run_query.setObjectName(_fromUtf8("button_run_query"))
        self.horizontalLayout_3.addWidget(self.button_run_query)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.groupBox = QtGui.QGroupBox(self.options_area)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.box_functions = QtGui.QVBoxLayout(self.groupBox)
        self.box_functions.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.box_functions.setContentsMargins(4, -1, 4, 0)
        self.box_functions.setSpacing(4)
        self.box_functions.setObjectName(_fromUtf8("box_functions"))
        self.list_toolbox = QtGui.QTableWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_toolbox.sizePolicy().hasHeightForWidth())
        self.list_toolbox.setSizePolicy(sizePolicy)
        self.list_toolbox.setAutoScroll(False)
        self.list_toolbox.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.list_toolbox.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.list_toolbox.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.list_toolbox.setShowGrid(False)
        self.list_toolbox.setRowCount(5)
        self.list_toolbox.setColumnCount(3)
        self.list_toolbox.setObjectName(_fromUtf8("list_toolbox"))
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.list_toolbox.setItem(4, 2, item)
        self.list_toolbox.horizontalHeader().setVisible(False)
        self.list_toolbox.verticalHeader().setVisible(False)
        self.box_functions.addWidget(self.list_toolbox)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.box_functions.addWidget(self.line)
        self.tool_widget = QtGui.QStackedWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_widget.sizePolicy().hasHeightForWidth())
        self.tool_widget.setSizePolicy(sizePolicy)
        self.tool_widget.setObjectName(_fromUtf8("tool_widget"))
        self.tool_widgetPage1 = QtGui.QWidget()
        self.tool_widgetPage1.setObjectName(_fromUtf8("tool_widgetPage1"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tool_widgetPage1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.check_context = QtGui.QCheckBox(self.tool_widgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_context.sizePolicy().hasHeightForWidth())
        self.check_context.setSizePolicy(sizePolicy)
        self.check_context.setText(_fromUtf8(""))
        self.check_context.setObjectName(_fromUtf8("check_context"))
        self.gridLayout.addWidget(self.check_context, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.tool_widgetPage1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.widget_context = QtGui.QWidget(self.tool_widgetPage1)
        self.widget_context.setObjectName(_fromUtf8("widget_context"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_context)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radio_context_mode_kwic = QtGui.QRadioButton(self.widget_context)
        self.radio_context_mode_kwic.setStyleSheet(_fromUtf8("text-align: center center"))
        self.radio_context_mode_kwic.setObjectName(_fromUtf8("radio_context_mode_kwic"))
        self.verticalLayout_2.addWidget(self.radio_context_mode_kwic)
        self.radio_context_mode_string = QtGui.QRadioButton(self.widget_context)
        self.radio_context_mode_string.setStyleSheet(_fromUtf8("text-align: center center"))
        self.radio_context_mode_string.setObjectName(_fromUtf8("radio_context_mode_string"))
        self.verticalLayout_2.addWidget(self.radio_context_mode_string)
        self.radio_context_mode_columns = QtGui.QRadioButton(self.widget_context)
        self.radio_context_mode_columns.setStyleSheet(_fromUtf8("text-align: center center"))
        self.radio_context_mode_columns.setObjectName(_fromUtf8("radio_context_mode_columns"))
        self.verticalLayout_2.addWidget(self.radio_context_mode_columns)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.context_left_span = QtGui.QSpinBox(self.widget_context)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span.sizePolicy().hasHeightForWidth())
        self.context_left_span.setSizePolicy(sizePolicy)
        self.context_left_span.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.context_left_span.setSuffix(_fromUtf8(""))
        self.context_left_span.setObjectName(_fromUtf8("context_left_span"))
        self.horizontalLayout_4.addWidget(self.context_left_span)
        self.context_right_span = QtGui.QSpinBox(self.widget_context)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_right_span.sizePolicy().hasHeightForWidth())
        self.context_right_span.setSizePolicy(sizePolicy)
        self.context_right_span.setFrame(True)
        self.context_right_span.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.context_right_span.setSuffix(_fromUtf8(""))
        self.context_right_span.setObjectName(_fromUtf8("context_right_span"))
        self.horizontalLayout_4.addWidget(self.context_right_span, QtCore.Qt.AlignTop)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.widget_context, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.tool_widget.addWidget(self.tool_widgetPage1)
        self.tool_widgetPage2 = QtGui.QWidget()
        self.tool_widgetPage2.setObjectName(_fromUtf8("tool_widgetPage2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tool_widgetPage2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.check_stopwords = QtGui.QCheckBox(self.tool_widgetPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_stopwords.sizePolicy().hasHeightForWidth())
        self.check_stopwords.setSizePolicy(sizePolicy)
        self.check_stopwords.setText(_fromUtf8(""))
        self.check_stopwords.setObjectName(_fromUtf8("check_stopwords"))
        self.gridLayout_2.addWidget(self.check_stopwords, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tool_widgetPage2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.widget_stopwords = QtGui.QWidget(self.tool_widgetPage2)
        self.widget_stopwords.setObjectName(_fromUtf8("widget_stopwords"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_stopwords)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.button_stopwords = QtGui.QPushButton(self.widget_stopwords)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stopwords.sizePolicy().hasHeightForWidth())
        self.button_stopwords.setSizePolicy(sizePolicy)
        self.button_stopwords.setObjectName(_fromUtf8("button_stopwords"))
        self.verticalLayout_8.addWidget(self.button_stopwords)
        spacerItem3 = QtGui.QSpacerItem(115, 191, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.gridLayout_2.addWidget(self.widget_stopwords, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tool_widget.addWidget(self.tool_widgetPage2)
        self.tool_widgetPage3 = QtGui.QWidget()
        self.tool_widgetPage3.setObjectName(_fromUtf8("tool_widgetPage3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tool_widgetPage3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget_grouping = QtGui.QWidget(self.tool_widgetPage3)
        self.widget_grouping.setObjectName(_fromUtf8("widget_grouping"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget_grouping)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.button_add_group_function = QtGui.QPushButton(self.widget_grouping)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_group_function.sizePolicy().hasHeightForWidth())
        self.button_add_group_function.setSizePolicy(sizePolicy)
        self.button_add_group_function.setObjectName(_fromUtf8("button_add_group_function"))
        self.verticalLayout_9.addWidget(self.button_add_group_function)
        self.button_filters_2 = QtGui.QPushButton(self.widget_grouping)
        self.button_filters_2.setObjectName(_fromUtf8("button_filters_2"))
        self.verticalLayout_9.addWidget(self.button_filters_2)
        self.gridLayout_4.addWidget(self.widget_grouping, 3, 1, 1, 1)
        self.check_grouping = QtGui.QCheckBox(self.tool_widgetPage3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_grouping.sizePolicy().hasHeightForWidth())
        self.check_grouping.setSizePolicy(sizePolicy)
        self.check_grouping.setText(_fromUtf8(""))
        self.check_grouping.setObjectName(_fromUtf8("check_grouping"))
        self.gridLayout_4.addWidget(self.check_grouping, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tool_widgetPage3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.list_group_columns = CoqListWidget(self.tool_widgetPage3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_group_columns.sizePolicy().hasHeightForWidth())
        self.list_group_columns.setSizePolicy(sizePolicy)
        self.list_group_columns.setObjectName(_fromUtf8("list_group_columns"))
        self.horizontalLayout_6.addWidget(self.list_group_columns)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        spacerItem4 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem5)
        self.verticalLayout_14.setStretch(0, 1)
        self.verticalLayout_14.setStretch(1, 1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.horizontalLayout_6.setStretch(0, 1)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.button_remove_group = QtGui.QPushButton(self.tool_widgetPage3)
        self.button_remove_group.setObjectName(_fromUtf8("button_remove_group"))
        self.horizontalLayout_8.addWidget(self.button_remove_group)
        self.button_group_up = QtGui.QToolButton(self.tool_widgetPage3)
        self.button_group_up.setText(_fromUtf8(""))
        self.button_group_up.setObjectName(_fromUtf8("button_group_up"))
        self.horizontalLayout_8.addWidget(self.button_group_up)
        self.button_group_down = QtGui.QToolButton(self.tool_widgetPage3)
        self.button_group_down.setText(_fromUtf8(""))
        self.button_group_down.setObjectName(_fromUtf8("button_group_down"))
        self.horizontalLayout_8.addWidget(self.button_group_down)
        self.horizontalLayout_8.setStretch(0, 1)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setRowStretch(1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.tool_widget.addWidget(self.tool_widgetPage3)
        self.tool_widgetPage4 = QtGui.QWidget()
        self.tool_widgetPage4.setObjectName(_fromUtf8("tool_widgetPage4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tool_widgetPage4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.check_aggregate = QtGui.QCheckBox(self.tool_widgetPage4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_aggregate.sizePolicy().hasHeightForWidth())
        self.check_aggregate.setSizePolicy(sizePolicy)
        self.check_aggregate.setText(_fromUtf8(""))
        self.check_aggregate.setObjectName(_fromUtf8("check_aggregate"))
        self.gridLayout_5.addWidget(self.check_aggregate, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tool_widgetPage4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 1)
        self.widget_aggregate = QtGui.QWidget(self.tool_widgetPage4)
        self.widget_aggregate.setObjectName(_fromUtf8("widget_aggregate"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget_aggregate)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.combo_aggregate = QtGui.QComboBox(self.widget_aggregate)
        self.combo_aggregate.setObjectName(_fromUtf8("combo_aggregate"))
        self.verticalLayout_10.addWidget(self.combo_aggregate)
        self.gridLayout_5.addWidget(self.widget_aggregate, 1, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        spacerItem6 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.tool_widget.addWidget(self.tool_widgetPage4)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.check_summarize_filters = QtGui.QCheckBox(self.page)
        self.check_summarize_filters.setText(_fromUtf8(""))
        self.check_summarize_filters.setObjectName(_fromUtf8("check_summarize_filters"))
        self.gridLayout_7.addWidget(self.check_summarize_filters, 2, 0, 1, 1)
        self.check_summarize = QtGui.QCheckBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_summarize.sizePolicy().hasHeightForWidth())
        self.check_summarize.setSizePolicy(sizePolicy)
        self.check_summarize.setText(_fromUtf8(""))
        self.check_summarize.setObjectName(_fromUtf8("check_summarize"))
        self.gridLayout_7.addWidget(self.check_summarize, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 0, 3, 1, 1)
        self.widget_summarize = QtGui.QWidget(self.page)
        self.widget_summarize.setObjectName(_fromUtf8("widget_summarize"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.widget_summarize)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.button_add_summary_function = QtGui.QPushButton(self.widget_summarize)
        self.button_add_summary_function.setObjectName(_fromUtf8("button_add_summary_function"))
        self.verticalLayout_12.addWidget(self.button_add_summary_function)
        self.gridLayout_7.addWidget(self.widget_summarize, 1, 3, 1, 1)
        self.button_filters = QtGui.QPushButton(self.page)
        self.button_filters.setObjectName(_fromUtf8("button_filters"))
        self.gridLayout_7.addWidget(self.button_filters, 3, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 2, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem7, 4, 3, 1, 1)
        self.gridLayout_7.setColumnStretch(1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_7)
        self.tool_widget.addWidget(self.page)
        self.box_functions.addWidget(self.tool_widget)
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.data_preview = CoqTableView(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_preview.sizePolicy().hasHeightForWidth())
        self.data_preview.setSizePolicy(sizePolicy)
        self.data_preview.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.data_preview.setAlternatingRowColors(True)
        self.data_preview.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.data_preview.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.data_preview.setTextElideMode(QtCore.Qt.ElideRight)
        self.data_preview.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setSortingEnabled(True)
        self.data_preview.setObjectName(_fromUtf8("data_preview"))
        self.verticalLayout_15.addWidget(self.data_preview)
        self.text_no_match = QtGui.QTextEdit(self.layoutWidget)
        self.text_no_match.setEnabled(True)
        self.text_no_match.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.text_no_match.setObjectName(_fromUtf8("text_no_match"))
        self.verticalLayout_15.addWidget(self.text_no_match)
        self.verticalLayout_4.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        self.menuCorpus = QtGui.QMenu(self.menubar)
        self.menuCorpus.setObjectName(_fromUtf8("menuCorpus"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuAnalyse = QtGui.QMenu(self.menubar)
        self.menuAnalyse.setObjectName(_fromUtf8("menuAnalyse"))
        self.menuFrequencies = QtGui.QMenu(self.menuAnalyse)
        self.menuFrequencies.setObjectName(_fromUtf8("menuFrequencies"))
        self.menuFrequency_maps = QtGui.QMenu(self.menuAnalyse)
        self.menuFrequency_maps.setObjectName(_fromUtf8("menuFrequency_maps"))
        self.menuCorpus_locations = QtGui.QMenu(self.menuAnalyse)
        self.menuCorpus_locations.setObjectName(_fromUtf8("menuCorpus_locations"))
        self.menuDensity_plots = QtGui.QMenu(self.menuAnalyse)
        self.menuDensity_plots.setEnabled(False)
        self.menuDensity_plots.setObjectName(_fromUtf8("menuDensity_plots"))
        self.menuTime_data = QtGui.QMenu(self.menuAnalyse)
        self.menuTime_data.setObjectName(_fromUtf8("menuTime_data"))
        self.menu_Results = QtGui.QMenu(self.menubar)
        self.menu_Results.setObjectName(_fromUtf8("menu_Results"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_input_file = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.action_open_input_file.setIcon(icon)
        self.action_open_input_file.setObjectName(_fromUtf8("action_open_input_file"))
        self.action_help = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-contents"))
        self.action_help.setIcon(icon)
        self.action_help.setObjectName(_fromUtf8("action_help"))
        self.action_about_coquery = QtGui.QAction(MainWindow)
        self.action_about_coquery.setObjectName(_fromUtf8("action_about_coquery"))
        self.actionDummy = QtGui.QAction(MainWindow)
        self.actionDummy.setObjectName(_fromUtf8("actionDummy"))
        self.action_distinct_tokens = QtGui.QAction(MainWindow)
        self.action_distinct_tokens.setObjectName(_fromUtf8("action_distinct_tokens"))
        self.action_frequency = QtGui.QAction(MainWindow)
        self.action_frequency.setObjectName(_fromUtf8("action_frequency"))
        self.action_all_tokens = QtGui.QAction(MainWindow)
        self.action_all_tokens.setObjectName(_fromUtf8("action_all_tokens"))
        self.action_statistics = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-statistics"))
        self.action_statistics.setIcon(icon)
        self.action_statistics.setObjectName(_fromUtf8("action_statistics"))
        self.action_connection_settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("server-database"))
        self.action_connection_settings.setIcon(icon)
        self.action_connection_settings.setObjectName(_fromUtf8("action_connection_settings"))
        self.action_settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("configure"))
        self.action_settings.setIcon(icon)
        self.action_settings.setObjectName(_fromUtf8("action_settings"))
        self.action_quit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.action_quit.setIcon(icon)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_build_corpus = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-new"))
        self.action_build_corpus.setIcon(icon)
        self.action_build_corpus.setObjectName(_fromUtf8("action_build_corpus"))
        self.action_remove_corpus = QtGui.QAction(MainWindow)
        self.action_remove_corpus.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-delete"))
        self.action_remove_corpus.setIcon(icon)
        self.action_remove_corpus.setObjectName(_fromUtf8("action_remove_corpus"))
        self.action_manage_corpus = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("server-database"))
        self.action_manage_corpus.setIcon(icon)
        self.action_manage_corpus.setObjectName(_fromUtf8("action_manage_corpus"))
        self.action_tree_map = QtGui.QAction(MainWindow)
        self.action_tree_map.setEnabled(False)
        self.action_tree_map.setObjectName(_fromUtf8("action_tree_map"))
        self.action_heat_map = QtGui.QAction(MainWindow)
        self.action_heat_map.setEnabled(True)
        self.action_heat_map.setObjectName(_fromUtf8("action_heat_map"))
        self.action_word_cloud = QtGui.QAction(MainWindow)
        self.action_word_cloud.setEnabled(False)
        self.action_word_cloud.setObjectName(_fromUtf8("action_word_cloud"))
        self.action_barcode_plot = QtGui.QAction(MainWindow)
        self.action_barcode_plot.setObjectName(_fromUtf8("action_barcode_plot"))
        self.action_beeswarm_plot = QtGui.QAction(MainWindow)
        self.action_beeswarm_plot.setObjectName(_fromUtf8("action_beeswarm_plot"))
        self.action_barchart_plot = QtGui.QAction(MainWindow)
        self.action_barchart_plot.setObjectName(_fromUtf8("action_barchart_plot"))
        self.action_time_series_plot = QtGui.QAction(MainWindow)
        self.action_time_series_plot.setObjectName(_fromUtf8("action_time_series_plot"))
        self.action_corpus_documentation = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-browser"))
        self.action_corpus_documentation.setIcon(icon)
        self.action_corpus_documentation.setObjectName(_fromUtf8("action_corpus_documentation"))
        self.action_percentage_area_plot = QtGui.QAction(MainWindow)
        self.action_percentage_area_plot.setObjectName(_fromUtf8("action_percentage_area_plot"))
        self.action_stacked_area_plot = QtGui.QAction(MainWindow)
        self.action_stacked_area_plot.setObjectName(_fromUtf8("action_stacked_area_plot"))
        self.action_line_plot = QtGui.QAction(MainWindow)
        self.action_line_plot.setObjectName(_fromUtf8("action_line_plot"))
        self.actionStop_words = QtGui.QAction(MainWindow)
        self.actionStop_words.setObjectName(_fromUtf8("actionStop_words"))
        self.actionStop_words_2 = QtGui.QAction(MainWindow)
        self.actionStop_words_2.setObjectName(_fromUtf8("actionStop_words_2"))
        self.action_percentage_bars = QtGui.QAction(MainWindow)
        self.action_percentage_bars.setObjectName(_fromUtf8("action_percentage_bars"))
        self.action_stacked_bars = QtGui.QAction(MainWindow)
        self.action_stacked_bars.setObjectName(_fromUtf8("action_stacked_bars"))
        self.action_view_log = QtGui.QAction(MainWindow)
        self.action_view_log.setObjectName(_fromUtf8("action_view_log"))
        self.action_mysql_server_help = QtGui.QAction(MainWindow)
        self.action_mysql_server_help.setObjectName(_fromUtf8("action_mysql_server_help"))
        self.action_Column_context_menu = QtGui.QAction(MainWindow)
        self.action_Column_context_menu.setObjectName(_fromUtf8("action_Column_context_menu"))
        self.action_Row_context_menu = QtGui.QAction(MainWindow)
        self.action_Row_context_menu.setObjectName(_fromUtf8("action_Row_context_menu"))
        self.actionCopy_to_clipboard = QtGui.QAction(MainWindow)
        self.actionCopy_to_clipboard.setObjectName(_fromUtf8("actionCopy_to_clipboard"))
        self.actionSave_results = QtGui.QAction(MainWindow)
        self.actionSave_results.setObjectName(_fromUtf8("actionSave_results"))
        self.action_Selection_menu = QtGui.QAction(MainWindow)
        self.action_Selection_menu.setObjectName(_fromUtf8("action_Selection_menu"))
        self.action_bubble_chart = QtGui.QAction(MainWindow)
        self.action_bubble_chart.setObjectName(_fromUtf8("action_bubble_chart"))
        self.action_save_results = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.action_save_results.setIcon(icon)
        self.action_save_results.setObjectName(_fromUtf8("action_save_results"))
        self.action_copy_to_clipboard = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-copy"))
        self.action_copy_to_clipboard.setIcon(icon)
        self.action_copy_to_clipboard.setObjectName(_fromUtf8("action_copy_to_clipboard"))
        self.action_kde_plot = QtGui.QAction(MainWindow)
        self.action_kde_plot.setObjectName(_fromUtf8("action_kde_plot"))
        self.action_ecd_plot = QtGui.QAction(MainWindow)
        self.action_ecd_plot.setObjectName(_fromUtf8("action_ecd_plot"))
        self.action_save_selection = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.action_save_selection.setIcon(icon)
        self.action_save_selection.setObjectName(_fromUtf8("action_save_selection"))
        self.action_toggle_filters = QtGui.QAction(MainWindow)
        self.action_toggle_filters.setCheckable(True)
        self.action_toggle_filters.setObjectName(_fromUtf8("action_toggle_filters"))
        self.action_toggle_stopwords = QtGui.QAction(MainWindow)
        self.action_toggle_stopwords.setCheckable(True)
        self.action_toggle_stopwords.setObjectName(_fromUtf8("action_toggle_stopwords"))
        self.action_create_textgrid = QtGui.QAction(MainWindow)
        self.action_create_textgrid.setObjectName(_fromUtf8("action_create_textgrid"))
        self.action_available_modules = QtGui.QAction(MainWindow)
        self.action_available_modules.setObjectName(_fromUtf8("action_available_modules"))
        self.menuFile.addAction(self.action_save_results)
        self.menuFile.addAction(self.action_save_selection)
        self.menuFile.addAction(self.action_create_textgrid)
        self.menuFile.addAction(self.action_copy_to_clipboard)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_view_log)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_quit)
        self.menuHilfe.addAction(self.action_help)
        self.menuHilfe.addSeparator()
        self.menuHilfe.addAction(self.action_available_modules)
        self.menuHilfe.addAction(self.action_about_coquery)
        self.menuCorpus.addAction(self.action_manage_corpus)
        self.menuCorpus.addSeparator()
        self.menuCorpus.addAction(self.action_statistics)
        self.menuCorpus.addAction(self.action_corpus_documentation)
        self.menuSettings.addAction(self.action_connection_settings)
        self.menuSettings.addAction(self.action_settings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.action_toggle_filters)
        self.menuSettings.addAction(self.action_toggle_stopwords)
        self.menuFrequencies.addAction(self.action_percentage_bars)
        self.menuFrequencies.addAction(self.action_stacked_bars)
        self.menuFrequencies.addAction(self.action_barchart_plot)
        self.menuFrequency_maps.addAction(self.action_heat_map)
        self.menuFrequency_maps.addAction(self.action_tree_map)
        self.menuFrequency_maps.addAction(self.action_word_cloud)
        self.menuFrequency_maps.addAction(self.action_bubble_chart)
        self.menuCorpus_locations.addAction(self.action_barcode_plot)
        self.menuCorpus_locations.addAction(self.action_beeswarm_plot)
        self.menuDensity_plots.addAction(self.action_kde_plot)
        self.menuDensity_plots.addAction(self.action_ecd_plot)
        self.menuTime_data.addAction(self.action_percentage_area_plot)
        self.menuTime_data.addAction(self.action_stacked_area_plot)
        self.menuTime_data.addAction(self.action_line_plot)
        self.menuAnalyse.addAction(self.menuCorpus_locations.menuAction())
        self.menuAnalyse.addAction(self.menuFrequencies.menuAction())
        self.menuAnalyse.addAction(self.menuTime_data.menuAction())
        self.menuAnalyse.addAction(self.menuFrequency_maps.menuAction())
        self.menuAnalyse.addAction(self.menuDensity_plots.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCorpus.menuAction())
        self.menubar.addAction(self.menu_Results.menuAction())
        self.menubar.addAction(self.menuAnalyse.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())
        self.label_2.setBuddy(self.combo_corpus)
        self.label_5.setBuddy(self.check_aggregate)
        self.label_6.setBuddy(self.check_aggregate)

        self.retranslateUi(MainWindow)
        self.tool_widget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Coquery", None))
        self.box_corpus_select.setTitle(_translate("MainWindow", "&Resource selection", None))
        self.label_2.setText(_translate("MainWindow", "&Corpus:", None))
        self.box_input_settings.setTitle(_translate("MainWindow", "Query &strings", None))
        self.edit_file_name.setPlaceholderText(_translate("MainWindow", "(no query input file selected)", None))
        self.button_change_file.setText(_translate("MainWindow", "&Browse", None))
        self.button_change_file.setShortcut(_translate("MainWindow", "Alt+B", None))
        self.button_run_query.setText(_translate("MainWindow", "&Query", None))
        self.groupBox.setTitle(_translate("MainWindow", "Output &management", None))
        __sortingEnabled = self.list_toolbox.isSortingEnabled()
        self.list_toolbox.setSortingEnabled(False)
        item = self.list_toolbox.item(0, 0)
        item.setText(_translate("MainWindow", "Context", None))
        item = self.list_toolbox.item(1, 0)
        item.setText(_translate("MainWindow", "Stopwords", None))
        item = self.list_toolbox.item(2, 0)
        item.setText(_translate("MainWindow", "Grouping", None))
        item = self.list_toolbox.item(3, 0)
        item.setText(_translate("MainWindow", "Aggregate", None))
        item = self.list_toolbox.item(4, 0)
        item.setText(_translate("MainWindow", "Summarize", None))
        self.list_toolbox.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Add context:", None))
        self.radio_context_mode_kwic.setText(_translate("MainWindow", "&KWIC", None))
        self.radio_context_mode_string.setText(_translate("MainWindow", "Sing&le string", None))
        self.radio_context_mode_columns.setText(_translate("MainWindow", "Colu&mns", None))
        self.context_left_span.setPrefix(_translate("MainWindow", "Left: ", None))
        self.context_right_span.setPrefix(_translate("MainWindow", "Right: ", None))
        self.label_3.setText(_translate("MainWindow", "Apply stop words:", None))
        self.button_stopwords.setText(_translate("MainWindow", "Manage stop &words...", None))
        self.button_add_group_function.setText(_translate("MainWindow", "Group functions...", None))
        self.button_filters_2.setText(_translate("MainWindow", "Group fil&ters...", None))
        self.label_4.setText(_translate("MainWindow", "Use grouping columns:", None))
        self.button_remove_group.setText(_translate("MainWindow", "Remove", None))
        self.label_5.setText(_translate("MainWindow", "Aggregate results", None))
        self.label_6.setText(_translate("MainWindow", "Summarize output", None))
        self.button_add_summary_function.setText(_translate("MainWindow", "Summary functions...", None))
        self.button_filters.setText(_translate("MainWindow", "Summary filters...", None))
        self.label_7.setText(_translate("MainWindow", "Filter results", None))
        self.text_no_match.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">No match.</span></p></body></html>", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuHilfe.setTitle(_translate("MainWindow", "&Help", None))
        self.menuCorpus.setTitle(_translate("MainWindow", "&Corpus", None))
        self.menuSettings.setTitle(_translate("MainWindow", "&Preferences", None))
        self.menuAnalyse.setTitle(_translate("MainWindow", "&Visualizations", None))
        self.menuFrequencies.setTitle(_translate("MainWindow", "&Bar charts", None))
        self.menuFrequency_maps.setTitle(_translate("MainWindow", "Frequency maps", None))
        self.menuCorpus_locations.setTitle(_translate("MainWindow", "&Corpus locations", None))
        self.menuDensity_plots.setTitle(_translate("MainWindow", "Density plots", None))
        self.menuTime_data.setTitle(_translate("MainWindow", "&Time data", None))
        self.menu_Results.setTitle(_translate("MainWindow", "&Output", None))
        self.action_open_input_file.setText(_translate("MainWindow", "&Open input file...", None))
        self.action_open_input_file.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_help.setText(_translate("MainWindow", "&Help", None))
        self.action_help.setShortcut(_translate("MainWindow", "F1", None))
        self.action_about_coquery.setText(_translate("MainWindow", "&About Coquery", None))
        self.actionDummy.setText(_translate("MainWindow", "Dummy", None))
        self.action_distinct_tokens.setText(_translate("MainWindow", "Distinct tokens", None))
        self.action_frequency.setText(_translate("MainWindow", "Frequency", None))
        self.action_all_tokens.setText(_translate("MainWindow", "All tokens", None))
        self.action_statistics.setText(_translate("MainWindow", "&Statistics", None))
        self.action_connection_settings.setText(_translate("MainWindow", "&Database connections...", None))
        self.action_settings.setText(_translate("MainWindow", "&Settings...", None))
        self.action_quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_build_corpus.setText(_translate("MainWindow", "&Build new corpus...", None))
        self.action_build_corpus.setToolTip(_translate("MainWindow", "Build a new corpus from text files in a folder", None))
        self.action_remove_corpus.setText(_translate("MainWindow", "&Remove corpus...", None))
        self.action_remove_corpus.setToolTip(_translate("MainWindow", "Permanently and irrevocably remove corpus database", None))
        self.action_manage_corpus.setText(_translate("MainWindow", "Corpus &manager...", None))
        self.action_manage_corpus.setToolTip(_translate("MainWindow", "Install a corpus into a MySQL database", None))
        self.action_manage_corpus.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.action_tree_map.setText(_translate("MainWindow", "&Tree map", None))
        self.action_heat_map.setText(_translate("MainWindow", "&Heat map", None))
        self.action_word_cloud.setText(_translate("MainWindow", "Word cloud", None))
        self.action_barcode_plot.setText(_translate("MainWindow", "&Barcode plot", None))
        self.action_beeswarm_plot.setText(_translate("MainWindow", "Bee&swarm plot", None))
        self.action_barchart_plot.setText(_translate("MainWindow", "&Bars", None))
        self.action_time_series_plot.setText(_translate("MainWindow", "T&ime series", None))
        self.action_corpus_documentation.setText(_translate("MainWindow", "&Documentation...", None))
        self.action_percentage_area_plot.setText(_translate("MainWindow", "&Percentage areas", None))
        self.action_stacked_area_plot.setText(_translate("MainWindow", "&Stacked areas", None))
        self.action_line_plot.setText(_translate("MainWindow", "&Lines", None))
        self.actionStop_words.setText(_translate("MainWindow", "Stop words...", None))
        self.actionStop_words_2.setText(_translate("MainWindow", "&Stop words...", None))
        self.action_percentage_bars.setText(_translate("MainWindow", "&Percentage bars", None))
        self.action_stacked_bars.setText(_translate("MainWindow", "&Stacked bars", None))
        self.action_view_log.setText(_translate("MainWindow", "View &log file...", None))
        self.action_mysql_server_help.setText(_translate("MainWindow", "MySQL server help", None))
        self.action_Column_context_menu.setText(_translate("MainWindow", "[Column context menu]", None))
        self.action_Row_context_menu.setText(_translate("MainWindow", "[Row context menu]", None))
        self.actionCopy_to_clipboard.setText(_translate("MainWindow", "Copy to clipboard", None))
        self.actionSave_results.setText(_translate("MainWindow", "Save", None))
        self.action_Selection_menu.setText(_translate("MainWindow", "[Selection menu]", None))
        self.action_bubble_chart.setText(_translate("MainWindow", "&Bubble chart", None))
        self.action_save_results.setText(_translate("MainWindow", "&Save results...", None))
        self.action_save_results.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_copy_to_clipboard.setText(_translate("MainWindow", "&Copy selection to clipboard", None))
        self.action_copy_to_clipboard.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.action_kde_plot.setText(_translate("MainWindow", "Kernel Density Estimate", None))
        self.action_ecd_plot.setText(_translate("MainWindow", "Estimated cumulative distribution", None))
        self.action_save_selection.setText(_translate("MainWindow", "Sa&ve selection...", None))
        self.action_save_selection.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.action_toggle_filters.setText(_translate("MainWindow", "Use &filters", None))
        self.action_toggle_stopwords.setText(_translate("MainWindow", "Use stop&words", None))
        self.action_create_textgrid.setText(_translate("MainWindow", "Create te&xtgrid...", None))
        self.action_available_modules.setText(_translate("MainWindow", "Available &modules...", None))

from ..classes import CoqListWidget, CoqTableView, CoqTextEdit

