# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coquery.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from coquery.gui.pyqt_compat import QtCore, QtGui, frameShadow, frameShape

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(783, 1137)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.options_area = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.options_area.sizePolicy().hasHeightForWidth())
        self.options_area.setSizePolicy(sizePolicy)
        self.options_area.setObjectName(_fromUtf8("options_area"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.options_area)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.box_corpus_select = QtGui.QGroupBox(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_corpus_select.sizePolicy().hasHeightForWidth())
        self.box_corpus_select.setSizePolicy(sizePolicy)
        self.box_corpus_select.setObjectName(_fromUtf8("box_corpus_select"))
        self.output_columns = QtGui.QVBoxLayout(self.box_corpus_select)
        self.output_columns.setContentsMargins(8, 4, 8, 4)
        self.output_columns.setSpacing(0)
        self.output_columns.setObjectName(_fromUtf8("output_columns"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.combo_corpus = QtGui.QComboBox(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_corpus.sizePolicy().hasHeightForWidth())
        self.combo_corpus.setSizePolicy(sizePolicy)
        self.combo_corpus.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.combo_corpus.setEditable(False)
        self.combo_corpus.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.combo_corpus.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.combo_corpus.setFrame(True)
        self.combo_corpus.setObjectName(_fromUtf8("combo_corpus"))
        self.horizontalLayout_2.addWidget(self.combo_corpus)
        self.output_columns.addLayout(self.horizontalLayout_2)
        self.label_data_columns = QtGui.QLabel(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_columns.sizePolicy().hasHeightForWidth())
        self.label_data_columns.setSizePolicy(sizePolicy)
        self.label_data_columns.setObjectName(_fromUtf8("label_data_columns"))
        self.output_columns.addWidget(self.label_data_columns)
        self.verticalLayout.addWidget(self.box_corpus_select)
        self.frame_buttons = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons.sizePolicy().hasHeightForWidth())
        self.frame_buttons.setSizePolicy(sizePolicy)
        self.frame_buttons.setObjectName(_fromUtf8("frame_buttons"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_buttons)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.button_run_query = QtGui.QPushButton(self.frame_buttons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_run_query.sizePolicy().hasHeightForWidth())
        self.button_run_query.setSizePolicy(sizePolicy)
        self.button_run_query.setObjectName(_fromUtf8("button_run_query"))
        self.horizontalLayout_7.addWidget(self.button_run_query)
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_buttons)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.box_input_settings = QtGui.QGroupBox(self.options_area)
        self.box_input_settings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.box_input_settings.setObjectName(_fromUtf8("box_input_settings"))
        self.layout_query = QtGui.QGridLayout(self.box_input_settings)
        self.layout_query.setContentsMargins(-1, -1, -1, 4)
        self.layout_query.setObjectName(_fromUtf8("layout_query"))
        self.radio_query_file = QtGui.QRadioButton(self.box_input_settings)
        self.radio_query_file.setText(_fromUtf8(""))
        self.radio_query_file.setObjectName(_fromUtf8("radio_query_file"))
        self.layout_query.addWidget(self.radio_query_file, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.edit_file_name = QtGui.QLineEdit(self.box_input_settings)
        self.edit_file_name.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_file_name.sizePolicy().hasHeightForWidth())
        self.edit_file_name.setSizePolicy(sizePolicy)
        self.edit_file_name.setAccessibleDescription(_fromUtf8(""))
        self.edit_file_name.setObjectName(_fromUtf8("edit_file_name"))
        self.gridLayout_3.addWidget(self.edit_file_name, 0, 0, 1, 1)
        self.button_browse_file = QtGui.QPushButton(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_file.sizePolicy().hasHeightForWidth())
        self.button_browse_file.setSizePolicy(sizePolicy)
        self.button_browse_file.setObjectName(_fromUtf8("button_browse_file"))
        self.gridLayout_3.addWidget(self.button_browse_file, 0, 1, 1, 1)
        self.button_file_options = QtGui.QPushButton(self.box_input_settings)
        self.button_file_options.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_file_options.sizePolicy().hasHeightForWidth())
        self.button_file_options.setSizePolicy(sizePolicy)
        self.button_file_options.setObjectName(_fromUtf8("button_file_options"))
        self.gridLayout_3.addWidget(self.button_file_options, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.layout_query.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.edit_query_string = CoqTextEdit(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_query_string.sizePolicy().hasHeightForWidth())
        self.edit_query_string.setSizePolicy(sizePolicy)
        self.edit_query_string.setObjectName(_fromUtf8("edit_query_string"))
        self.layout_query.addWidget(self.edit_query_string, 0, 1, 1, 1)
        self.radio_query_string = QtGui.QRadioButton(self.box_input_settings)
        self.radio_query_string.setText(_fromUtf8(""))
        self.radio_query_string.setChecked(True)
        self.radio_query_string.setObjectName(_fromUtf8("radio_query_string"))
        self.layout_query.addWidget(self.radio_query_string, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.layout_query.setRowStretch(0, 1)
        self.horizontalLayout.addWidget(self.box_input_settings)
        self.groupBox = QtGui.QGroupBox(self.options_area)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.box_functions = QtGui.QVBoxLayout(self.groupBox)
        self.box_functions.setContentsMargins(4, -1, 4, 0)
        self.box_functions.setSpacing(4)
        self.box_functions.setObjectName(_fromUtf8("box_functions"))
        self.tool_widget = QtGui.QTabWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_widget.sizePolicy().hasHeightForWidth())
        self.tool_widget.setSizePolicy(sizePolicy)
        self.tool_widget.setTabPosition(QtGui.QTabWidget.West)
        self.tool_widget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tool_widget.setObjectName(_fromUtf8("tool_widget"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabWidgetPage1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.radio_context_none = QtGui.QRadioButton(self.tabWidgetPage1)
        self.radio_context_none.setStyleSheet(_fromUtf8("text-align: center center"))
        self.radio_context_none.setObjectName(_fromUtf8("radio_context_none"))
        self.verticalLayout_10.addWidget(self.radio_context_none)
        self.radio_context_mode_kwic = QtGui.QRadioButton(self.tabWidgetPage1)
        self.radio_context_mode_kwic.setStyleSheet(_fromUtf8("text-align: center center"))
        self.radio_context_mode_kwic.setObjectName(_fromUtf8("radio_context_mode_kwic"))
        self.verticalLayout_10.addWidget(self.radio_context_mode_kwic)
        self.radio_context_mode_string = QtGui.QRadioButton(self.tabWidgetPage1)
        self.radio_context_mode_string.setStyleSheet(_fromUtf8("text-align: center center"))
        self.radio_context_mode_string.setObjectName(_fromUtf8("radio_context_mode_string"))
        self.verticalLayout_10.addWidget(self.radio_context_mode_string)
        self.radio_context_mode_columns = QtGui.QRadioButton(self.tabWidgetPage1)
        self.radio_context_mode_columns.setStyleSheet(_fromUtf8("text-align: center center"))
        self.radio_context_mode_columns.setObjectName(_fromUtf8("radio_context_mode_columns"))
        self.verticalLayout_10.addWidget(self.radio_context_mode_columns)
        self.verticalLayout_2.addLayout(self.verticalLayout_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.context_left_span = QtGui.QSpinBox(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span.sizePolicy().hasHeightForWidth())
        self.context_left_span.setSizePolicy(sizePolicy)
        self.context_left_span.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.context_left_span.setSuffix(_fromUtf8(""))
        self.context_left_span.setObjectName(_fromUtf8("context_left_span"))
        self.horizontalLayout_4.addWidget(self.context_left_span)
        self.context_right_span = QtGui.QSpinBox(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_right_span.sizePolicy().hasHeightForWidth())
        self.context_right_span.setSizePolicy(sizePolicy)
        self.context_right_span.setFrame(True)
        self.context_right_span.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.context_right_span.setSuffix(_fromUtf8(""))
        self.context_right_span.setObjectName(_fromUtf8("context_right_span"))
        self.horizontalLayout_4.addWidget(self.context_right_span)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tool_widget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabWidgetPage2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox = QtGui.QCheckBox(self.tabWidgetPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_3.addWidget(self.checkBox)
        self.list_stopwords = QtGui.QListWidget(self.tabWidgetPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_stopwords.sizePolicy().hasHeightForWidth())
        self.list_stopwords.setSizePolicy(sizePolicy)
        self.list_stopwords.setMaximumSize(QtCore.QSize(50, 16777215))
        self.list_stopwords.setAlternatingRowColors(True)
        self.list_stopwords.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.list_stopwords.setFlow(QtGui.QListView.TopToBottom)
        self.list_stopwords.setProperty("isWrapping", True)
        self.list_stopwords.setResizeMode(QtGui.QListView.Adjust)
        self.list_stopwords.setViewMode(QtGui.QListView.IconMode)
        self.list_stopwords.setWordWrap(True)
        self.list_stopwords.setSelectionRectVisible(True)
        self.list_stopwords.setObjectName(_fromUtf8("list_stopwords"))
        self.verticalLayout_3.addWidget(self.list_stopwords)
        self.layout_stopword_buttons = QtGui.QHBoxLayout()
        self.layout_stopword_buttons.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.layout_stopword_buttons.setObjectName(_fromUtf8("layout_stopword_buttons"))
        self.pushButton = QtGui.QPushButton(self.tabWidgetPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.layout_stopword_buttons.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.tabWidgetPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.layout_stopword_buttons.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.layout_stopword_buttons)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.tool_widget.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.Grouping = QtGui.QWidget()
        self.Grouping.setObjectName(_fromUtf8("Grouping"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.Grouping)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.list_group_columns = CoqListWidget(self.Grouping)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_group_columns.sizePolicy().hasHeightForWidth())
        self.list_group_columns.setSizePolicy(sizePolicy)
        self.list_group_columns.setMaximumSize(QtCore.QSize(50, 16777215))
        self.list_group_columns.setObjectName(_fromUtf8("list_group_columns"))
        self.verticalLayout_5.addWidget(self.list_group_columns)
        self.layout_group_columns = QtGui.QHBoxLayout()
        self.layout_group_columns.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.layout_group_columns.setObjectName(_fromUtf8("layout_group_columns"))
        self.button_remove_group = QtGui.QPushButton(self.Grouping)
        self.button_remove_group.setObjectName(_fromUtf8("button_remove_group"))
        self.layout_group_columns.addWidget(self.button_remove_group)
        self.button_group_up = QtGui.QToolButton(self.Grouping)
        self.button_group_up.setText(_fromUtf8(""))
        self.button_group_up.setObjectName(_fromUtf8("button_group_up"))
        self.layout_group_columns.addWidget(self.button_group_up)
        self.button_group_down = QtGui.QToolButton(self.Grouping)
        self.button_group_down.setText(_fromUtf8(""))
        self.button_group_down.setObjectName(_fromUtf8("button_group_down"))
        self.layout_group_columns.addWidget(self.button_group_down)
        self.verticalLayout_5.addLayout(self.layout_group_columns)
        self.button_filters_2 = QtGui.QPushButton(self.Grouping)
        self.button_filters_2.setObjectName(_fromUtf8("button_filters_2"))
        self.verticalLayout_5.addWidget(self.button_filters_2)
        self.button_add_group_function = QtGui.QPushButton(self.Grouping)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_group_function.sizePolicy().hasHeightForWidth())
        self.button_add_group_function.setSizePolicy(sizePolicy)
        self.button_add_group_function.setObjectName(_fromUtf8("button_add_group_function"))
        self.verticalLayout_5.addWidget(self.button_add_group_function)
        spacerItem4 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.tool_widget.addTab(self.Grouping, _fromUtf8(""))
        self.Summary = QtGui.QWidget()
        self.Summary.setObjectName(_fromUtf8("Summary"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.Summary)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.layout_summary = QtGui.QGridLayout()
        self.layout_summary.setObjectName(_fromUtf8("layout_summary"))
        self.label_5 = QtGui.QLabel(self.Summary)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.layout_summary.addWidget(self.label_5, 0, 1, 1, 1)
        self.radio_no_summary = QtGui.QRadioButton(self.Summary)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_no_summary.sizePolicy().hasHeightForWidth())
        self.radio_no_summary.setSizePolicy(sizePolicy)
        self.radio_no_summary.setText(_fromUtf8(""))
        self.radio_no_summary.setChecked(True)
        self.radio_no_summary.setObjectName(_fromUtf8("radio_no_summary"))
        self.layout_summary.addWidget(self.radio_no_summary, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_7 = QtGui.QLabel(self.Summary)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_14.addWidget(self.label_7)
        self.combo_summary = QtGui.QComboBox(self.Summary)
        self.combo_summary.setObjectName(_fromUtf8("combo_summary"))
        self.verticalLayout_14.addWidget(self.combo_summary)
        self.layout_summary.addLayout(self.verticalLayout_14, 1, 1, 1, 1)
        self.radio_summary = QtGui.QRadioButton(self.Summary)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_summary.sizePolicy().hasHeightForWidth())
        self.radio_summary.setSizePolicy(sizePolicy)
        self.radio_summary.setText(_fromUtf8(""))
        self.radio_summary.setChecked(False)
        self.radio_summary.setObjectName(_fromUtf8("radio_summary"))
        self.layout_summary.addWidget(self.radio_summary, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_6.addLayout(self.layout_summary)
        self.button_filters = QtGui.QPushButton(self.Summary)
        self.button_filters.setObjectName(_fromUtf8("button_filters"))
        self.verticalLayout_6.addWidget(self.button_filters)
        self.button_add_summary_function = QtGui.QPushButton(self.Summary)
        self.button_add_summary_function.setObjectName(_fromUtf8("button_add_summary_function"))
        self.verticalLayout_6.addWidget(self.button_add_summary_function)
        spacerItem5 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.tool_widget.addTab(self.Summary, _fromUtf8(""))
        self.box_functions.addWidget(self.tool_widget)
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout.setStretch(1, 1)
        self.data_preview = CoqTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_preview.sizePolicy().hasHeightForWidth())
        self.data_preview.setSizePolicy(sizePolicy)
        self.data_preview.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.data_preview.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.data_preview.setAlternatingRowColors(True)
        self.data_preview.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.data_preview.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.data_preview.setTextElideMode(QtCore.Qt.ElideRight)
        self.data_preview.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setSortingEnabled(True)
        self.data_preview.setObjectName(_fromUtf8("data_preview"))
        self.verticalLayout_4.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        self.menuCorpus = QtGui.QMenu(self.menubar)
        self.menuCorpus.setObjectName(_fromUtf8("menuCorpus"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuAnalyse = QtGui.QMenu(self.menubar)
        self.menuAnalyse.setObjectName(_fromUtf8("menuAnalyse"))
        self.menuFrequencies = QtGui.QMenu(self.menuAnalyse)
        self.menuFrequencies.setObjectName(_fromUtf8("menuFrequencies"))
        self.menuFrequency_maps = QtGui.QMenu(self.menuAnalyse)
        self.menuFrequency_maps.setObjectName(_fromUtf8("menuFrequency_maps"))
        self.menuCorpus_locations = QtGui.QMenu(self.menuAnalyse)
        self.menuCorpus_locations.setObjectName(_fromUtf8("menuCorpus_locations"))
        self.menuDensity_plots = QtGui.QMenu(self.menuAnalyse)
        self.menuDensity_plots.setEnabled(False)
        self.menuDensity_plots.setObjectName(_fromUtf8("menuDensity_plots"))
        self.menuTime_data = QtGui.QMenu(self.menuAnalyse)
        self.menuTime_data.setObjectName(_fromUtf8("menuTime_data"))
        self.menu_Results = QtGui.QMenu(self.menubar)
        self.menu_Results.setObjectName(_fromUtf8("menu_Results"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_input_file = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.action_open_input_file.setIcon(icon)
        self.action_open_input_file.setObjectName(_fromUtf8("action_open_input_file"))
        self.action_help = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-contents"))
        self.action_help.setIcon(icon)
        self.action_help.setObjectName(_fromUtf8("action_help"))
        self.action_about_coquery = QtGui.QAction(MainWindow)
        self.action_about_coquery.setObjectName(_fromUtf8("action_about_coquery"))
        self.actionDummy = QtGui.QAction(MainWindow)
        self.actionDummy.setObjectName(_fromUtf8("actionDummy"))
        self.action_distinct_tokens = QtGui.QAction(MainWindow)
        self.action_distinct_tokens.setObjectName(_fromUtf8("action_distinct_tokens"))
        self.action_frequency = QtGui.QAction(MainWindow)
        self.action_frequency.setObjectName(_fromUtf8("action_frequency"))
        self.action_all_tokens = QtGui.QAction(MainWindow)
        self.action_all_tokens.setObjectName(_fromUtf8("action_all_tokens"))
        self.action_statistics = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-statistics"))
        self.action_statistics.setIcon(icon)
        self.action_statistics.setObjectName(_fromUtf8("action_statistics"))
        self.action_connection_settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("server-database"))
        self.action_connection_settings.setIcon(icon)
        self.action_connection_settings.setObjectName(_fromUtf8("action_connection_settings"))
        self.action_settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("configure"))
        self.action_settings.setIcon(icon)
        self.action_settings.setObjectName(_fromUtf8("action_settings"))
        self.action_quit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.action_quit.setIcon(icon)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_build_corpus = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-new"))
        self.action_build_corpus.setIcon(icon)
        self.action_build_corpus.setObjectName(_fromUtf8("action_build_corpus"))
        self.action_remove_corpus = QtGui.QAction(MainWindow)
        self.action_remove_corpus.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-delete"))
        self.action_remove_corpus.setIcon(icon)
        self.action_remove_corpus.setObjectName(_fromUtf8("action_remove_corpus"))
        self.action_manage_corpus = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("server-database"))
        self.action_manage_corpus.setIcon(icon)
        self.action_manage_corpus.setObjectName(_fromUtf8("action_manage_corpus"))
        self.action_tree_map = QtGui.QAction(MainWindow)
        self.action_tree_map.setEnabled(False)
        self.action_tree_map.setObjectName(_fromUtf8("action_tree_map"))
        self.action_heat_map = QtGui.QAction(MainWindow)
        self.action_heat_map.setEnabled(True)
        self.action_heat_map.setObjectName(_fromUtf8("action_heat_map"))
        self.action_word_cloud = QtGui.QAction(MainWindow)
        self.action_word_cloud.setEnabled(False)
        self.action_word_cloud.setObjectName(_fromUtf8("action_word_cloud"))
        self.action_barcode_plot = QtGui.QAction(MainWindow)
        self.action_barcode_plot.setObjectName(_fromUtf8("action_barcode_plot"))
        self.action_beeswarm_plot = QtGui.QAction(MainWindow)
        self.action_beeswarm_plot.setObjectName(_fromUtf8("action_beeswarm_plot"))
        self.action_barchart_plot = QtGui.QAction(MainWindow)
        self.action_barchart_plot.setObjectName(_fromUtf8("action_barchart_plot"))
        self.action_time_series_plot = QtGui.QAction(MainWindow)
        self.action_time_series_plot.setObjectName(_fromUtf8("action_time_series_plot"))
        self.action_corpus_documentation = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-browser"))
        self.action_corpus_documentation.setIcon(icon)
        self.action_corpus_documentation.setObjectName(_fromUtf8("action_corpus_documentation"))
        self.action_percentage_area_plot = QtGui.QAction(MainWindow)
        self.action_percentage_area_plot.setObjectName(_fromUtf8("action_percentage_area_plot"))
        self.action_stacked_area_plot = QtGui.QAction(MainWindow)
        self.action_stacked_area_plot.setObjectName(_fromUtf8("action_stacked_area_plot"))
        self.action_line_plot = QtGui.QAction(MainWindow)
        self.action_line_plot.setObjectName(_fromUtf8("action_line_plot"))
        self.actionStop_words = QtGui.QAction(MainWindow)
        self.actionStop_words.setObjectName(_fromUtf8("actionStop_words"))
        self.actionStop_words_2 = QtGui.QAction(MainWindow)
        self.actionStop_words_2.setObjectName(_fromUtf8("actionStop_words_2"))
        self.action_percentage_bars = QtGui.QAction(MainWindow)
        self.action_percentage_bars.setObjectName(_fromUtf8("action_percentage_bars"))
        self.action_stacked_bars = QtGui.QAction(MainWindow)
        self.action_stacked_bars.setObjectName(_fromUtf8("action_stacked_bars"))
        self.action_view_log = QtGui.QAction(MainWindow)
        self.action_view_log.setObjectName(_fromUtf8("action_view_log"))
        self.action_mysql_server_help = QtGui.QAction(MainWindow)
        self.action_mysql_server_help.setObjectName(_fromUtf8("action_mysql_server_help"))
        self.action_Column_context_menu = QtGui.QAction(MainWindow)
        self.action_Column_context_menu.setObjectName(_fromUtf8("action_Column_context_menu"))
        self.action_Row_context_menu = QtGui.QAction(MainWindow)
        self.action_Row_context_menu.setObjectName(_fromUtf8("action_Row_context_menu"))
        self.actionCopy_to_clipboard = QtGui.QAction(MainWindow)
        self.actionCopy_to_clipboard.setObjectName(_fromUtf8("actionCopy_to_clipboard"))
        self.actionSave_results = QtGui.QAction(MainWindow)
        self.actionSave_results.setObjectName(_fromUtf8("actionSave_results"))
        self.action_Selection_menu = QtGui.QAction(MainWindow)
        self.action_Selection_menu.setObjectName(_fromUtf8("action_Selection_menu"))
        self.action_bubble_chart = QtGui.QAction(MainWindow)
        self.action_bubble_chart.setObjectName(_fromUtf8("action_bubble_chart"))
        self.action_save_results = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.action_save_results.setIcon(icon)
        self.action_save_results.setObjectName(_fromUtf8("action_save_results"))
        self.action_copy_to_clipboard = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-copy"))
        self.action_copy_to_clipboard.setIcon(icon)
        self.action_copy_to_clipboard.setObjectName(_fromUtf8("action_copy_to_clipboard"))
        self.action_kde_plot = QtGui.QAction(MainWindow)
        self.action_kde_plot.setObjectName(_fromUtf8("action_kde_plot"))
        self.action_ecd_plot = QtGui.QAction(MainWindow)
        self.action_ecd_plot.setObjectName(_fromUtf8("action_ecd_plot"))
        self.action_save_selection = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.action_save_selection.setIcon(icon)
        self.action_save_selection.setObjectName(_fromUtf8("action_save_selection"))
        self.action_toggle_filters = QtGui.QAction(MainWindow)
        self.action_toggle_filters.setCheckable(True)
        self.action_toggle_filters.setObjectName(_fromUtf8("action_toggle_filters"))
        self.action_toggle_stopwords = QtGui.QAction(MainWindow)
        self.action_toggle_stopwords.setCheckable(True)
        self.action_toggle_stopwords.setObjectName(_fromUtf8("action_toggle_stopwords"))
        self.action_create_textgrid = QtGui.QAction(MainWindow)
        self.action_create_textgrid.setObjectName(_fromUtf8("action_create_textgrid"))
        self.action_available_modules = QtGui.QAction(MainWindow)
        self.action_available_modules.setObjectName(_fromUtf8("action_available_modules"))
        self.menuFile.addAction(self.action_save_results)
        self.menuFile.addAction(self.action_save_selection)
        self.menuFile.addAction(self.action_create_textgrid)
        self.menuFile.addAction(self.action_copy_to_clipboard)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_view_log)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_quit)
        self.menuHilfe.addAction(self.action_help)
        self.menuHilfe.addSeparator()
        self.menuHilfe.addAction(self.action_available_modules)
        self.menuHilfe.addAction(self.action_about_coquery)
        self.menuCorpus.addAction(self.action_manage_corpus)
        self.menuCorpus.addSeparator()
        self.menuCorpus.addAction(self.action_statistics)
        self.menuCorpus.addAction(self.action_corpus_documentation)
        self.menuSettings.addAction(self.action_connection_settings)
        self.menuSettings.addAction(self.action_settings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.action_toggle_filters)
        self.menuSettings.addAction(self.action_toggle_stopwords)
        self.menuFrequencies.addAction(self.action_percentage_bars)
        self.menuFrequencies.addAction(self.action_stacked_bars)
        self.menuFrequencies.addAction(self.action_barchart_plot)
        self.menuFrequency_maps.addAction(self.action_heat_map)
        self.menuFrequency_maps.addAction(self.action_tree_map)
        self.menuFrequency_maps.addAction(self.action_word_cloud)
        self.menuFrequency_maps.addAction(self.action_bubble_chart)
        self.menuCorpus_locations.addAction(self.action_barcode_plot)
        self.menuCorpus_locations.addAction(self.action_beeswarm_plot)
        self.menuDensity_plots.addAction(self.action_kde_plot)
        self.menuDensity_plots.addAction(self.action_ecd_plot)
        self.menuTime_data.addAction(self.action_percentage_area_plot)
        self.menuTime_data.addAction(self.action_stacked_area_plot)
        self.menuTime_data.addAction(self.action_line_plot)
        self.menuAnalyse.addAction(self.menuCorpus_locations.menuAction())
        self.menuAnalyse.addAction(self.menuFrequencies.menuAction())
        self.menuAnalyse.addAction(self.menuTime_data.menuAction())
        self.menuAnalyse.addAction(self.menuFrequency_maps.menuAction())
        self.menuAnalyse.addAction(self.menuDensity_plots.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCorpus.menuAction())
        self.menubar.addAction(self.menu_Results.menuAction())
        self.menubar.addAction(self.menuAnalyse.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())
        self.label_2.setBuddy(self.combo_corpus)
        self.label_5.setBuddy(self.radio_no_summary)
        self.label_7.setBuddy(self.combo_summary)

        self.retranslateUi(MainWindow)
        self.tool_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Coquery", None))
        self.box_corpus_select.setTitle(_translate("MainWindow", "&Data source", None))
        self.label_2.setText(_translate("MainWindow", "&Corpus:", None))
        self.label_data_columns.setText(_translate("MainWindow", "Data co&lumns:", None))
        self.button_run_query.setText(_translate("MainWindow", "&Query", None))
        self.box_input_settings.setTitle(_translate("MainWindow", "Query &strings", None))
        self.edit_file_name.setPlaceholderText(_translate("MainWindow", "Choose an input file", None))
        self.button_browse_file.setText(_translate("MainWindow", "&Open", None))
        self.button_browse_file.setShortcut(_translate("MainWindow", "Alt+B", None))
        self.button_file_options.setText(_translate("MainWindow", "O&ptions", None))
        self.button_file_options.setShortcut(_translate("MainWindow", "Alt+B", None))
        self.groupBox.setTitle(_translate("MainWindow", "Output &management", None))
        self.radio_context_none.setText(_translate("MainWindow", "None", None))
        self.radio_context_mode_kwic.setText(_translate("MainWindow", "KWIC", None))
        self.radio_context_mode_string.setText(_translate("MainWindow", "Single string", None))
        self.radio_context_mode_columns.setText(_translate("MainWindow", "Columns", None))
        self.context_left_span.setPrefix(_translate("MainWindow", "Left: ", None))
        self.context_right_span.setPrefix(_translate("MainWindow", "Right: ", None))
        self.checkBox.setText(_translate("MainWindow", "Use stop words", None))
        self.pushButton.setText(_translate("MainWindow", "Save", None))
        self.pushButton_2.setText(_translate("MainWindow", "Load", None))
        self.button_remove_group.setText(_translate("MainWindow", "Remove", None))
        self.button_filters_2.setText(_translate("MainWindow", "Group fil&ters...", None))
        self.button_add_group_function.setText(_translate("MainWindow", "Group functions...", None))
        self.label_5.setText(_translate("MainWindow", "Show all &matches", None))
        self.radio_no_summary.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Do not aggregate the query results.</span></p><p>Every token that matches the query string is listed in the \'Query results\' table. </p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "&Transform matches:", None))
        self.button_filters.setText(_translate("MainWindow", "Summary fil&ters...", None))
        self.button_add_summary_function.setText(_translate("MainWindow", "Summary functions...", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuHilfe.setTitle(_translate("MainWindow", "&Help", None))
        self.menuCorpus.setTitle(_translate("MainWindow", "&Corpus", None))
        self.menuSettings.setTitle(_translate("MainWindow", "&Preferences", None))
        self.menuAnalyse.setTitle(_translate("MainWindow", "&Visualizations", None))
        self.menuFrequencies.setTitle(_translate("MainWindow", "&Bar charts", None))
        self.menuFrequency_maps.setTitle(_translate("MainWindow", "Frequency maps", None))
        self.menuCorpus_locations.setTitle(_translate("MainWindow", "&Corpus locations", None))
        self.menuDensity_plots.setTitle(_translate("MainWindow", "Density plots", None))
        self.menuTime_data.setTitle(_translate("MainWindow", "&Time data", None))
        self.menu_Results.setTitle(_translate("MainWindow", "&Output", None))
        self.action_open_input_file.setText(_translate("MainWindow", "&Open input file...", None))
        self.action_open_input_file.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_help.setText(_translate("MainWindow", "&Help", None))
        self.action_help.setShortcut(_translate("MainWindow", "F1", None))
        self.action_about_coquery.setText(_translate("MainWindow", "&About Coquery", None))
        self.actionDummy.setText(_translate("MainWindow", "Dummy", None))
        self.action_distinct_tokens.setText(_translate("MainWindow", "Distinct tokens", None))
        self.action_frequency.setText(_translate("MainWindow", "Frequency", None))
        self.action_all_tokens.setText(_translate("MainWindow", "All tokens", None))
        self.action_statistics.setText(_translate("MainWindow", "&Statistics", None))
        self.action_connection_settings.setText(_translate("MainWindow", "&Database connections...", None))
        self.action_settings.setText(_translate("MainWindow", "&Settings...", None))
        self.action_quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_build_corpus.setText(_translate("MainWindow", "&Build new corpus...", None))
        self.action_build_corpus.setToolTip(_translate("MainWindow", "Build a new corpus from text files in a folder", None))
        self.action_remove_corpus.setText(_translate("MainWindow", "&Remove corpus...", None))
        self.action_remove_corpus.setToolTip(_translate("MainWindow", "Permanently and irrevocably remove corpus database", None))
        self.action_manage_corpus.setText(_translate("MainWindow", "Corpus &manager...", None))
        self.action_manage_corpus.setToolTip(_translate("MainWindow", "Install a corpus into a MySQL database", None))
        self.action_manage_corpus.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.action_tree_map.setText(_translate("MainWindow", "&Tree map", None))
        self.action_heat_map.setText(_translate("MainWindow", "&Heat map", None))
        self.action_word_cloud.setText(_translate("MainWindow", "Word cloud", None))
        self.action_barcode_plot.setText(_translate("MainWindow", "&Barcode plot", None))
        self.action_beeswarm_plot.setText(_translate("MainWindow", "Bee&swarm plot", None))
        self.action_barchart_plot.setText(_translate("MainWindow", "&Bars", None))
        self.action_time_series_plot.setText(_translate("MainWindow", "T&ime series", None))
        self.action_corpus_documentation.setText(_translate("MainWindow", "&Documentation...", None))
        self.action_percentage_area_plot.setText(_translate("MainWindow", "&Percentage areas", None))
        self.action_stacked_area_plot.setText(_translate("MainWindow", "&Stacked areas", None))
        self.action_line_plot.setText(_translate("MainWindow", "&Lines", None))
        self.actionStop_words.setText(_translate("MainWindow", "Stop words...", None))
        self.actionStop_words_2.setText(_translate("MainWindow", "&Stop words...", None))
        self.action_percentage_bars.setText(_translate("MainWindow", "&Percentage bars", None))
        self.action_stacked_bars.setText(_translate("MainWindow", "&Stacked bars", None))
        self.action_view_log.setText(_translate("MainWindow", "View &log file...", None))
        self.action_mysql_server_help.setText(_translate("MainWindow", "MySQL server help", None))
        self.action_Column_context_menu.setText(_translate("MainWindow", "[Column context menu]", None))
        self.action_Row_context_menu.setText(_translate("MainWindow", "[Row context menu]", None))
        self.actionCopy_to_clipboard.setText(_translate("MainWindow", "Copy to clipboard", None))
        self.actionSave_results.setText(_translate("MainWindow", "Save", None))
        self.action_Selection_menu.setText(_translate("MainWindow", "[Selection menu]", None))
        self.action_bubble_chart.setText(_translate("MainWindow", "&Bubble chart", None))
        self.action_save_results.setText(_translate("MainWindow", "&Save results...", None))
        self.action_save_results.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_copy_to_clipboard.setText(_translate("MainWindow", "&Copy selection to clipboard", None))
        self.action_copy_to_clipboard.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.action_kde_plot.setText(_translate("MainWindow", "Kernel Density Estimate", None))
        self.action_ecd_plot.setText(_translate("MainWindow", "Estimated cumulative distribution", None))
        self.action_save_selection.setText(_translate("MainWindow", "Sa&ve selection...", None))
        self.action_save_selection.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.action_toggle_filters.setText(_translate("MainWindow", "Use &filters", None))
        self.action_toggle_stopwords.setText(_translate("MainWindow", "Use stop&words", None))
        self.action_create_textgrid.setText(_translate("MainWindow", "Create te&xtgrid...", None))
        self.action_available_modules.setText(_translate("MainWindow", "Available &modules...", None))

from ..classes import CoqListWidget, CoqTableView, CoqTextEdit

