# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coquery.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.options_area = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.options_area.sizePolicy().hasHeightForWidth())
        self.options_area.setSizePolicy(sizePolicy)
        self.options_area.setObjectName("options_area")
        self.gridLayout = QtWidgets.QGridLayout(self.options_area)
        self.gridLayout.setContentsMargins(0, 0, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.group_feature_selection = QtWidgets.QGroupBox(self.options_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_feature_selection.sizePolicy().hasHeightForWidth())
        self.group_feature_selection.setSizePolicy(sizePolicy)
        self.group_feature_selection.setObjectName("group_feature_selection")
        self.output_columns = QtWidgets.QVBoxLayout(self.group_feature_selection)
        self.output_columns.setObjectName("output_columns")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.group_feature_selection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.combo_corpus = QtWidgets.QComboBox(self.group_feature_selection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_corpus.sizePolicy().hasHeightForWidth())
        self.combo_corpus.setSizePolicy(sizePolicy)
        self.combo_corpus.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.combo_corpus.setEditable(False)
        self.combo_corpus.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.combo_corpus.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.combo_corpus.setFrame(True)
        self.combo_corpus.setObjectName("combo_corpus")
        self.horizontalLayout_2.addWidget(self.combo_corpus)
        self.horizontalLayout_2.setStretch(1, 1)
        self.output_columns.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.output_columns.addItem(spacerItem)
        self.gridLayout.addWidget(self.group_feature_selection, 0, 0, 2, 1)
        self.group_buttons = QtWidgets.QGroupBox(self.options_area)
        self.group_buttons.setObjectName("group_buttons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.group_buttons)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.button_run_query = QtWidgets.QPushButton(self.group_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_run_query.sizePolicy().hasHeightForWidth())
        self.button_run_query.setSizePolicy(sizePolicy)
        self.button_run_query.setAutoDefault(True)
        self.button_run_query.setDefault(True)
        self.button_run_query.setObjectName("button_run_query")
        self.horizontalLayout_3.addWidget(self.button_run_query)
        self.button_run_query_to_file = QtWidgets.QPushButton(self.group_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_run_query_to_file.sizePolicy().hasHeightForWidth())
        self.button_run_query_to_file.setSizePolicy(sizePolicy)
        self.button_run_query_to_file.setAutoDefault(True)
        self.button_run_query_to_file.setDefault(True)
        self.button_run_query_to_file.setObjectName("button_run_query_to_file")
        self.horizontalLayout_3.addWidget(self.button_run_query_to_file)
        self.button_stop_query = QtWidgets.QPushButton(self.group_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stop_query.sizePolicy().hasHeightForWidth())
        self.button_stop_query.setSizePolicy(sizePolicy)
        self.button_stop_query.setAutoDefault(False)
        self.button_stop_query.setDefault(False)
        self.button_stop_query.setObjectName("button_stop_query")
        self.horizontalLayout_3.addWidget(self.button_stop_query)
        spacerItem2 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addWidget(self.group_buttons, 1, 1, 1, 1)
        self.group_management = QtWidgets.QGroupBox(self.options_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_management.sizePolicy().hasHeightForWidth())
        self.group_management.setSizePolicy(sizePolicy)
        self.group_management.setObjectName("group_management")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_management)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_toolbox = QtWidgets.QTableWidget(self.group_management)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_toolbox.sizePolicy().hasHeightForWidth())
        self.list_toolbox.setSizePolicy(sizePolicy)
        self.list_toolbox.setAutoScroll(False)
        self.list_toolbox.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_toolbox.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.list_toolbox.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.list_toolbox.setShowGrid(False)
        self.list_toolbox.setRowCount(6)
        self.list_toolbox.setColumnCount(3)
        self.list_toolbox.setObjectName("list_toolbox")
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_toolbox.setItem(5, 2, item)
        self.list_toolbox.horizontalHeader().setVisible(False)
        self.list_toolbox.horizontalHeader().setDefaultSectionSize(0)
        self.list_toolbox.horizontalHeader().setMinimumSectionSize(0)
        self.list_toolbox.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.list_toolbox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.tool_widget = QtWidgets.QStackedWidget(self.group_management)
        self.tool_widget.setObjectName("tool_widget")
        self.tool_widget_column_order = QtWidgets.QWidget()
        self.tool_widget_column_order.setObjectName("tool_widget_column_order")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tool_widget_column_order)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.list_column_order = CoqButtonList(self.tool_widget_column_order)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_column_order.sizePolicy().hasHeightForWidth())
        self.list_column_order.setSizePolicy(sizePolicy)
        self.list_column_order.setObjectName("list_column_order")
        self.verticalLayout_4.addWidget(self.list_column_order)
        self.tool_widget.addWidget(self.tool_widget_column_order)
        self.tool_widget_page_context = QtWidgets.QWidget()
        self.tool_widget_page_context.setObjectName("tool_widget_page_context")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tool_widget_page_context)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 0, 1, 1)
        self.widget_context = QtWidgets.QWidget(self.tool_widget_page_context)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_context.sizePolicy().hasHeightForWidth())
        self.widget_context.setSizePolicy(sizePolicy)
        self.widget_context.setObjectName("widget_context")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_context)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radio_context_mode_none = QtWidgets.QRadioButton(self.widget_context)
        self.radio_context_mode_none.setObjectName("radio_context_mode_none")
        self.verticalLayout_5.addWidget(self.radio_context_mode_none)
        self.line = QtWidgets.QFrame(self.widget_context)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.radio_context_mode_columns = QtWidgets.QRadioButton(self.widget_context)
        self.radio_context_mode_columns.setStyleSheet("text-align: center center")
        self.radio_context_mode_columns.setObjectName("radio_context_mode_columns")
        self.verticalLayout_5.addWidget(self.radio_context_mode_columns)
        self.radio_context_mode_kwic = QtWidgets.QRadioButton(self.widget_context)
        self.radio_context_mode_kwic.setStyleSheet("text-align: center center")
        self.radio_context_mode_kwic.setObjectName("radio_context_mode_kwic")
        self.verticalLayout_5.addWidget(self.radio_context_mode_kwic)
        self.radio_context_mode_string = QtWidgets.QRadioButton(self.widget_context)
        self.radio_context_mode_string.setStyleSheet("text-align: center center")
        self.radio_context_mode_string.setObjectName("radio_context_mode_string")
        self.verticalLayout_5.addWidget(self.radio_context_mode_string)
        self.gridLayout_2.addWidget(self.widget_context, 0, 1, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 3, 1, 1)
        self.context_left_span = QtWidgets.QSpinBox(self.tool_widget_page_context)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span.sizePolicy().hasHeightForWidth())
        self.context_left_span.setSizePolicy(sizePolicy)
        self.context_left_span.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.context_left_span.setSuffix("")
        self.context_left_span.setObjectName("context_left_span")
        self.gridLayout_2.addWidget(self.context_left_span, 1, 1, 1, 1)
        self.context_right_span = QtWidgets.QSpinBox(self.tool_widget_page_context)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_right_span.sizePolicy().hasHeightForWidth())
        self.context_right_span.setSizePolicy(sizePolicy)
        self.context_right_span.setFrame(True)
        self.context_right_span.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.context_right_span.setSuffix("")
        self.context_right_span.setObjectName("context_right_span")
        self.gridLayout_2.addWidget(self.context_right_span, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tool_widget_page_context)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 2, 1, 1, 2)
        self.check_restrict = QtWidgets.QCheckBox(self.tool_widget_page_context)
        self.check_restrict.setObjectName("check_restrict")
        self.gridLayout_2.addWidget(self.check_restrict, 3, 1, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 4, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.tool_widget.addWidget(self.tool_widget_page_context)
        self.tool_widget_page_stopwords_2 = QtWidgets.QWidget()
        self.tool_widget_page_stopwords_2.setObjectName("tool_widget_page_stopwords_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tool_widget_page_stopwords_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 2, 3, 1)
        self.label_stopwords = QtWidgets.QLabel(self.tool_widget_page_stopwords_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stopwords.sizePolicy().hasHeightForWidth())
        self.label_stopwords.setSizePolicy(sizePolicy)
        self.label_stopwords.setObjectName("label_stopwords")
        self.gridLayout_4.addWidget(self.label_stopwords, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 2, 1, 1, 1)
        self.button_stopwords = QtWidgets.QPushButton(self.tool_widget_page_stopwords_2)
        self.button_stopwords.setObjectName("button_stopwords")
        self.gridLayout_4.addWidget(self.button_stopwords, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 0, 3, 1)
        self.tool_widget.addWidget(self.tool_widget_page_stopwords_2)
        self.tool_widget_page_groups_2 = QtWidgets.QWidget()
        self.tool_widget_page_groups_2.setObjectName("tool_widget_page_groups_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tool_widget_page_groups_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tree_groups = CoqGroupTree(self.tool_widget_page_groups_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_groups.sizePolicy().hasHeightForWidth())
        self.tree_groups.setSizePolicy(sizePolicy)
        self.tree_groups.setObjectName("tree_groups")
        self.tree_groups.headerItem().setText(0, "1")
        self.verticalLayout_6.addWidget(self.tree_groups)
        self.tool_widget.addWidget(self.tool_widget_page_groups_2)
        self.tool_widget_page_transform_2 = QtWidgets.QWidget()
        self.tool_widget_page_transform_2.setObjectName("tool_widget_page_transform_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tool_widget_page_transform_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem10, 0, 0, 1, 1)
        self.layout_aggregate = QtWidgets.QVBoxLayout()
        self.layout_aggregate.setContentsMargins(0, 0, 0, 0)
        self.layout_aggregate.setSpacing(1)
        self.layout_aggregate.setObjectName("layout_aggregate")
        self.gridLayout_7.addLayout(self.layout_aggregate, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem11, 0, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem12, 1, 0, 1, 3)
        self.tool_widget.addWidget(self.tool_widget_page_transform_2)
        self.tool_widget_page_summary_2 = QtWidgets.QWidget()
        self.tool_widget_page_summary_2.setObjectName("tool_widget_page_summary_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tool_widget_page_summary_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_add_summary_function = QtWidgets.QPushButton(self.tool_widget_page_summary_2)
        self.button_add_summary_function.setObjectName("button_add_summary_function")
        self.gridLayout_5.addWidget(self.button_add_summary_function, 0, 1, 1, 1)
        self.button_filters = QtWidgets.QPushButton(self.tool_widget_page_summary_2)
        self.button_filters.setObjectName("button_filters")
        self.gridLayout_5.addWidget(self.button_filters, 1, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tool_widget_page_summary_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_5.addWidget(self.line_3, 2, 1, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.check_sample_matches = QtWidgets.QCheckBox(self.tool_widget_page_summary_2)
        self.check_sample_matches.setText("")
        self.check_sample_matches.setObjectName("check_sample_matches")
        self.gridLayout_8.addWidget(self.check_sample_matches, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tool_widget_page_summary_2)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 1, 1, 1)
        self.spin_sample_size = QtWidgets.QSpinBox(self.tool_widget_page_summary_2)
        self.spin_sample_size.setMinimum(1)
        self.spin_sample_size.setMaximum(999999999)
        self.spin_sample_size.setProperty("value", 10)
        self.spin_sample_size.setObjectName("spin_sample_size")
        self.gridLayout_8.addWidget(self.spin_sample_size, 1, 1, 1, 1)
        self.gridLayout_8.setColumnStretch(1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_8, 3, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem13, 0, 2, 5, 1)
        spacerItem14 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem14, 0, 0, 5, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem15, 4, 1, 1, 1)
        self.tool_widget.addWidget(self.tool_widget_page_summary_2)
        self.verticalLayout.addWidget(self.tool_widget)
        self.button_box_reaggregate = QtWidgets.QWidget(self.group_management)
        self.button_box_reaggregate.setObjectName("button_box_reaggregate")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.button_box_reaggregate)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_apply_management = QtWidgets.QPushButton(self.button_box_reaggregate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_apply_management.sizePolicy().hasHeightForWidth())
        self.button_apply_management.setSizePolicy(sizePolicy)
        self.button_apply_management.setObjectName("button_apply_management")
        self.horizontalLayout_5.addWidget(self.button_apply_management)
        self.button_cancel_management = QtWidgets.QPushButton(self.button_box_reaggregate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_cancel_management.sizePolicy().hasHeightForWidth())
        self.button_cancel_management.setSizePolicy(sizePolicy)
        self.button_cancel_management.setObjectName("button_cancel_management")
        self.horizontalLayout_5.addWidget(self.button_cancel_management)
        self.verticalLayout.addWidget(self.button_box_reaggregate)
        self.gridLayout.addWidget(self.group_management, 0, 2, 2, 1)
        self.group_query_strings = QtWidgets.QGroupBox(self.options_area)
        self.group_query_strings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.group_query_strings.setObjectName("group_query_strings")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_query_strings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radio_query_string = QtWidgets.QRadioButton(self.group_query_strings)
        self.radio_query_string.setText("")
        self.radio_query_string.setChecked(True)
        self.radio_query_string.setObjectName("radio_query_string")
        self.gridLayout_3.addWidget(self.radio_query_string, 0, 0, 1, 1)
        self.dummy_1 = QtWidgets.QLineEdit(self.group_query_strings)
        self.dummy_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dummy_1.sizePolicy().hasHeightForWidth())
        self.dummy_1.setSizePolicy(sizePolicy)
        self.dummy_1.setObjectName("dummy_1")
        self.gridLayout_3.addWidget(self.dummy_1, 0, 1, 1, 1)
        self.radio_query_file = QtWidgets.QRadioButton(self.group_query_strings)
        self.radio_query_file.setText("")
        self.radio_query_file.setObjectName("radio_query_file")
        self.gridLayout_3.addWidget(self.radio_query_file, 2, 0, 1, 1)
        self.dummy_2 = QtWidgets.QLineEdit(self.group_query_strings)
        self.dummy_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dummy_2.sizePolicy().hasHeightForWidth())
        self.dummy_2.setSizePolicy(sizePolicy)
        self.dummy_2.setObjectName("dummy_2")
        self.gridLayout_3.addWidget(self.dummy_2, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_file_name = CoqClickableLabel(self.group_query_strings)
        self.edit_file_name.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_file_name.sizePolicy().hasHeightForWidth())
        self.edit_file_name.setSizePolicy(sizePolicy)
        self.edit_file_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_file_name.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.edit_file_name.setObjectName("edit_file_name")
        self.horizontalLayout.addWidget(self.edit_file_name)
        self.button_change_file = QtWidgets.QPushButton(self.group_query_strings)
        self.button_change_file.setObjectName("button_change_file")
        self.horizontalLayout.addWidget(self.button_change_file)
        self.horizontalLayout.setStretch(0, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 2, 1, 1)
        self.edit_query_string = CoqTextEdit(self.group_query_strings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_query_string.sizePolicy().hasHeightForWidth())
        self.edit_query_string.setSizePolicy(sizePolicy)
        self.edit_query_string.setAcceptRichText(False)
        self.edit_query_string.setObjectName("edit_query_string")
        self.gridLayout_3.addWidget(self.edit_query_string, 0, 2, 2, 1)
        self.gridLayout.addWidget(self.group_query_strings, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout.setColumnStretch(2, 3)
        self.gridLayout.setRowStretch(0, 1)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_columns = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_columns.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_columns.setChildrenCollapsible(False)
        self.splitter_columns.setObjectName("splitter_columns")
        self.data_preview = CoqResultsTableView(self.splitter_columns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_preview.sizePolicy().hasHeightForWidth())
        self.data_preview.setSizePolicy(sizePolicy)
        self.data_preview.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.data_preview.setAlternatingRowColors(True)
        self.data_preview.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.data_preview.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.data_preview.setTextElideMode(QtCore.Qt.ElideRight)
        self.data_preview.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setObjectName("data_preview")
        self.widget_hidden_columns = QtWidgets.QWidget(self.splitter_columns)
        self.widget_hidden_columns.setObjectName("widget_hidden_columns")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_hidden_columns)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.button_toggle_hidden = CoqRotatedButton(self.widget_hidden_columns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_toggle_hidden.sizePolicy().hasHeightForWidth())
        self.button_toggle_hidden.setSizePolicy(sizePolicy)
        self.button_toggle_hidden.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(244, 165, 130);")
        self.button_toggle_hidden.setObjectName("button_toggle_hidden")
        self.verticalLayout_8.addWidget(self.button_toggle_hidden)
        spacerItem16 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem16)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.hidden_columns = CoqHiddenResultsTable(self.widget_hidden_columns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hidden_columns.sizePolicy().hasHeightForWidth())
        self.hidden_columns.setSizePolicy(sizePolicy)
        self.hidden_columns.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.hidden_columns.setAlternatingRowColors(True)
        self.hidden_columns.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.hidden_columns.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.hidden_columns.setTextElideMode(QtCore.Qt.ElideRight)
        self.hidden_columns.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.hidden_columns.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.hidden_columns.setObjectName("hidden_columns")
        self.horizontalLayout_6.addWidget(self.hidden_columns)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.splitter_columns)
        self.text_no_match = QtWidgets.QTextEdit(self.layoutWidget)
        self.text_no_match.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_no_match.sizePolicy().hasHeightForWidth())
        self.text_no_match.setSizePolicy(sizePolicy)
        self.text_no_match.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.text_no_match.setObjectName("text_no_match")
        self.verticalLayout_3.addWidget(self.text_no_match)
        self.widget_find = CoqFindWidget(self.layoutWidget)
        self.widget_find.setObjectName("widget_find")
        self.verticalLayout_3.addWidget(self.widget_find)
        self.verticalLayout_3.setStretch(0, 1)
        self.gridLayout_6.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuCorpus = QtWidgets.QMenu(self.menubar)
        self.menuCorpus.setObjectName("menuCorpus")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menu_Results = QtWidgets.QMenu(self.menubar)
        self.menu_Results.setObjectName("menu_Results")
        MainWindow.setMenuBar(self.menubar)
        self.action_help = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-contents")
        self.action_help.setIcon(icon)
        self.action_help.setObjectName("action_help")
        self.action_about_coquery = QtWidgets.QAction(MainWindow)
        self.action_about_coquery.setObjectName("action_about_coquery")
        self.action_statistics = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("view-statistics")
        self.action_statistics.setIcon(icon)
        self.action_statistics.setObjectName("action_statistics")
        self.action_connection_settings = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("server-database")
        self.action_connection_settings.setIcon(icon)
        self.action_connection_settings.setObjectName("action_connection_settings")
        self.action_settings = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("configure")
        self.action_settings.setIcon(icon)
        self.action_settings.setObjectName("action_settings")
        self.action_quit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.action_quit.setIcon(icon)
        self.action_quit.setObjectName("action_quit")
        self.action_manage_corpus = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("server-database")
        self.action_manage_corpus.setIcon(icon)
        self.action_manage_corpus.setObjectName("action_manage_corpus")
        self.action_corpus_documentation = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-browser")
        self.action_corpus_documentation.setIcon(icon)
        self.action_corpus_documentation.setObjectName("action_corpus_documentation")
        self.action_view_log = QtWidgets.QAction(MainWindow)
        self.action_view_log.setObjectName("action_view_log")
        self.action_save_results = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.action_save_results.setIcon(icon)
        self.action_save_results.setObjectName("action_save_results")
        self.action_copy_to_clipboard = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-copy")
        self.action_copy_to_clipboard.setIcon(icon)
        self.action_copy_to_clipboard.setObjectName("action_copy_to_clipboard")
        self.action_save_selection = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.action_save_selection.setIcon(icon)
        self.action_save_selection.setObjectName("action_save_selection")
        self.action_toggle_management = QtWidgets.QAction(MainWindow)
        self.action_toggle_management.setCheckable(True)
        self.action_toggle_management.setObjectName("action_toggle_management")
        self.action_toggle_columns = QtWidgets.QAction(MainWindow)
        self.action_toggle_columns.setCheckable(True)
        self.action_toggle_columns.setObjectName("action_toggle_columns")
        self.action_create_textgrid = QtWidgets.QAction(MainWindow)
        self.action_create_textgrid.setObjectName("action_create_textgrid")
        self.action_available_modules = QtWidgets.QAction(MainWindow)
        self.action_available_modules.setObjectName("action_available_modules")
        self.action_reference_corpus = QtWidgets.QAction(MainWindow)
        self.action_reference_corpus.setObjectName("action_reference_corpus")
        self.action_save_query = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.action_save_query.setIcon(icon)
        self.action_save_query.setObjectName("action_save_query")
        self.action_load_query = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.action_load_query.setIcon(icon)
        self.action_load_query.setObjectName("action_load_query")
        self.action_share_query = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-share")
        self.action_share_query.setIcon(icon)
        self.action_share_query.setObjectName("action_share_query")
        self.action_column_properties = QtWidgets.QAction(MainWindow)
        self.action_column_properties.setObjectName("action_column_properties")
        self.action_show_hidden = QtWidgets.QAction(MainWindow)
        self.action_show_hidden.setObjectName("action_show_hidden")
        self.action_add_column = QtWidgets.QAction(MainWindow)
        self.action_add_column.setObjectName("action_add_column")
        self.action_add_function = QtWidgets.QAction(MainWindow)
        self.action_add_function.setObjectName("action_add_function")
        self.action_link_external = QtWidgets.QAction(MainWindow)
        self.action_link_external.setObjectName("action_link_external")
        self.action_find = QtWidgets.QAction(MainWindow)
        self.action_find.setObjectName("action_find")
        self.action_visualization_designer = QtWidgets.QAction(MainWindow)
        self.action_visualization_designer.setObjectName("action_visualization_designer")
        self.action_how_to_cite = QtWidgets.QAction(MainWindow)
        self.action_how_to_cite.setObjectName("action_how_to_cite")
        self.action_regex_tester = QtWidgets.QAction(MainWindow)
        self.action_regex_tester.setObjectName("action_regex_tester")
        self.action_pos_helper = QtWidgets.QAction(MainWindow)
        self.action_pos_helper.setObjectName("action_pos_helper")
        self.action_view_sql = QtWidgets.QAction(MainWindow)
        self.action_view_sql.setObjectName("action_view_sql")
        self.menuFile.addAction(self.action_save_results)
        self.menuFile.addAction(self.action_save_selection)
        self.menuFile.addAction(self.action_copy_to_clipboard)
        self.menuFile.addAction(self.action_create_textgrid)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_save_query)
        self.menuFile.addAction(self.action_load_query)
        self.menuFile.addAction(self.action_share_query)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_view_log)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_quit)
        self.menuHelp.addAction(self.action_help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_available_modules)
        self.menuHelp.addAction(self.action_about_coquery)
        self.menuHelp.addAction(self.action_how_to_cite)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_regex_tester)
        self.menuHelp.addAction(self.action_pos_helper)
        self.menuCorpus.addAction(self.action_manage_corpus)
        self.menuCorpus.addSeparator()
        self.menuCorpus.addAction(self.action_link_external)
        self.menuCorpus.addAction(self.action_reference_corpus)
        self.menuCorpus.addSeparator()
        self.menuCorpus.addAction(self.action_statistics)
        self.menuCorpus.addAction(self.action_corpus_documentation)
        self.menuSettings.addAction(self.action_connection_settings)
        self.menuSettings.addAction(self.action_settings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.action_toggle_columns)
        self.menuSettings.addAction(self.action_toggle_management)
        self.menu_Results.addAction(self.action_visualization_designer)
        self.menu_Results.addSeparator()
        self.menu_Results.addAction(self.action_column_properties)
        self.menu_Results.addAction(self.action_show_hidden)
        self.menu_Results.addAction(self.action_add_column)
        self.menu_Results.addAction(self.action_add_function)
        self.menu_Results.addSeparator()
        self.menu_Results.addAction(self.action_find)
        self.menu_Results.addSeparator()
        self.menu_Results.addAction(self.action_view_sql)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCorpus.menuAction())
        self.menubar.addAction(self.menu_Results.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label_2.setBuddy(self.combo_corpus)
        self.label.setBuddy(self.spin_sample_size)

        self.retranslateUi(MainWindow)
        self.tool_widget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.combo_corpus, self.button_apply_management)
        MainWindow.setTabOrder(self.button_apply_management, self.button_cancel_management)
        MainWindow.setTabOrder(self.button_cancel_management, self.button_run_query)
        MainWindow.setTabOrder(self.button_run_query, self.button_stop_query)
        MainWindow.setTabOrder(self.button_stop_query, self.data_preview)
        MainWindow.setTabOrder(self.data_preview, self.button_toggle_hidden)
        MainWindow.setTabOrder(self.button_toggle_hidden, self.hidden_columns)
        MainWindow.setTabOrder(self.hidden_columns, self.text_no_match)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Coquery"))
        self.group_feature_selection.setTitle(_translate("MainWindow", "Fe&ature selection"))
        self.label_2.setText(_translate("MainWindow", "&Corpus:"))
        self.button_run_query.setText(_translate("MainWindow", "&New query"))
        self.button_run_query.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.button_run_query_to_file.setText(_translate("MainWindow", "&New query to file"))
        self.button_run_query_to_file.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.button_stop_query.setText(_translate("MainWindow", "&Stop"))
        self.group_management.setTitle(_translate("MainWindow", "Data &management"))
        __sortingEnabled = self.list_toolbox.isSortingEnabled()
        self.list_toolbox.setSortingEnabled(False)
        item = self.list_toolbox.item(0, 0)
        item.setText(_translate("MainWindow", "Feature order"))
        item = self.list_toolbox.item(1, 0)
        item.setText(_translate("MainWindow", "Context/KWIC"))
        item = self.list_toolbox.item(2, 0)
        item.setText(_translate("MainWindow", "Stopwords"))
        item = self.list_toolbox.item(3, 0)
        item.setText(_translate("MainWindow", "Data groups"))
        item = self.list_toolbox.item(4, 0)
        item.setText(_translate("MainWindow", "Transform"))
        item = self.list_toolbox.item(5, 0)
        item.setText(_translate("MainWindow", "Finalize"))
        self.list_toolbox.setSortingEnabled(__sortingEnabled)
        self.radio_context_mode_none.setText(_translate("MainWindow", "No context"))
        self.radio_context_mode_columns.setText(_translate("MainWindow", "Colu&mns"))
        self.radio_context_mode_kwic.setText(_translate("MainWindow", "&KWIC"))
        self.radio_context_mode_string.setText(_translate("MainWindow", "Sing&le string"))
        self.context_left_span.setPrefix(_translate("MainWindow", "Left: "))
        self.context_right_span.setPrefix(_translate("MainWindow", "Right: "))
        self.check_restrict.setText(_translate("MainWindow", "&Restrict to sentences"))
        self.label_stopwords.setText(_translate("MainWindow", "Number of stop words: {}"))
        self.button_stopwords.setText(_translate("MainWindow", "Change stop &words..."))
        self.button_add_summary_function.setText(_translate("MainWindow", "Summary functions{}..."))
        self.button_filters.setText(_translate("MainWindow", "Result filters{}..."))
        self.label.setText(_translate("MainWindow", "Show rando&m sample:"))
        self.spin_sample_size.setSuffix(_translate("MainWindow", " match(es)"))
        self.button_apply_management.setText(_translate("MainWindow", "&Apply"))
        self.button_apply_management.setShortcut(_translate("MainWindow", "F5"))
        self.button_cancel_management.setText(_translate("MainWindow", "Cancel"))
        self.group_query_strings.setTitle(_translate("MainWindow", "Quer&y strings"))
        self.edit_file_name.setText(_translate("MainWindow", "(no &query file selected)"))
        self.button_change_file.setText(_translate("MainWindow", "C&hange..."))
        self.button_change_file.setShortcut(_translate("MainWindow", "Alt+B"))
        self.button_toggle_hidden.setText(_translate("MainWindow", "Hidden columns"))
        self.text_no_match.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans [GOOG]\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:11pt; font-weight:600;\">No match.</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuCorpus.setTitle(_translate("MainWindow", "&Corpus"))
        self.menuSettings.setTitle(_translate("MainWindow", "Op&tions"))
        self.menu_Results.setTitle(_translate("MainWindow", "&Results"))
        self.action_help.setText(_translate("MainWindow", "&Help"))
        self.action_help.setShortcut(_translate("MainWindow", "F1"))
        self.action_about_coquery.setText(_translate("MainWindow", "&About Coquery"))
        self.action_statistics.setText(_translate("MainWindow", "&Statistics"))
        self.action_connection_settings.setText(_translate("MainWindow", "&Database connections..."))
        self.action_settings.setText(_translate("MainWindow", "&Settings..."))
        self.action_quit.setText(_translate("MainWindow", "&Quit"))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_manage_corpus.setText(_translate("MainWindow", "Corpus &manager..."))
        self.action_manage_corpus.setToolTip(_translate("MainWindow", "Install a corpus into a MySQL database"))
        self.action_manage_corpus.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.action_corpus_documentation.setText(_translate("MainWindow", "&Documentation..."))
        self.action_view_log.setText(_translate("MainWindow", "View session &log..."))
        self.action_save_results.setText(_translate("MainWindow", "&Save results..."))
        self.action_save_results.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_copy_to_clipboard.setText(_translate("MainWindow", "&Copy selection to clipboard"))
        self.action_copy_to_clipboard.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.action_save_selection.setText(_translate("MainWindow", "Sa&ve selection..."))
        self.action_save_selection.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_toggle_management.setText(_translate("MainWindow", "Show &output management"))
        self.action_toggle_columns.setText(_translate("MainWindow", "Show &column &selection"))
        self.action_create_textgrid.setText(_translate("MainWindow", "Create te&xtgrids..."))
        self.action_create_textgrid.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.action_available_modules.setText(_translate("MainWindow", "Available &modules..."))
        self.action_reference_corpus.setText(_translate("MainWindow", "Set &reference corpus:"))
        self.action_reference_corpus.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.action_save_query.setText(_translate("MainWindow", "S&ave query..."))
        self.action_load_query.setText(_translate("MainWindow", "L&oad query..."))
        self.action_share_query.setText(_translate("MainWindow", "S&hare query..."))
        self.action_column_properties.setText(_translate("MainWindow", "Column &properties..."))
        self.action_column_properties.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.action_show_hidden.setText(_translate("MainWindow", "Show &hidden columns"))
        self.action_add_column.setText(_translate("MainWindow", "Add &user data column"))
        self.action_add_function.setText(_translate("MainWindow", "Add &function..."))
        self.action_add_function.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.action_link_external.setText(_translate("MainWindow", "Link e&xternal corpus"))
        self.action_link_external.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_find.setText(_translate("MainWindow", "F&ind..."))
        self.action_find.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.action_visualization_designer.setText(_translate("MainWindow", "&Visualization designer..."))
        self.action_visualization_designer.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.action_how_to_cite.setText(_translate("MainWindow", "How to &cite"))
        self.action_regex_tester.setText(_translate("MainWindow", "Regular &expression tester..."))
        self.action_pos_helper.setText(_translate("MainWindow", "&POS Tag helper.."))
        self.action_view_sql.setText(_translate("MainWindow", "View SQL queries..."))

from ..buttonlist import CoqButtonList
from ..classes import CoqClickableLabel, CoqRotatedButton, CoqTextEdit
from ..findwidget import CoqFindWidget
from ..grouptree import CoqGroupTree
from ..resultstable import CoqHiddenResultsTable, CoqResultsTableView
