# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'corpusInstaller.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from coquery.gui.pyqt_compat import QtCore, QtGui, frameShadow, frameShape

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CorpusInstaller(object):
    def setupUi(self, CorpusInstaller):
        CorpusInstaller.setObjectName(_fromUtf8("CorpusInstaller"))
        CorpusInstaller.resize(640, 488)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CorpusInstaller.sizePolicy().hasHeightForWidth())
        CorpusInstaller.setSizePolicy(sizePolicy)
        CorpusInstaller.setModal(True)
        self.verticalLayout_4 = QtGui.QVBoxLayout(CorpusInstaller)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.name_label = QtGui.QLabel(CorpusInstaller)
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.horizontalLayout.addWidget(self.name_label)
        self.corpus_name = QtGui.QLineEdit(CorpusInstaller)
        self.corpus_name.setMaxLength(32)
        self.corpus_name.setObjectName(_fromUtf8("corpus_name"))
        self.horizontalLayout.addWidget(self.corpus_name)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.widget_options = QtGui.QWidget(CorpusInstaller)
        self.widget_options.setObjectName(_fromUtf8("widget_options"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_options)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.group_read_files = QtGui.QGroupBox(self.widget_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_read_files.sizePolicy().hasHeightForWidth())
        self.group_read_files.setSizePolicy(sizePolicy)
        self.group_read_files.setCheckable(True)
        self.group_read_files.setObjectName(_fromUtf8("group_read_files"))
        self.verticalLayout = QtGui.QVBoxLayout(self.group_read_files)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.button_metafile = QtGui.QPushButton(self.group_read_files)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.button_metafile.setIcon(icon)
        self.button_metafile.setObjectName(_fromUtf8("button_metafile"))
        self.gridLayout.addWidget(self.button_metafile, 1, 2, 1, 1)
        self.label_metafile = CoqClickableLabel(self.group_read_files)
        self.label_metafile.setFrameShape(frameShape)
        self.label_metafile.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_metafile.setText(_fromUtf8(""))
        self.label_metafile.setObjectName(_fromUtf8("label_metafile"))
        self.gridLayout.addWidget(self.label_metafile, 1, 1, 1, 1)
        self.label_input_path = QtGui.QLabel(self.group_read_files)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_input_path.sizePolicy().hasHeightForWidth())
        self.label_input_path.setSizePolicy(sizePolicy)
        self.label_input_path.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_input_path.setWordWrap(True)
        self.label_input_path.setObjectName(_fromUtf8("label_input_path"))
        self.gridLayout.addWidget(self.label_input_path, 0, 0, 1, 1)
        self.button_input_path = QtGui.QPushButton(self.group_read_files)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_input_path.sizePolicy().hasHeightForWidth())
        self.button_input_path.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("folder"))
        self.button_input_path.setIcon(icon)
        self.button_input_path.setObjectName(_fromUtf8("button_input_path"))
        self.gridLayout.addWidget(self.button_input_path, 0, 2, 1, 1)
        self.input_path = CoqClickableLabel(self.group_read_files)
        self.input_path.setFrameShape(frameShape)
        self.input_path.setFrameShadow(QtGui.QFrame.Sunken)
        self.input_path.setObjectName(_fromUtf8("input_path"))
        self.gridLayout.addWidget(self.input_path, 0, 1, 1, 1)
        self.check_use_metafile = QtGui.QCheckBox(self.group_read_files)
        self.check_use_metafile.setObjectName(_fromUtf8("check_use_metafile"))
        self.gridLayout.addWidget(self.check_use_metafile, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.layout_nltk = QtGui.QHBoxLayout()
        self.layout_nltk.setObjectName(_fromUtf8("layout_nltk"))
        self.use_pos_tagging = QtGui.QCheckBox(self.group_read_files)
        self.use_pos_tagging.setText(_fromUtf8(""))
        self.use_pos_tagging.setObjectName(_fromUtf8("use_pos_tagging"))
        self.layout_nltk.addWidget(self.use_pos_tagging)
        self.label_pos_tagging = QtGui.QLabel(self.group_read_files)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pos_tagging.sizePolicy().hasHeightForWidth())
        self.label_pos_tagging.setSizePolicy(sizePolicy)
        self.label_pos_tagging.setText(_fromUtf8(""))
        self.label_pos_tagging.setWordWrap(True)
        self.label_pos_tagging.setObjectName(_fromUtf8("label_pos_tagging"))
        self.layout_nltk.addWidget(self.label_pos_tagging)
        self.verticalLayout.addLayout(self.layout_nltk)
        self.widget_ngram = QtGui.QWidget(self.group_read_files)
        self.widget_ngram.setObjectName(_fromUtf8("widget_ngram"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_ngram)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.check_ngram = QtGui.QCheckBox(self.widget_ngram)
        self.check_ngram.setText(_fromUtf8(""))
        self.check_ngram.setObjectName(_fromUtf8("check_ngram"))
        self.horizontalLayout_3.addWidget(self.check_ngram)
        self.label_2 = QtGui.QLabel(self.widget_ngram)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spin_n = QtGui.QSpinBox(self.widget_ngram)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_n.sizePolicy().hasHeightForWidth())
        self.spin_n.setSizePolicy(sizePolicy)
        self.spin_n.setMinimum(2)
        self.spin_n.setProperty("value", 2)
        self.spin_n.setObjectName(_fromUtf8("spin_n"))
        self.horizontalLayout_3.addWidget(self.spin_n)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_ngram_info = CoqInfoLabel(self.widget_ngram)
        self.label_ngram_info.setObjectName(_fromUtf8("label_ngram_info"))
        self.horizontalLayout_3.addWidget(self.label_ngram_info)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout.addWidget(self.widget_ngram)
        self.verticalLayout_3.addWidget(self.group_read_files)
        self.group_only_module = QtGui.QGroupBox(self.widget_options)
        self.group_only_module.setCheckable(True)
        self.group_only_module.setChecked(False)
        self.group_only_module.setObjectName(_fromUtf8("group_only_module"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.group_only_module)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_4 = QtGui.QLabel(self.group_only_module)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_3.addWidget(self.group_only_module)
        self.issue_label = QtGui.QLabel(self.widget_options)
        self.issue_label.setObjectName(_fromUtf8("issue_label"))
        self.verticalLayout_3.addWidget(self.issue_label)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.widget_options)
        self.progress_box = QtGui.QFrame(CorpusInstaller)
        self.progress_box.setFrameShape(frameShape)
        self.progress_box.setFrameShadow(frameShadow)
        self.progress_box.setObjectName(_fromUtf8("progress_box"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.progress_box)
        self.verticalLayout_2.setMargin(10)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.progress_box)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.progress_general = QtGui.QProgressBar(self.progress_box)
        self.progress_general.setMinimum(0)
        self.progress_general.setMaximum(9)
        self.progress_general.setProperty("value", 0)
        self.progress_general.setObjectName(_fromUtf8("progress_general"))
        self.verticalLayout_2.addWidget(self.progress_general)
        self.progress_bar = QtGui.QProgressBar(self.progress_box)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setFormat(_fromUtf8(""))
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        self.verticalLayout_2.addWidget(self.progress_bar)
        self.verticalLayout_4.addWidget(self.progress_box)
        self.buttonBox = QtGui.QDialogButtonBox(CorpusInstaller)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.name_label.setBuddy(self.input_path)
        self.label_input_path.setBuddy(self.input_path)

        self.retranslateUi(CorpusInstaller)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CorpusInstaller.reject)
        QtCore.QMetaObject.connectSlotsByName(CorpusInstaller)

    def retranslateUi(self, CorpusInstaller):
        CorpusInstaller.setWindowTitle(_translate("CorpusInstaller", "Corpus Installer – Coquery", None))
        self.name_label.setText(_translate("CorpusInstaller", "&Corpus name:", None))
        self.group_read_files.setTitle(_translate("CorpusInstaller", "&Read corpus data files", None))
        self.button_metafile.setText(_translate("CorpusInstaller", "Open", None))
        self.label_input_path.setText(_translate("CorpusInstaller", "Da&ta file directory:", None))
        self.button_input_path.setText(_translate("CorpusInstaller", "Browse", None))
        self.button_input_path.setShortcut(_translate("CorpusInstaller", "Alt+B", None))
        self.input_path.setText(_translate("CorpusInstaller", "(no path or file selected)", None))
        self.check_use_metafile.setText(_translate("CorpusInstaller", "Use &meta data file:", None))
        self.label_2.setText(_translate("CorpusInstaller", "&Generate lookup table for multi-item query strings,", None))
        self.spin_n.setSuffix(_translate("CorpusInstaller", " items", None))
        self.spin_n.setPrefix(_translate("CorpusInstaller", "up to ", None))
        self.label_ngram_info.setToolTip(_translate("CorpusInstaller", "<html><head/><body><p>A lookup table for multi-item queries is an additional database table. For each token in the corpus, this table also contains information on the <span style=\" font-style:italic;\">n</span> following tokens. Using a lookup table can greatly speed up queries that consist of more than one query item. However, it also greatly increases the disk space required for the corpus database, and it increases the time required to install the corpus.</p><p>Lookup tables are recommended for the larger corpora such as the BNC, COCA, or COHA.</p><p>Note that even if you do not generate a lookup table for multi-item query strings, you can still use query strings that consist of more than one query item, or that are longer than the lookup table. However, in these cases, the query may be relatively slow.</p><p>For a detailed description of multi-token lookup tables, see:</p><p>Davies, Mark. Semantically-based queries with a joint <span style=\" font-style:italic;\">BNC/WordNet</span> database. In Facchinetti, Roberta (ed.). <span style=\" font-style:italic;\">Corpus linguistics 25 years on.</span> 149–168. Amsterdam: Rodopi.</p></body></html>", None))
        self.label_ngram_info.setText(_translate("CorpusInstaller", "?", None))
        self.group_only_module.setTitle(_translate("CorpusInstaller", "Only install corpus &module", None))
        self.label_4.setText(_translate("CorpusInstaller", "Do not read corpus data files (e.g. if using a database server over the network)", None))
        self.issue_label.setText(_translate("CorpusInstaller", "TextLabel", None))
        self.label.setText(_translate("CorpusInstaller", "Installing...", None))
        self.progress_general.setFormat(_translate("CorpusInstaller", "Stage %v of %m", None))

from ..classes import CoqClickableLabel, CoqInfoLabel

