# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'corpusTable.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CorpusTable(object):
    def setupUi(self, CorpusTable):
        CorpusTable.setObjectName("CorpusTable")
        CorpusTable.resize(640, 492)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CorpusTable.sizePolicy().hasHeightForWidth())
        CorpusTable.setSizePolicy(sizePolicy)
        CorpusTable.setModal(True)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(CorpusTable)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(CorpusTable)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.corpus_name = QtWidgets.QLineEdit(CorpusTable)
        self.corpus_name.setMaxLength(32)
        self.corpus_name.setObjectName("corpus_name")
        self.horizontalLayout.addWidget(self.corpus_name)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(CorpusTable)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.input_path = CoqClickableLabel(CorpusTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_path.sizePolicy().hasHeightForWidth())
        self.input_path.setSizePolicy(sizePolicy)
        self.input_path.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_path.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_path.setObjectName("input_path")
        self.horizontalLayout_2.addWidget(self.input_path)
        self.button_input_path = QtWidgets.QPushButton(CorpusTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_input_path.sizePolicy().hasHeightForWidth())
        self.button_input_path.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("folder")
        self.button_input_path.setIcon(icon)
        self.button_input_path.setObjectName("button_input_path")
        self.horizontalLayout_2.addWidget(self.button_input_path)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.widget_options = QtWidgets.QWidget(CorpusTable)
        self.widget_options.setObjectName("widget_options")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_options)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4.addWidget(self.widget_options)
        self.groupBox = QtWidgets.QGroupBox(CorpusTable)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio_read_files = QtWidgets.QRadioButton(self.groupBox)
        self.radio_read_files.setChecked(True)
        self.radio_read_files.setObjectName("radio_read_files")
        self.verticalLayout.addWidget(self.radio_read_files)
        self.radio_only_module = QtWidgets.QRadioButton(self.groupBox)
        self.radio_only_module.setObjectName("radio_only_module")
        self.verticalLayout.addWidget(self.radio_only_module)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.issue_label = QtWidgets.QLabel(CorpusTable)
        self.issue_label.setObjectName("issue_label")
        self.verticalLayout_4.addWidget(self.issue_label)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.progress_box = QtWidgets.QFrame(CorpusTable)
        self.progress_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_box.setObjectName("progress_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.progress_box)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.progress_box)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.progress_general = QtWidgets.QProgressBar(self.progress_box)
        self.progress_general.setMinimum(0)
        self.progress_general.setMaximum(9)
        self.progress_general.setProperty("value", 0)
        self.progress_general.setObjectName("progress_general")
        self.verticalLayout_2.addWidget(self.progress_general)
        self.progress_bar = QtWidgets.QProgressBar(self.progress_box)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setFormat("")
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_2.addWidget(self.progress_bar)
        self.verticalLayout_4.addWidget(self.progress_box)
        self.buttonBox = QtWidgets.QDialogButtonBox(CorpusTable)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.name_label.setBuddy(self.corpus_name)

        self.retranslateUi(CorpusTable)
        self.buttonBox.rejected.connect(CorpusTable.reject)
        QtCore.QMetaObject.connectSlotsByName(CorpusTable)

    def retranslateUi(self, CorpusTable):
        _translate = QtCore.QCoreApplication.translate
        CorpusTable.setWindowTitle(_translate("CorpusTable", "Corpus Builder – Coquery"))
        self.name_label.setText(_translate("CorpusTable", "&Corpus name:"))
        self.label_2.setText(_translate("CorpusTable", "Data table file:"))
        self.input_path.setText(_translate("CorpusTable", "(no path or file selected)"))
        self.button_input_path.setText(_translate("CorpusTable", "&Browse"))
        self.button_input_path.setShortcut(_translate("CorpusTable", "Alt+B"))
        self.radio_read_files.setText(_translate("CorpusTable", "&Build new corpus from data table file"))
        self.radio_only_module.setText(_translate("CorpusTable", "Only install corpus &module from file"))
        self.issue_label.setText(_translate("CorpusTable", "TextLabel"))
        self.label.setText(_translate("CorpusTable", "Installing..."))
        self.progress_general.setFormat(_translate("CorpusTable", "Stage %v of %m"))

from ..classes import CoqClickableLabel
