# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'corpusInstaller.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CorpusInstaller(object):
    def setupUi(self, CorpusInstaller):
        CorpusInstaller.setObjectName("CorpusInstaller")
        CorpusInstaller.resize(640, 488)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CorpusInstaller.sizePolicy().hasHeightForWidth())
        CorpusInstaller.setSizePolicy(sizePolicy)
        CorpusInstaller.setModal(True)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(CorpusInstaller)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(CorpusInstaller)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.corpus_name = QtWidgets.QLineEdit(CorpusInstaller)
        self.corpus_name.setMaxLength(32)
        self.corpus_name.setObjectName("corpus_name")
        self.horizontalLayout.addWidget(self.corpus_name)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.widget_options = QtWidgets.QWidget(CorpusInstaller)
        self.widget_options.setObjectName("widget_options")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_options)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.group_read_files = QtWidgets.QGroupBox(self.widget_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_read_files.sizePolicy().hasHeightForWidth())
        self.group_read_files.setSizePolicy(sizePolicy)
        self.group_read_files.setCheckable(True)
        self.group_read_files.setObjectName("group_read_files")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_read_files)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_metafile = QtWidgets.QPushButton(self.group_read_files)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.button_metafile.setIcon(icon)
        self.button_metafile.setObjectName("button_metafile")
        self.gridLayout.addWidget(self.button_metafile, 1, 2, 1, 1)
        self.label_metafile = CoqClickableLabel(self.group_read_files)
        self.label_metafile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_metafile.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_metafile.setText("")
        self.label_metafile.setObjectName("label_metafile")
        self.gridLayout.addWidget(self.label_metafile, 1, 1, 1, 1)
        self.label_input_path = QtWidgets.QLabel(self.group_read_files)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_input_path.sizePolicy().hasHeightForWidth())
        self.label_input_path.setSizePolicy(sizePolicy)
        self.label_input_path.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_input_path.setWordWrap(True)
        self.label_input_path.setObjectName("label_input_path")
        self.gridLayout.addWidget(self.label_input_path, 0, 0, 1, 1)
        self.button_input_path = QtWidgets.QPushButton(self.group_read_files)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_input_path.sizePolicy().hasHeightForWidth())
        self.button_input_path.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("folder")
        self.button_input_path.setIcon(icon)
        self.button_input_path.setObjectName("button_input_path")
        self.gridLayout.addWidget(self.button_input_path, 0, 2, 1, 1)
        self.input_path = CoqClickableLabel(self.group_read_files)
        self.input_path.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_path.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_path.setObjectName("input_path")
        self.gridLayout.addWidget(self.input_path, 0, 1, 1, 1)
        self.check_use_metafile = QtWidgets.QCheckBox(self.group_read_files)
        self.check_use_metafile.setObjectName("check_use_metafile")
        self.gridLayout.addWidget(self.check_use_metafile, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.layout_nltk = QtWidgets.QHBoxLayout()
        self.layout_nltk.setObjectName("layout_nltk")
        self.use_pos_tagging = QtWidgets.QCheckBox(self.group_read_files)
        self.use_pos_tagging.setText("")
        self.use_pos_tagging.setObjectName("use_pos_tagging")
        self.layout_nltk.addWidget(self.use_pos_tagging)
        self.label_pos_tagging = QtWidgets.QLabel(self.group_read_files)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pos_tagging.sizePolicy().hasHeightForWidth())
        self.label_pos_tagging.setSizePolicy(sizePolicy)
        self.label_pos_tagging.setText("")
        self.label_pos_tagging.setWordWrap(True)
        self.label_pos_tagging.setObjectName("label_pos_tagging")
        self.layout_nltk.addWidget(self.label_pos_tagging)
        self.verticalLayout.addLayout(self.layout_nltk)
        self.widget_ngram = QtWidgets.QWidget(self.group_read_files)
        self.widget_ngram.setObjectName("widget_ngram")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_ngram)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.check_ngram = QtWidgets.QCheckBox(self.widget_ngram)
        self.check_ngram.setText("")
        self.check_ngram.setObjectName("check_ngram")
        self.horizontalLayout_3.addWidget(self.check_ngram)
        self.label_2 = QtWidgets.QLabel(self.widget_ngram)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spin_n = QtWidgets.QSpinBox(self.widget_ngram)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_n.sizePolicy().hasHeightForWidth())
        self.spin_n.setSizePolicy(sizePolicy)
        self.spin_n.setMinimum(2)
        self.spin_n.setProperty("value", 2)
        self.spin_n.setObjectName("spin_n")
        self.horizontalLayout_3.addWidget(self.spin_n)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_ngram_info = CoqInfoLabel(self.widget_ngram)
        self.label_ngram_info.setObjectName("label_ngram_info")
        self.horizontalLayout_3.addWidget(self.label_ngram_info)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout.addWidget(self.widget_ngram)
        self.verticalLayout_3.addWidget(self.group_read_files)
        self.group_only_module = QtWidgets.QGroupBox(self.widget_options)
        self.group_only_module.setCheckable(True)
        self.group_only_module.setChecked(False)
        self.group_only_module.setObjectName("group_only_module")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.group_only_module)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.group_only_module)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_3.addWidget(self.group_only_module)
        self.issue_label = QtWidgets.QLabel(self.widget_options)
        self.issue_label.setObjectName("issue_label")
        self.verticalLayout_3.addWidget(self.issue_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.widget_options)
        self.progress_box = QtWidgets.QFrame(CorpusInstaller)
        self.progress_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_box.setObjectName("progress_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.progress_box)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.progress_box)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.progress_general = QtWidgets.QProgressBar(self.progress_box)
        self.progress_general.setMinimum(0)
        self.progress_general.setMaximum(9)
        self.progress_general.setProperty("value", 0)
        self.progress_general.setObjectName("progress_general")
        self.verticalLayout_2.addWidget(self.progress_general)
        self.progress_bar = QtWidgets.QProgressBar(self.progress_box)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setFormat("")
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_2.addWidget(self.progress_bar)
        self.verticalLayout_4.addWidget(self.progress_box)
        self.buttonBox = QtWidgets.QDialogButtonBox(CorpusInstaller)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.name_label.setBuddy(self.input_path)
        self.label_input_path.setBuddy(self.input_path)

        self.retranslateUi(CorpusInstaller)
        self.buttonBox.rejected.connect(CorpusInstaller.reject)
        QtCore.QMetaObject.connectSlotsByName(CorpusInstaller)

    def retranslateUi(self, CorpusInstaller):
        _translate = QtCore.QCoreApplication.translate
        CorpusInstaller.setWindowTitle(_translate("CorpusInstaller", "Corpus Installer – Coquery"))
        self.name_label.setText(_translate("CorpusInstaller", "&Corpus name:"))
        self.group_read_files.setTitle(_translate("CorpusInstaller", "&Read corpus data files"))
        self.button_metafile.setText(_translate("CorpusInstaller", "Open"))
        self.label_input_path.setText(_translate("CorpusInstaller", "Da&ta file directory:"))
        self.button_input_path.setText(_translate("CorpusInstaller", "Browse"))
        self.button_input_path.setShortcut(_translate("CorpusInstaller", "Alt+B"))
        self.input_path.setText(_translate("CorpusInstaller", "(no path or file selected)"))
        self.check_use_metafile.setText(_translate("CorpusInstaller", "Use &meta data file:"))
        self.label_2.setText(_translate("CorpusInstaller", "&Generate lookup table for multi-item query strings,"))
        self.spin_n.setSuffix(_translate("CorpusInstaller", " items"))
        self.spin_n.setPrefix(_translate("CorpusInstaller", "up to "))
        self.label_ngram_info.setToolTip(_translate("CorpusInstaller", "<html><head/><body><p>A lookup table for multi-item queries is an additional database table. For each token in the corpus, this table also contains information on the <span style=\" font-style:italic;\">n</span> following tokens. Using a lookup table can greatly speed up queries that consist of more than one query item. However, it also greatly increases the disk space required for the corpus database, and it increases the time required to install the corpus.</p><p>Lookup tables are recommended for the larger corpora such as the BNC, COCA, or COHA.</p><p>Note that even if you do not generate a lookup table for multi-item query strings, you can still use query strings that consist of more than one query item, or that are longer than the lookup table. However, in these cases, the query may be relatively slow.</p><p>For a detailed description of multi-token lookup tables, see:</p><p>Davies, Mark. Semantically-based queries with a joint <span style=\" font-style:italic;\">BNC/WordNet</span> database. In Facchinetti, Roberta (ed.). <span style=\" font-style:italic;\">Corpus linguistics 25 years on.</span> 149–168. Amsterdam: Rodopi.</p></body></html>"))
        self.label_ngram_info.setText(_translate("CorpusInstaller", "?"))
        self.group_only_module.setTitle(_translate("CorpusInstaller", "Only install corpus &module"))
        self.label_4.setText(_translate("CorpusInstaller", "Do not read corpus data files (e.g. if using a database server over the network)"))
        self.issue_label.setText(_translate("CorpusInstaller", "TextLabel"))
        self.label.setText(_translate("CorpusInstaller", "Installing..."))
        self.progress_general.setFormat(_translate("CorpusInstaller", "Stage %v of %m"))

from ..classes import CoqClickableLabel, CoqInfoLabel

