# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createUser.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateUser(object):
    def setupUi(self, CreateUser):
        CreateUser.setObjectName("CreateUser")
        CreateUser.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateUser)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(CreateUser)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.new_name = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_name.sizePolicy().hasHeightForWidth())
        self.new_name.setSizePolicy(sizePolicy)
        self.new_name.setClearButtonEnabled(True)
        self.new_name.setObjectName("new_name")
        self.gridLayout_2.addWidget(self.new_name, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.new_password = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_password.sizePolicy().hasHeightForWidth())
        self.new_password.setSizePolicy(sizePolicy)
        self.new_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.new_password.setClearButtonEnabled(True)
        self.new_password.setObjectName("new_password")
        self.gridLayout_2.addWidget(self.new_password, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.new_password_check = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_password_check.sizePolicy().hasHeightForWidth())
        self.new_password_check.setSizePolicy(sizePolicy)
        self.new_password_check.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.new_password_check.setClearButtonEnabled(True)
        self.new_password_check.setObjectName("new_password_check")
        self.gridLayout_2.addWidget(self.new_password_check, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 2)
        self.gridLayout_2.setRowStretch(3, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(CreateUser)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.root_name = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.root_name.sizePolicy().hasHeightForWidth())
        self.root_name.setSizePolicy(sizePolicy)
        self.root_name.setClearButtonEnabled(True)
        self.root_name.setObjectName("root_name")
        self.gridLayout.addWidget(self.root_name, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.root_password = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.root_password.sizePolicy().hasHeightForWidth())
        self.root_password.setSizePolicy(sizePolicy)
        self.root_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.root_password.setClearButtonEnabled(True)
        self.root_password.setObjectName("root_password")
        self.gridLayout.addWidget(self.root_password, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_show_passwords = QtWidgets.QCheckBox(CreateUser)
        self.check_show_passwords.setObjectName("check_show_passwords")
        self.horizontalLayout.addWidget(self.check_show_passwords)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateUser)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(2, 1)
        self.label_5.setBuddy(self.new_name)
        self.label_4.setBuddy(self.new_password)
        self.label_6.setBuddy(self.new_password_check)
        self.label_3.setBuddy(self.root_name)
        self.label_2.setBuddy(self.root_password)

        self.retranslateUi(CreateUser)
        self.buttonBox.accepted.connect(CreateUser.accept)
        self.buttonBox.rejected.connect(CreateUser.reject)
        QtCore.QMetaObject.connectSlotsByName(CreateUser)
        CreateUser.setTabOrder(self.new_name, self.new_password)
        CreateUser.setTabOrder(self.new_password, self.new_password_check)
        CreateUser.setTabOrder(self.new_password_check, self.root_name)
        CreateUser.setTabOrder(self.root_name, self.root_password)
        CreateUser.setTabOrder(self.root_password, self.check_show_passwords)

    def retranslateUi(self, CreateUser):
        _translate = QtCore.QCoreApplication.translate
        CreateUser.setWindowTitle(_translate("CreateUser", "Create a new MySQL user – Coquery"))
        self.label_5.setText(_translate("CreateUser", "&New user name:"))
        self.label_4.setText(_translate("CreateUser", "Pass&word:"))
        self.label_6.setText(_translate("CreateUser", "&Retype:"))
        self.label_7.setText(_translate("CreateUser", "<html><head/><body><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The user will be able to create, query, modify, and delete databases and tables</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The user will <span style=\" font-weight:600;\">not be able</span> to create or modify the privileges of other users </li></ul></body></html>"))
        self.label_3.setText(_translate("CreateUser", "MySQL roo&t user:"))
        self.label_2.setText(_translate("CreateUser", "&MySQL root password:"))
        self.check_show_passwords.setText(_translate("CreateUser", "&Show passwords"))

