# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'namedTableOptions.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from coquery.gui.pyqt_compat import QtCore, QtGui, frameShadow, frameShape

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NamedTableOptions(object):
    def setupUi(self, NamedTableOptions):
        NamedTableOptions.setObjectName(_fromUtf8("NamedTableOptions"))
        NamedTableOptions.resize(640, 480)
        NamedTableOptions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtGui.QVBoxLayout(NamedTableOptions)
        self.verticalLayout_2.setContentsMargins(4, -1, 4, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.OptionsBox = QtGui.QGroupBox(NamedTableOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OptionsBox.sizePolicy().hasHeightForWidth())
        self.OptionsBox.setSizePolicy(sizePolicy)
        self.OptionsBox.setObjectName(_fromUtf8("OptionsBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.OptionsBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_query_column = QtGui.QLabel(self.OptionsBox)
        self.label_query_column.setObjectName(_fromUtf8("label_query_column"))
        self.gridLayout.addWidget(self.label_query_column, 1, 0, 1, 1)
        self.ignore_lines = QtGui.QSpinBox(self.OptionsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ignore_lines.sizePolicy().hasHeightForWidth())
        self.ignore_lines.setSizePolicy(sizePolicy)
        self.ignore_lines.setObjectName(_fromUtf8("ignore_lines"))
        self.gridLayout.addWidget(self.ignore_lines, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.OptionsBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.quote_char = QtGui.QComboBox(self.OptionsBox)
        self.quote_char.setObjectName(_fromUtf8("quote_char"))
        self.gridLayout.addWidget(self.quote_char, 5, 1, 1, 1)
        self.query_column = QtGui.QSpinBox(self.OptionsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_column.sizePolicy().hasHeightForWidth())
        self.query_column.setSizePolicy(sizePolicy)
        self.query_column.setMinimum(1)
        self.query_column.setMaximum(999)
        self.query_column.setObjectName(_fromUtf8("query_column"))
        self.gridLayout.addWidget(self.query_column, 1, 1, 1, 1)
        self.separate_char = QtGui.QComboBox(self.OptionsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.separate_char.sizePolicy().hasHeightForWidth())
        self.separate_char.setSizePolicy(sizePolicy)
        self.separate_char.setEditable(True)
        self.separate_char.setObjectName(_fromUtf8("separate_char"))
        self.separate_char.addItem(_fromUtf8(""))
        self.separate_char.addItem(_fromUtf8(""))
        self.separate_char.addItem(_fromUtf8(""))
        self.separate_char.addItem(_fromUtf8(""))
        self.separate_char.addItem(_fromUtf8(""))
        self.separate_char.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.separate_char, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.OptionsBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.OptionsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.file_has_headers = QtGui.QCheckBox(self.OptionsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_has_headers.sizePolicy().hasHeightForWidth())
        self.file_has_headers.setSizePolicy(sizePolicy)
        self.file_has_headers.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.file_has_headers.setText(_fromUtf8(""))
        self.file_has_headers.setObjectName(_fromUtf8("file_has_headers"))
        self.gridLayout.addWidget(self.file_has_headers, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.OptionsBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.OptionsBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.combo_encoding = QtGui.QComboBox(self.OptionsBox)
        self.combo_encoding.setObjectName(_fromUtf8("combo_encoding"))
        self.gridLayout.addWidget(self.combo_encoding, 6, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.OptionsBox)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox = QtGui.QGroupBox(NamedTableOptions)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, 4, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layout_name_buttons = QtGui.QGridLayout()
        self.layout_name_buttons.setObjectName(_fromUtf8("layout_name_buttons"))
        self.button_word = QtGui.QPushButton(self.groupBox)
        self.button_word.setObjectName(_fromUtf8("button_word"))
        self.layout_name_buttons.addWidget(self.button_word, 0, 0, 1, 1)
        self.edit_word = QtGui.QLineEdit(self.groupBox)
        self.edit_word.setReadOnly(True)
        self.edit_word.setObjectName(_fromUtf8("edit_word"))
        self.layout_name_buttons.addWidget(self.edit_word, 0, 1, 1, 1)
        self.button_lemma = QtGui.QPushButton(self.groupBox)
        self.button_lemma.setObjectName(_fromUtf8("button_lemma"))
        self.layout_name_buttons.addWidget(self.button_lemma, 1, 0, 1, 1)
        self.edit_lemma = QtGui.QLineEdit(self.groupBox)
        self.edit_lemma.setReadOnly(True)
        self.edit_lemma.setObjectName(_fromUtf8("edit_lemma"))
        self.layout_name_buttons.addWidget(self.edit_lemma, 1, 1, 1, 1)
        self.button_pos = QtGui.QPushButton(self.groupBox)
        self.button_pos.setObjectName(_fromUtf8("button_pos"))
        self.layout_name_buttons.addWidget(self.button_pos, 2, 0, 1, 1)
        self.edit_pos = QtGui.QLineEdit(self.groupBox)
        self.edit_pos.setReadOnly(True)
        self.edit_pos.setObjectName(_fromUtf8("edit_pos"))
        self.layout_name_buttons.addWidget(self.edit_pos, 2, 1, 1, 1)
        self.edit_transcript = QtGui.QLineEdit(self.groupBox)
        self.edit_transcript.setReadOnly(True)
        self.edit_transcript.setObjectName(_fromUtf8("edit_transcript"))
        self.layout_name_buttons.addWidget(self.edit_transcript, 3, 1, 1, 1)
        self.edit_gloss = QtGui.QLineEdit(self.groupBox)
        self.edit_gloss.setReadOnly(True)
        self.edit_gloss.setObjectName(_fromUtf8("edit_gloss"))
        self.layout_name_buttons.addWidget(self.edit_gloss, 4, 1, 1, 1)
        self.button_transcript = QtGui.QPushButton(self.groupBox)
        self.button_transcript.setObjectName(_fromUtf8("button_transcript"))
        self.layout_name_buttons.addWidget(self.button_transcript, 3, 0, 1, 1)
        self.button_gloss = QtGui.QPushButton(self.groupBox)
        self.button_gloss.setObjectName(_fromUtf8("button_gloss"))
        self.layout_name_buttons.addWidget(self.button_gloss, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.layout_name_buttons)
        self.verticalLayout_4.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.FilePreviewArea = QtGui.QTableView(NamedTableOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilePreviewArea.sizePolicy().hasHeightForWidth())
        self.FilePreviewArea.setSizePolicy(sizePolicy)
        self.FilePreviewArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.FilePreviewArea.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.FilePreviewArea.setAlternatingRowColors(True)
        self.FilePreviewArea.setSelectionBehavior(QtGui.QAbstractItemView.SelectColumns)
        self.FilePreviewArea.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.FilePreviewArea.setObjectName(_fromUtf8("FilePreviewArea"))
        self.verticalLayout_2.addWidget(self.FilePreviewArea)
        self.buttonBox = QtGui.QDialogButtonBox(NamedTableOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label_query_column.setBuddy(self.query_column)
        self.label_6.setBuddy(self.ignore_lines)
        self.label.setBuddy(self.file_has_headers)
        self.label_10.setBuddy(self.separate_char)
        self.label_2.setBuddy(self.quote_char)
        self.label_3.setBuddy(self.combo_encoding)

        self.retranslateUi(NamedTableOptions)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), NamedTableOptions.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), NamedTableOptions.reject)
        QtCore.QMetaObject.connectSlotsByName(NamedTableOptions)

    def retranslateUi(self, NamedTableOptions):
        NamedTableOptions.setWindowTitle(_translate("NamedTableOptions", "Table options ~ Coquery", None))
        self.OptionsBox.setTitle(_translate("NamedTableOptions", "CSV Options", None))
        self.label_query_column.setText(_translate("NamedTableOptions", "Read &queries from column number:", None))
        self.label_6.setText(_translate("NamedTableOptions", "Text lines to &ignore after header:", None))
        self.separate_char.setItemText(0, _translate("NamedTableOptions", ",", None))
        self.separate_char.setItemText(1, _translate("NamedTableOptions", ";", None))
        self.separate_char.setItemText(2, _translate("NamedTableOptions", ":", None))
        self.separate_char.setItemText(3, _translate("NamedTableOptions", "#", None))
        self.separate_char.setItemText(4, _translate("NamedTableOptions", "{tab}", None))
        self.separate_char.setItemText(5, _translate("NamedTableOptions", "{space}", None))
        self.label.setText(_translate("NamedTableOptions", "File contains &header:", None))
        self.label_10.setText(_translate("NamedTableOptions", "Character that &separates columns:", None))
        self.label_2.setText(_translate("NamedTableOptions", "&Quote character:", None))
        self.label_3.setText(_translate("NamedTableOptions", "Character &encoding:", None))
        self.groupBox.setTitle(_translate("NamedTableOptions", "Query type mappings", None))
        self.button_word.setText(_translate("NamedTableOptions", "Word", None))
        self.button_lemma.setText(_translate("NamedTableOptions", "Lemma", None))
        self.button_pos.setText(_translate("NamedTableOptions", "POS", None))
        self.button_transcript.setText(_translate("NamedTableOptions", "Transcript", None))
        self.button_gloss.setText(_translate("NamedTableOptions", "Gloss", None))


