# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'readPackage.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PackageInstaller(object):
    def setupUi(self, PackageInstaller):
        PackageInstaller.setObjectName("PackageInstaller")
        PackageInstaller.resize(687, 513)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PackageInstaller.sizePolicy().hasHeightForWidth())
        PackageInstaller.setSizePolicy(sizePolicy)
        PackageInstaller.setModal(True)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(PackageInstaller)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_input_path = QtWidgets.QLabel(PackageInstaller)
        self.label_input_path.setObjectName("label_input_path")
        self.horizontalLayout_3.addWidget(self.label_input_path)
        self.input_path = CoqClickableLabel(PackageInstaller)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_path.sizePolicy().hasHeightForWidth())
        self.input_path.setSizePolicy(sizePolicy)
        self.input_path.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_path.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_path.setObjectName("input_path")
        self.horizontalLayout_3.addWidget(self.input_path)
        self.button_input_path = QtWidgets.QPushButton(PackageInstaller)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_input_path.sizePolicy().hasHeightForWidth())
        self.button_input_path.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("folder")
        self.button_input_path.setIcon(icon)
        self.button_input_path.setObjectName("button_input_path")
        self.horizontalLayout_3.addWidget(self.button_input_path)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.group_options = QtWidgets.QGroupBox(PackageInstaller)
        self.group_options.setObjectName("group_options")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_options)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(self.group_options)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.corpus_name = QtWidgets.QLineEdit(self.group_options)
        self.corpus_name.setMaxLength(32)
        self.corpus_name.setObjectName("corpus_name")
        self.horizontalLayout.addWidget(self.corpus_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.text_license = QtWidgets.QTextEdit(self.group_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_license.sizePolicy().hasHeightForWidth())
        self.text_license.setSizePolicy(sizePolicy)
        self.text_license.setReadOnly(True)
        self.text_license.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.text_license.setObjectName("text_license")
        self.verticalLayout.addWidget(self.text_license)
        self.radio_read_files = QtWidgets.QRadioButton(self.group_options)
        self.radio_read_files.setChecked(True)
        self.radio_read_files.setObjectName("radio_read_files")
        self.verticalLayout.addWidget(self.radio_read_files)
        self.radio_only_module = QtWidgets.QRadioButton(self.group_options)
        self.radio_only_module.setObjectName("radio_only_module")
        self.verticalLayout.addWidget(self.radio_only_module)
        self.verticalLayout_4.addWidget(self.group_options)
        self.issue_label = QtWidgets.QLabel(PackageInstaller)
        self.issue_label.setObjectName("issue_label")
        self.verticalLayout_4.addWidget(self.issue_label)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.progress_box = QtWidgets.QFrame(PackageInstaller)
        self.progress_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_box.setObjectName("progress_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.progress_box)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.progress_box)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.progress_general = QtWidgets.QProgressBar(self.progress_box)
        self.progress_general.setMinimum(0)
        self.progress_general.setMaximum(9)
        self.progress_general.setProperty("value", 0)
        self.progress_general.setObjectName("progress_general")
        self.verticalLayout_2.addWidget(self.progress_general)
        self.progress_bar = QtWidgets.QProgressBar(self.progress_box)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setFormat("")
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_2.addWidget(self.progress_bar)
        self.verticalLayout_4.addWidget(self.progress_box)
        self.buttonBox = QtWidgets.QDialogButtonBox(PackageInstaller)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.label_input_path.setBuddy(self.input_path)
        self.name_label.setBuddy(self.corpus_name)

        self.retranslateUi(PackageInstaller)
        self.buttonBox.rejected.connect(PackageInstaller.reject)
        QtCore.QMetaObject.connectSlotsByName(PackageInstaller)

    def retranslateUi(self, PackageInstaller):
        _translate = QtCore.QCoreApplication.translate
        PackageInstaller.setWindowTitle(_translate("PackageInstaller", "Package installer – Coquery"))
        self.label_input_path.setText(_translate("PackageInstaller", "&Package:"))
        self.input_path.setText(_translate("PackageInstaller", "(no path or file selected)"))
        self.button_input_path.setText(_translate("PackageInstaller", "&Browse"))
        self.button_input_path.setShortcut(_translate("PackageInstaller", "Alt+B"))
        self.name_label.setText(_translate("PackageInstaller", "&Corpus name:"))
        self.radio_read_files.setText(_translate("PackageInstaller", "&Read corpus from package"))
        self.radio_only_module.setText(_translate("PackageInstaller", "Only install corpus &module"))
        self.issue_label.setText(_translate("PackageInstaller", "TextLabel"))
        self.label.setText(_translate("PackageInstaller", "Reading package..."))
        self.progress_general.setFormat(_translate("PackageInstaller", "Stage %v of %m"))

from ..classes import CoqClickableLabel

