# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from pyqt_compat import QtCore, QtGui, frameShadow, frameShape

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName(_fromUtf8("SettingsDialog"))
        SettingsDialog.resize(667, 737)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtGui.QVBoxLayout(SettingsDialog)
        self.verticalLayout_3.setContentsMargins(4, -1, 4, -1)
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame = QtGui.QFrame(SettingsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(frameShape)
        self.frame.setFrameShadow(frameShadow)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(8, 6, 8, 6)
        self.verticalLayout_5.setSpacing(16)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setContentsMargins(8, 6, 8, 6)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.check_reaggregate_data = QtGui.QCheckBox(self.groupBox)
        self.check_reaggregate_data.setObjectName(_fromUtf8("check_reaggregate_data"))
        self.verticalLayout.addWidget(self.check_reaggregate_data)
        self.check_server_side = QtGui.QCheckBox(self.groupBox)
        self.check_server_side.setObjectName(_fromUtf8("check_server_side"))
        self.verticalLayout.addWidget(self.check_server_side)
        self.check_ignore_punctuation = QtGui.QCheckBox(self.groupBox)
        self.check_ignore_punctuation.setObjectName(_fromUtf8("check_ignore_punctuation"))
        self.verticalLayout.addWidget(self.check_ignore_punctuation)
        self.check_experimental = QtGui.QCheckBox(self.groupBox)
        self.check_experimental.setObjectName(_fromUtf8("check_experimental"))
        self.verticalLayout.addWidget(self.check_experimental)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox1 = QtGui.QGroupBox(self.frame)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox1)
        self.horizontalLayout_4.setContentsMargins(8, 6, 8, 6)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.spin_digits = QtGui.QSpinBox(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_digits.sizePolicy().hasHeightForWidth())
        self.spin_digits.setSizePolicy(sizePolicy)
        self.spin_digits.setProperty("value", 3)
        self.spin_digits.setObjectName(_fromUtf8("spin_digits"))
        self.horizontalLayout.addWidget(self.spin_digits)
        self.label_3 = QtGui.QLabel(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.check_ignore_case = QtGui.QCheckBox(self.groupBox1)
        self.check_ignore_case.setObjectName(_fromUtf8("check_ignore_case"))
        self.verticalLayout_4.addWidget(self.check_ignore_case)
        self.check_align_quantified = QtGui.QCheckBox(self.groupBox1)
        self.check_align_quantified.setObjectName(_fromUtf8("check_align_quantified"))
        self.verticalLayout_4.addWidget(self.check_align_quantified)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.groupBox1)
        self.groupBox2 = QtGui.QGroupBox(self.frame)
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox2)
        self.horizontalLayout_3.setContentsMargins(8, 6, 8, 6)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame_addon_paths = QtGui.QFrame(self.groupBox2)
        self.frame_addon_paths.setObjectName(_fromUtf8("frame_addon_paths"))
        self.gridLayout = QtGui.QGridLayout(self.frame_addon_paths)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.button_visualizer_path = QtGui.QPushButton(self.frame_addon_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_visualizer_path.sizePolicy().hasHeightForWidth())
        self.button_visualizer_path.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("folder"))
        self.button_visualizer_path.setIcon(icon)
        self.button_visualizer_path.setObjectName(_fromUtf8("button_visualizer_path"))
        self.gridLayout.addWidget(self.button_visualizer_path, 1, 2, 1, 1)
        self.edit_installer_path = QtGui.QLineEdit(self.frame_addon_paths)
        self.edit_installer_path.setObjectName(_fromUtf8("edit_installer_path"))
        self.gridLayout.addWidget(self.edit_installer_path, 0, 1, 1, 1)
        self.button_installer_path = QtGui.QPushButton(self.frame_addon_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_installer_path.sizePolicy().hasHeightForWidth())
        self.button_installer_path.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("folder"))
        self.button_installer_path.setIcon(icon)
        self.button_installer_path.setObjectName(_fromUtf8("button_installer_path"))
        self.gridLayout.addWidget(self.button_installer_path, 0, 2, 1, 1)
        self.edit_visualizer_path = QtGui.QLineEdit(self.frame_addon_paths)
        self.edit_visualizer_path.setObjectName(_fromUtf8("edit_visualizer_path"))
        self.gridLayout.addWidget(self.edit_visualizer_path, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_addon_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_addon_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_addon_paths)
        self.verticalLayout_5.addWidget(self.groupBox2)
        self.groupBox3 = QtGui.QGroupBox(self.frame)
        self.groupBox3.setObjectName(_fromUtf8("groupBox3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox3)
        self.horizontalLayout_2.setContentsMargins(8, 6, 8, 6)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.check_ask_on_quit = QtGui.QCheckBox(self.groupBox3)
        self.check_ask_on_quit.setObjectName(_fromUtf8("check_ask_on_quit"))
        self.verticalLayout_2.addWidget(self.check_ask_on_quit)
        self.check_save_query_string = QtGui.QCheckBox(self.groupBox3)
        self.check_save_query_string.setObjectName(_fromUtf8("check_save_query_string"))
        self.verticalLayout_2.addWidget(self.check_save_query_string)
        self.check_save_query_file = QtGui.QCheckBox(self.groupBox3)
        self.check_save_query_file.setObjectName(_fromUtf8("check_save_query_file"))
        self.verticalLayout_2.addWidget(self.check_save_query_file)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox3)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.label.setBuddy(self.spin_digits)
        self.label_9.setBuddy(self.edit_visualizer_path)
        self.label_2.setBuddy(self.edit_installer_path)

        self.retranslateUi(SettingsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings – Coquery", None))
        self.groupBox.setTitle(_translate("SettingsDialog", "Query options", None))
        self.check_reaggregate_data.setText(_translate("SettingsDialog", "&Reaggregate data when toggling column visibility", None))
        self.check_server_side.setText(_translate("SettingsDialog", "Retrieve results from server one by one  (somewhat slower, but uses less memory)", None))
        self.check_ignore_punctuation.setText(_translate("SettingsDialog", "Ignore &punctuation in contexts", None))
        self.check_experimental.setText(_translate("SettingsDialog", "Use &experimental features (MAY BE UNSTABLE!)", None))
        self.groupBox1.setTitle(_translate("SettingsDialog", "Output options", None))
        self.label.setText(_translate("SettingsDialog", "&Display ", None))
        self.spin_digits.setSuffix(_translate("SettingsDialog", " digit(s)", None))
        self.label_3.setText(_translate("SettingsDialog", "after decimal point", None))
        self.check_ignore_case.setText(_translate("SettingsDialog", "Ignore &case", None))
        self.check_align_quantified.setText(_translate("SettingsDialog", "Align &quantified token columns", None))
        self.groupBox2.setTitle(_translate("SettingsDialog", "Additional paths", None))
        self.button_visualizer_path.setText(_translate("SettingsDialog", "B&rowse", None))
        self.button_visualizer_path.setShortcut(_translate("SettingsDialog", "Alt+B", None))
        self.button_installer_path.setText(_translate("SettingsDialog", "&Browse", None))
        self.button_installer_path.setShortcut(_translate("SettingsDialog", "Alt+B", None))
        self.label_9.setText(_translate("SettingsDialog", "&Visualizers:", None))
        self.label_2.setText(_translate("SettingsDialog", "Corpus &installers: ", None))
        self.groupBox3.setTitle(_translate("SettingsDialog", "Exit options", None))
        self.check_ask_on_quit.setText(_translate("SettingsDialog", "Ask if &unsaved results should be saved upon exit", None))
        self.check_save_query_string.setText(_translate("SettingsDialog", "Save last query &string in configuration file", None))
        self.check_save_query_file.setText(_translate("SettingsDialog", "Save last query &file in configuration file", None))


