# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textgridExport.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from coquery.gui.pyqt_compat import QtCore, QtGui, frameShadow, frameShape

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TextgridExport(object):
    def setupUi(self, TextgridExport):
        TextgridExport.setObjectName(_fromUtf8("TextgridExport"))
        TextgridExport.resize(640, 480)
        self.verticalLayout_3 = QtGui.QVBoxLayout(TextgridExport)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(TextgridExport)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.edit_output_path = QtGui.QLineEdit(TextgridExport)
        self.edit_output_path.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_output_path.sizePolicy().hasHeightForWidth())
        self.edit_output_path.setSizePolicy(sizePolicy)
        self.edit_output_path.setAccessibleDescription(_fromUtf8(""))
        self.edit_output_path.setObjectName(_fromUtf8("edit_output_path"))
        self.horizontalLayout.addWidget(self.edit_output_path)
        self.button_output_path = QtGui.QPushButton(TextgridExport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_output_path.sizePolicy().hasHeightForWidth())
        self.button_output_path.setSizePolicy(sizePolicy)
        self.button_output_path.setObjectName(_fromUtf8("button_output_path"))
        self.horizontalLayout.addWidget(self.button_output_path)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox = QtGui.QGroupBox(TextgridExport)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.list_columns = QtGui.QListWidget(self.groupBox)
        self.list_columns.setObjectName(_fromUtf8("list_columns"))
        self.verticalLayout.addWidget(self.list_columns)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox1 = QtGui.QGroupBox(TextgridExport)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radio_one_per_match = QtGui.QRadioButton(self.groupBox1)
        self.radio_one_per_match.setObjectName(_fromUtf8("radio_one_per_match"))
        self.verticalLayout_2.addWidget(self.radio_one_per_match)
        self.radio_one_per_file = QtGui.QRadioButton(self.groupBox1)
        self.radio_one_per_file.setObjectName(_fromUtf8("radio_one_per_file"))
        self.verticalLayout_2.addWidget(self.radio_one_per_file)
        self.verticalLayout_3.addWidget(self.groupBox1)
        self.groupBox2 = QtGui.QGroupBox(TextgridExport)
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.check_copy_sounds = QtGui.QCheckBox(self.groupBox2)
        self.check_copy_sounds.setText(_fromUtf8(""))
        self.check_copy_sounds.setObjectName(_fromUtf8("check_copy_sounds"))
        self.gridLayout.addWidget(self.check_copy_sounds, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.spin_left_padding = QtGui.QDoubleSpinBox(self.groupBox2)
        self.spin_left_padding.setDecimals(3)
        self.spin_left_padding.setMaximum(999.999)
        self.spin_left_padding.setSingleStep(0.1)
        self.spin_left_padding.setObjectName(_fromUtf8("spin_left_padding"))
        self.horizontalLayout_3.addWidget(self.spin_left_padding)
        self.label_5 = QtGui.QLabel(self.groupBox2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.spin_right_padding = QtGui.QDoubleSpinBox(self.groupBox2)
        self.spin_right_padding.setDecimals(3)
        self.spin_right_padding.setMaximum(999.999)
        self.spin_right_padding.setSingleStep(0.1)
        self.spin_right_padding.setObjectName(_fromUtf8("spin_right_padding"))
        self.horizontalLayout_3.addWidget(self.spin_right_padding)
        self.label_6 = QtGui.QLabel(self.groupBox2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.edit_sound_path = QtGui.QLineEdit(self.groupBox2)
        self.edit_sound_path.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_sound_path.sizePolicy().hasHeightForWidth())
        self.edit_sound_path.setSizePolicy(sizePolicy)
        self.edit_sound_path.setAccessibleDescription(_fromUtf8(""))
        self.edit_sound_path.setObjectName(_fromUtf8("edit_sound_path"))
        self.horizontalLayout_2.addWidget(self.edit_sound_path)
        self.button_sound_path = QtGui.QPushButton(self.groupBox2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_sound_path.sizePolicy().hasHeightForWidth())
        self.button_sound_path.setSizePolicy(sizePolicy)
        self.button_sound_path.setObjectName(_fromUtf8("button_sound_path"))
        self.horizontalLayout_2.addWidget(self.button_sound_path)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.check_remember = QtGui.QCheckBox(self.groupBox2)
        self.check_remember.setObjectName(_fromUtf8("check_remember"))
        self.gridLayout.addWidget(self.check_remember, 3, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox2)
        self.buttonBox = QtGui.QDialogButtonBox(TextgridExport)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.label.setBuddy(self.edit_output_path)
        self.label_4.setBuddy(self.check_copy_sounds)
        self.label_5.setBuddy(self.spin_left_padding)
        self.label_6.setBuddy(self.spin_right_padding)
        self.label_3.setBuddy(self.edit_sound_path)

        self.retranslateUi(TextgridExport)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TextgridExport.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TextgridExport.accept)
        QtCore.QMetaObject.connectSlotsByName(TextgridExport)

    def retranslateUi(self, TextgridExport):
        TextgridExport.setWindowTitle(_translate("TextgridExport", "Export to text grids – Coquery", None))
        self.label.setText(_translate("TextgridExport", "&Output path:", None))
        self.edit_output_path.setPlaceholderText(_translate("TextgridExport", "Input path name", None))
        self.button_output_path.setText(_translate("TextgridExport", "&Browse", None))
        self.button_output_path.setShortcut(_translate("TextgridExport", "Alt+B", None))
        self.groupBox.setTitle(_translate("TextgridExport", "Column selection", None))
        self.groupBox1.setTitle(_translate("TextgridExport", "Text grid creation", None))
        self.radio_one_per_match.setText(_translate("TextgridExport", "Create one text grid for each &match", None))
        self.radio_one_per_file.setText(_translate("TextgridExport", "Create one &text grid for each source file", None))
        self.groupBox2.setTitle(_translate("TextgridExport", "Copy sound files", None))
        self.label_4.setText(_translate("TextgridExport", "&Copy matching sound files to output path", None))
        self.label_2.setText(_translate("TextgridExport", "Include audio context:", None))
        self.spin_left_padding.setSuffix(_translate("TextgridExport", " seconds", None))
        self.label_5.setText(_translate("TextgridExport", "&before", None))
        self.spin_right_padding.setSuffix(_translate("TextgridExport", " seconds", None))
        self.label_6.setText(_translate("TextgridExport", "&after", None))
        self.label_3.setText(_translate("TextgridExport", "&Sound file path:", None))
        self.edit_sound_path.setPlaceholderText(_translate("TextgridExport", "Input path name", None))
        self.button_sound_path.setText(_translate("TextgridExport", "&Browse", None))
        self.button_sound_path.setShortcut(_translate("TextgridExport", "Alt+B", None))
        self.check_remember.setText(_translate("TextgridExport", "&Remember original time in a point tier", None))


