# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textgridExport.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from coquery.gui.pyqt_compat import QtCore, QtGui, frameShadow, frameShape

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TextgridExport(object):
    def setupUi(self, TextgridExport):
        TextgridExport.setObjectName(_fromUtf8("TextgridExport"))
        TextgridExport.resize(640, 480)
        self.verticalLayout = QtGui.QVBoxLayout(TextgridExport)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(TextgridExport)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edit_output_path = QtGui.QLineEdit(self.groupBox)
        self.edit_output_path.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_output_path.sizePolicy().hasHeightForWidth())
        self.edit_output_path.setSizePolicy(sizePolicy)
        self.edit_output_path.setAccessibleDescription(_fromUtf8(""))
        self.edit_output_path.setObjectName(_fromUtf8("edit_output_path"))
        self.gridLayout.addWidget(self.edit_output_path, 0, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.button_output_path = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_output_path.sizePolicy().hasHeightForWidth())
        self.button_output_path.setSizePolicy(sizePolicy)
        self.button_output_path.setObjectName(_fromUtf8("button_output_path"))
        self.gridLayout.addWidget(self.button_output_path, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edit_file_prefix = QtGui.QLineEdit(self.groupBox)
        self.edit_file_prefix.setObjectName(_fromUtf8("edit_file_prefix"))
        self.horizontalLayout_4.addWidget(self.edit_file_prefix)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget = QtGui.QTabWidget(TextgridExport)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_5.addWidget(self.label_8)
        self.list_columns = CoqListSelect(self.tab)
        self.list_columns.setObjectName(_fromUtf8("list_columns"))
        self.verticalLayout_5.addWidget(self.list_columns)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.radio_one_per_match = QtGui.QRadioButton(self.tab_2)
        self.radio_one_per_match.setObjectName(_fromUtf8("radio_one_per_match"))
        self.verticalLayout_6.addWidget(self.radio_one_per_match)
        self.radio_one_per_file = QtGui.QRadioButton(self.tab_2)
        self.radio_one_per_file.setObjectName(_fromUtf8("radio_one_per_file"))
        self.verticalLayout_6.addWidget(self.radio_one_per_file)
        self.line = QtGui.QFrame(self.tab_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.check_remember = QtGui.QCheckBox(self.tab_2)
        self.check_remember.setObjectName(_fromUtf8("check_remember"))
        self.verticalLayout_6.addWidget(self.check_remember)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.check_copy_sounds = QtGui.QCheckBox(self.tab_3)
        self.check_copy_sounds.setText(_fromUtf8(""))
        self.check_copy_sounds.setObjectName(_fromUtf8("check_copy_sounds"))
        self.gridLayout_3.addWidget(self.check_copy_sounds, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.edit_sound_path = QtGui.QLineEdit(self.tab_3)
        self.edit_sound_path.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_sound_path.sizePolicy().hasHeightForWidth())
        self.edit_sound_path.setSizePolicy(sizePolicy)
        self.edit_sound_path.setAccessibleDescription(_fromUtf8(""))
        self.edit_sound_path.setObjectName(_fromUtf8("edit_sound_path"))
        self.horizontalLayout_2.addWidget(self.edit_sound_path)
        self.button_sound_path = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_sound_path.sizePolicy().hasHeightForWidth())
        self.button_sound_path.setSizePolicy(sizePolicy)
        self.button_sound_path.setObjectName(_fromUtf8("button_sound_path"))
        self.horizontalLayout_2.addWidget(self.button_sound_path)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.groupbox = QtGui.QGroupBox(self.tab_3)
        self.groupbox.setObjectName(_fromUtf8("groupbox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupbox)
        self.gridLayout_4.setMargin(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.groupbox)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupbox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 1, 1, 1)
        self.spin_left_padding = QtGui.QDoubleSpinBox(self.groupbox)
        self.spin_left_padding.setDecimals(3)
        self.spin_left_padding.setMaximum(999.999)
        self.spin_left_padding.setSingleStep(0.1)
        self.spin_left_padding.setObjectName(_fromUtf8("spin_left_padding"))
        self.gridLayout_4.addWidget(self.spin_left_padding, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupbox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 4, 1, 1)
        self.spin_right_padding = QtGui.QDoubleSpinBox(self.groupbox)
        self.spin_right_padding.setDecimals(3)
        self.spin_right_padding.setMaximum(999.999)
        self.spin_right_padding.setSingleStep(0.1)
        self.spin_right_padding.setObjectName(_fromUtf8("spin_right_padding"))
        self.gridLayout_4.addWidget(self.spin_right_padding, 0, 5, 1, 1)
        self.gridLayout_3.addWidget(self.groupbox, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(TextgridExport)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_7.setBuddy(self.edit_file_prefix)
        self.label.setBuddy(self.edit_output_path)
        self.label_4.setBuddy(self.check_copy_sounds)
        self.label_5.setBuddy(self.spin_left_padding)
        self.label_6.setBuddy(self.spin_right_padding)

        self.retranslateUi(TextgridExport)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TextgridExport.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TextgridExport.accept)
        QtCore.QMetaObject.connectSlotsByName(TextgridExport)

    def retranslateUi(self, TextgridExport):
        TextgridExport.setWindowTitle(_translate("TextgridExport", "Export to text grids – Coquery", None))
        self.groupBox.setTitle(_translate("TextgridExport", "Save as text grid files", None))
        self.edit_output_path.setPlaceholderText(_translate("TextgridExport", "Input path name", None))
        self.label_7.setText(_translate("TextgridExport", "Fi&le prefix:", None))
        self.button_output_path.setText(_translate("TextgridExport", "&Browse", None))
        self.button_output_path.setShortcut(_translate("TextgridExport", "Alt+B", None))
        self.label.setText(_translate("TextgridExport", "&Output path:", None))
        self.label_8.setText(_translate("TextgridExport", "Select the columns that will be included as tiers in the text grids.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TextgridExport", "&Columns", None))
        self.radio_one_per_match.setText(_translate("TextgridExport", "Create one text grid for each &match", None))
        self.radio_one_per_file.setText(_translate("TextgridExport", "Create one &text grid for each source file", None))
        self.check_remember.setText(_translate("TextgridExport", "&Remember original time in a point tier", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TextgridExport", "Text &grids", None))
        self.edit_sound_path.setPlaceholderText(_translate("TextgridExport", "Input path name", None))
        self.button_sound_path.setText(_translate("TextgridExport", "&Browse", None))
        self.button_sound_path.setShortcut(_translate("TextgridExport", "Alt+B", None))
        self.label_4.setText(_translate("TextgridExport", "&Copy matching sound files to output path:", None))
        self.groupbox.setTitle(_translate("TextgridExport", "Add audio context", None))
        self.label_5.setText(_translate("TextgridExport", "&Before:", None))
        self.spin_left_padding.setSuffix(_translate("TextgridExport", " seconds", None))
        self.label_6.setText(_translate("TextgridExport", "&After:", None))
        self.spin_right_padding.setSuffix(_translate("TextgridExport", " seconds", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("TextgridExport", "&Sound files", None))

from ..listselect import CoqListSelect

