# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualizationDesigner.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from coquery.gui.pyqt_compat import QtCore, QtGui, frameShadow, frameShape

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_VisualizationDesigner(object):
    def setupUi(self, VisualizationDesigner):
        VisualizationDesigner.setObjectName(_fromUtf8("VisualizationDesigner"))
        VisualizationDesigner.resize(800, 600)
        self.verticalLayout_12 = QtGui.QVBoxLayout(VisualizationDesigner)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.tab_widget = QtGui.QTabWidget(VisualizationDesigner)
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.tab_layout = QtGui.QWidget()
        self.tab_layout.setObjectName(_fromUtf8("tab_layout"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_layout)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.group_variables = QtGui.QGroupBox(self.tab_layout)
        self.group_variables.setObjectName(_fromUtf8("group_variables"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.group_variables)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.group_variables)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.table_categorical = CoqFeatureList(self.group_variables)
        self.table_categorical.setAlternatingRowColors(True)
        self.table_categorical.setObjectName(_fromUtf8("table_categorical"))
        self.verticalLayout_2.addWidget(self.table_categorical)
        self.label_5 = QtGui.QLabel(self.group_variables)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.table_numerical = CoqFeatureList(self.group_variables)
        self.table_numerical.setAlternatingRowColors(True)
        self.table_numerical.setObjectName(_fromUtf8("table_numerical"))
        self.verticalLayout_2.addWidget(self.table_numerical)
        self.horizontalLayout.addWidget(self.group_variables)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.group_data = QtGui.QGroupBox(self.tab_layout)
        self.group_data.setObjectName(_fromUtf8("group_data"))
        self.gridLayout_3 = QtGui.QGridLayout(self.group_data)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radio_horizontal = QtGui.QRadioButton(self.group_data)
        self.radio_horizontal.setText(_fromUtf8(""))
        self.radio_horizontal.setObjectName(_fromUtf8("radio_horizontal"))
        self.gridLayout_3.addWidget(self.radio_horizontal, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.group_data)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.tray_data_x = CoqFeatureTray(self.group_data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tray_data_x.sizePolicy().hasHeightForWidth())
        self.tray_data_x.setSizePolicy(sizePolicy)
        self.tray_data_x.setObjectName(_fromUtf8("tray_data_x"))
        self.gridLayout_3.addWidget(self.tray_data_x, 0, 2, 1, 1)
        self.button_clear_x = QtGui.QToolButton(self.group_data)
        self.button_clear_x.setText(_fromUtf8(""))
        self.button_clear_x.setObjectName(_fromUtf8("button_clear_x"))
        self.gridLayout_3.addWidget(self.button_clear_x, 0, 3, 1, 1, QtCore.Qt.AlignVCenter)
        self.radio_vertical = QtGui.QRadioButton(self.group_data)
        self.radio_vertical.setText(_fromUtf8(""))
        self.radio_vertical.setObjectName(_fromUtf8("radio_vertical"))
        self.gridLayout_3.addWidget(self.radio_vertical, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.group_data)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 1, 1, 1)
        self.tray_data_y = CoqFeatureTray(self.group_data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tray_data_y.sizePolicy().hasHeightForWidth())
        self.tray_data_y.setSizePolicy(sizePolicy)
        self.tray_data_y.setObjectName(_fromUtf8("tray_data_y"))
        self.gridLayout_3.addWidget(self.tray_data_y, 1, 2, 1, 1)
        self.button_clear_y = QtGui.QToolButton(self.group_data)
        self.button_clear_y.setText(_fromUtf8(""))
        self.button_clear_y.setObjectName(_fromUtf8("button_clear_y"))
        self.gridLayout_3.addWidget(self.button_clear_y, 1, 3, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_8 = QtGui.QLabel(self.group_data)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 1, 1, 1)
        self.tray_data_z = CoqFeatureTray(self.group_data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tray_data_z.sizePolicy().hasHeightForWidth())
        self.tray_data_z.setSizePolicy(sizePolicy)
        self.tray_data_z.setObjectName(_fromUtf8("tray_data_z"))
        self.gridLayout_3.addWidget(self.tray_data_z, 2, 2, 1, 1)
        self.button_clear_z = QtGui.QToolButton(self.group_data)
        self.button_clear_z.setText(_fromUtf8(""))
        self.button_clear_z.setObjectName(_fromUtf8("button_clear_z"))
        self.gridLayout_3.addWidget(self.button_clear_z, 2, 3, 1, 1, QtCore.Qt.AlignVCenter)
        self.verticalLayout_6.addWidget(self.group_data)
        self.group_layout = QtGui.QGroupBox(self.tab_layout)
        self.group_layout.setObjectName(_fromUtf8("group_layout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.group_layout)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_rows = QtGui.QLabel(self.group_layout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rows.sizePolicy().hasHeightForWidth())
        self.label_rows.setSizePolicy(sizePolicy)
        self.label_rows.setObjectName(_fromUtf8("label_rows"))
        self.gridLayout.addWidget(self.label_rows, 0, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(13, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.button_clear_columns = QtGui.QToolButton(self.group_layout)
        self.button_clear_columns.setText(_fromUtf8(""))
        self.button_clear_columns.setObjectName(_fromUtf8("button_clear_columns"))
        self.gridLayout.addWidget(self.button_clear_columns, 2, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(13, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(13, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(14, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 3, 1, 1)
        self.button_columns = QtGui.QToolButton(self.group_layout)
        self.button_columns.setText(_fromUtf8(""))
        self.button_columns.setObjectName(_fromUtf8("button_columns"))
        self.gridLayout.addWidget(self.button_columns, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        self.button_rows = QtGui.QToolButton(self.group_layout)
        self.button_rows.setText(_fromUtf8(""))
        self.button_rows.setObjectName(_fromUtf8("button_rows"))
        self.gridLayout.addWidget(self.button_rows, 2, 4, 1, 1)
        self.tray_rows = CoqFeatureTray(self.group_layout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tray_rows.sizePolicy().hasHeightForWidth())
        self.tray_rows.setSizePolicy(sizePolicy)
        self.tray_rows.setObjectName(_fromUtf8("tray_rows"))
        self.gridLayout.addWidget(self.tray_rows, 1, 5, 3, 1)
        spacerItem6 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 1, 6, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 1, 4, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(13, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 3, 6, 1, 1)
        self.button_clear_rows = QtGui.QToolButton(self.group_layout)
        self.button_clear_rows.setText(_fromUtf8(""))
        self.button_clear_rows.setObjectName(_fromUtf8("button_clear_rows"))
        self.gridLayout.addWidget(self.button_clear_rows, 2, 6, 1, 1)
        self.tray_columns = CoqFeatureTray(self.group_layout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tray_columns.sizePolicy().hasHeightForWidth())
        self.tray_columns.setSizePolicy(sizePolicy)
        self.tray_columns.setObjectName(_fromUtf8("tray_columns"))
        self.gridLayout.addWidget(self.tray_columns, 1, 1, 3, 1)
        self.label_columns = QtGui.QLabel(self.group_layout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_columns.sizePolicy().hasHeightForWidth())
        self.label_columns.setSizePolicy(sizePolicy)
        self.label_columns.setObjectName(_fromUtf8("label_columns"))
        self.gridLayout.addWidget(self.label_columns, 0, 1, 1, 1)
        self.check_wrap_layout = QtGui.QCheckBox(self.group_layout)
        self.check_wrap_layout.setChecked(True)
        self.check_wrap_layout.setObjectName(_fromUtf8("check_wrap_layout"))
        self.gridLayout.addWidget(self.check_wrap_layout, 4, 1, 1, 2)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_6.addWidget(self.group_layout)
        self.group_legend = QtGui.QGroupBox(self.tab_layout)
        self.group_legend.setObjectName(_fromUtf8("group_legend"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.group_legend)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.check_show_legend = QtGui.QCheckBox(self.group_legend)
        self.check_show_legend.setChecked(True)
        self.check_show_legend.setObjectName(_fromUtf8("check_show_legend"))
        self.horizontalLayout_4.addWidget(self.check_show_legend)
        spacerItem9 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.label_13 = QtGui.QLabel(self.group_legend)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_4.addWidget(self.label_13)
        self.spin_columns = QtGui.QSpinBox(self.group_legend)
        self.spin_columns.setMinimum(1)
        self.spin_columns.setMaximum(9)
        self.spin_columns.setProperty("value", 1)
        self.spin_columns.setObjectName(_fromUtf8("spin_columns"))
        self.horizontalLayout_4.addWidget(self.spin_columns)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addWidget(self.group_legend)
        self.group_preview = QtGui.QGroupBox(self.tab_layout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_preview.sizePolicy().hasHeightForWidth())
        self.group_preview.setSizePolicy(sizePolicy)
        self.group_preview.setObjectName(_fromUtf8("group_preview"))
        self.layout_preview = QtGui.QVBoxLayout(self.group_preview)
        self.layout_preview.setMargin(0)
        self.layout_preview.setObjectName(_fromUtf8("layout_preview"))
        self.verticalLayout_6.addWidget(self.group_preview)
        self.verticalLayout_6.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.group_figures = QtGui.QGroupBox(self.tab_layout)
        self.group_figures.setObjectName(_fromUtf8("group_figures"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.group_figures)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.list_figures = QtGui.QListWidget(self.group_figures)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_figures.sizePolicy().hasHeightForWidth())
        self.list_figures.setSizePolicy(sizePolicy)
        self.list_figures.setMinimumSize(QtCore.QSize(200, 0))
        self.list_figures.setMaximumSize(QtCore.QSize(200, 16777215))
        self.list_figures.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_figures.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.list_figures.setProperty("showDropIndicator", False)
        self.list_figures.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.list_figures.setViewMode(QtGui.QListView.IconMode)
        self.list_figures.setObjectName(_fromUtf8("list_figures"))
        self.verticalLayout_3.addWidget(self.list_figures)
        self.horizontalLayout.addWidget(self.group_figures)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.tab_widget.addTab(self.tab_layout, _fromUtf8(""))
        self.tab_fonts = QtGui.QWidget()
        self.tab_fonts.setObjectName(_fromUtf8("tab_fonts"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab_fonts)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.scrollArea = QtGui.QScrollArea(self.tab_fonts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 784, 271))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_9.addWidget(self.label_16)
        self.combo_font_figure = QtGui.QFontComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_font_figure.sizePolicy().hasHeightForWidth())
        self.combo_font_figure.setSizePolicy(sizePolicy)
        self.combo_font_figure.setObjectName(_fromUtf8("combo_font_figure"))
        self.horizontalLayout_9.addWidget(self.combo_font_figure)
        self.verticalLayout_15.addLayout(self.horizontalLayout_9)
        self.group_main = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_main.setObjectName(_fromUtf8("group_main"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.group_main)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_11 = QtGui.QLabel(self.group_main)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.edit_figure_title = QtGui.QLineEdit(self.group_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_figure_title.sizePolicy().hasHeightForWidth())
        self.edit_figure_title.setSizePolicy(sizePolicy)
        self.edit_figure_title.setInputMask(_fromUtf8(""))
        self.edit_figure_title.setObjectName(_fromUtf8("edit_figure_title"))
        self.horizontalLayout_2.addWidget(self.edit_figure_title)
        self.spin_size_main = QtGui.QSpinBox(self.group_main)
        self.spin_size_main.setMinimum(1)
        self.spin_size_main.setMaximum(96)
        self.spin_size_main.setObjectName(_fromUtf8("spin_size_main"))
        self.horizontalLayout_2.addWidget(self.spin_size_main)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_15.addWidget(self.group_main)
        self.group_x_axis = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_x_axis.setObjectName(_fromUtf8("group_x_axis"))
        self.gridLayout_2 = QtGui.QGridLayout(self.group_x_axis)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem10 = QtGui.QSpacerItem(97, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 1, 4, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 4, 1, 1)
        self.edit_y_label = QtGui.QLineEdit(self.group_x_axis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_y_label.sizePolicy().hasHeightForWidth())
        self.edit_y_label.setSizePolicy(sizePolicy)
        self.edit_y_label.setText(_fromUtf8(""))
        self.edit_y_label.setObjectName(_fromUtf8("edit_y_label"))
        self.gridLayout_2.addWidget(self.edit_y_label, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.group_x_axis)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 1, 5, 1, 1)
        self.label_14 = QtGui.QLabel(self.group_x_axis)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 5, 1, 1)
        self.toolButton = QtGui.QToolButton(self.group_x_axis)
        self.toolButton.setText(_fromUtf8(""))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout_2.addWidget(self.toolButton, 0, 0, 1, 1)
        self.edit_x_label = QtGui.QLineEdit(self.group_x_axis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_x_label.sizePolicy().hasHeightForWidth())
        self.edit_x_label.setSizePolicy(sizePolicy)
        self.edit_x_label.setObjectName(_fromUtf8("edit_x_label"))
        self.gridLayout_2.addWidget(self.edit_x_label, 0, 1, 1, 1)
        self.spin_size_y_ticks = QtGui.QSpinBox(self.group_x_axis)
        self.spin_size_y_ticks.setMinimum(1)
        self.spin_size_y_ticks.setMaximum(96)
        self.spin_size_y_ticks.setObjectName(_fromUtf8("spin_size_y_ticks"))
        self.gridLayout_2.addWidget(self.spin_size_y_ticks, 1, 6, 1, 1)
        self.spin_size_x_ticks = QtGui.QSpinBox(self.group_x_axis)
        self.spin_size_x_ticks.setMinimum(1)
        self.spin_size_x_ticks.setMaximum(96)
        self.spin_size_x_ticks.setObjectName(_fromUtf8("spin_size_x_ticks"))
        self.gridLayout_2.addWidget(self.spin_size_x_ticks, 0, 6, 1, 1)
        self.spin_size_x_axis = QtGui.QSpinBox(self.group_x_axis)
        self.spin_size_x_axis.setMinimum(1)
        self.spin_size_x_axis.setMaximum(96)
        self.spin_size_x_axis.setObjectName(_fromUtf8("spin_size_x_axis"))
        self.gridLayout_2.addWidget(self.spin_size_x_axis, 0, 3, 1, 1)
        self.spin_size_y_axis = QtGui.QSpinBox(self.group_x_axis)
        self.spin_size_y_axis.setMinimum(1)
        self.spin_size_y_axis.setMaximum(96)
        self.spin_size_y_axis.setObjectName(_fromUtf8("spin_size_y_axis"))
        self.gridLayout_2.addWidget(self.spin_size_y_axis, 1, 3, 1, 1)
        self.toolButton_2 = QtGui.QToolButton(self.group_x_axis)
        self.toolButton_2.setText(_fromUtf8(""))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout_2.addWidget(self.toolButton_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.group_x_axis)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.group_x_axis)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout_15.addWidget(self.group_x_axis)
        self.group_legend_font = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_legend_font.setObjectName(_fromUtf8("group_legend_font"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.group_legend_font)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.toolButton_3 = QtGui.QToolButton(self.group_legend_font)
        self.toolButton_3.setText(_fromUtf8(""))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.horizontalLayout_3.addWidget(self.toolButton_3)
        self.lineEdit = QtGui.QLineEdit(self.group_legend_font)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.label_4 = QtGui.QLabel(self.group_legend_font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spin_size_legend_entries = QtGui.QSpinBox(self.group_legend_font)
        self.spin_size_legend_entries.setMinimum(1)
        self.spin_size_legend_entries.setMaximum(96)
        self.spin_size_legend_entries.setObjectName(_fromUtf8("spin_size_legend_entries"))
        self.horizontalLayout_3.addWidget(self.spin_size_legend_entries)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.label_19 = QtGui.QLabel(self.group_legend_font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_3.addWidget(self.label_19)
        self.spin_size_legend = QtGui.QSpinBox(self.group_legend_font)
        self.spin_size_legend.setMinimum(1)
        self.spin_size_legend.setMaximum(96)
        self.spin_size_legend.setObjectName(_fromUtf8("spin_size_legend"))
        self.horizontalLayout_3.addWidget(self.spin_size_legend)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_15.addWidget(self.group_legend_font)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_16.addWidget(self.scrollArea)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem13)
        self.tab_widget.addTab(self.tab_fonts, _fromUtf8(""))
        self.tab_colors = QtGui.QWidget()
        self.tab_colors.setObjectName(_fromUtf8("tab_colors"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_colors)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.tab_colors)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.combo_sequential = QtGui.QComboBox(self.groupBox)
        self.combo_sequential.setObjectName(_fromUtf8("combo_sequential"))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.combo_sequential, 1, 2, 1, 1)
        self.radio_custom = QtGui.QRadioButton(self.groupBox)
        self.radio_custom.setObjectName(_fromUtf8("radio_custom"))
        self.gridLayout_9.addWidget(self.radio_custom, 3, 0, 1, 1)
        self.radio_qualitative = QtGui.QRadioButton(self.groupBox)
        self.radio_qualitative.setChecked(False)
        self.radio_qualitative.setObjectName(_fromUtf8("radio_qualitative"))
        self.gridLayout_9.addWidget(self.radio_qualitative, 0, 0, 1, 2)
        self.combo_qualitative = QtGui.QComboBox(self.groupBox)
        self.combo_qualitative.setObjectName(_fromUtf8("combo_qualitative"))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.combo_qualitative, 0, 2, 1, 1)
        self.radio_diverging = QtGui.QRadioButton(self.groupBox)
        self.radio_diverging.setObjectName(_fromUtf8("radio_diverging"))
        self.gridLayout_9.addWidget(self.radio_diverging, 2, 0, 1, 1)
        self.radio_sequential = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_sequential.sizePolicy().hasHeightForWidth())
        self.radio_sequential.setSizePolicy(sizePolicy)
        self.radio_sequential.setObjectName(_fromUtf8("radio_sequential"))
        self.gridLayout_9.addWidget(self.radio_sequential, 1, 0, 1, 1)
        self.combo_diverging = QtGui.QComboBox(self.groupBox)
        self.combo_diverging.setObjectName(_fromUtf8("combo_diverging"))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.combo_diverging, 2, 2, 1, 1)
        self.button_remove_custom = QtGui.QPushButton(self.groupBox)
        self.button_remove_custom.setObjectName(_fromUtf8("button_remove_custom"))
        self.gridLayout_9.addWidget(self.button_remove_custom, 3, 3, 1, 1)
        self.combo_custom = QtGui.QComboBox(self.groupBox)
        self.combo_custom.setObjectName(_fromUtf8("combo_custom"))
        self.gridLayout_9.addWidget(self.combo_custom, 3, 2, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem14, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.group_preview_colors = QtGui.QGroupBox(self.tab_colors)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_preview_colors.sizePolicy().hasHeightForWidth())
        self.group_preview_colors.setSizePolicy(sizePolicy)
        self.group_preview_colors.setObjectName(_fromUtf8("group_preview_colors"))
        self.layout_preview_colors = QtGui.QVBoxLayout(self.group_preview_colors)
        self.layout_preview_colors.setMargin(0)
        self.layout_preview_colors.setObjectName(_fromUtf8("layout_preview_colors"))
        self.verticalLayout.addWidget(self.group_preview_colors)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_colors)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.label_38 = QtGui.QLabel(self.groupBox_10)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.verticalLayout_24.addWidget(self.label_38)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.button_reverse_order = QtGui.QPushButton(self.groupBox_10)
        self.button_reverse_order.setObjectName(_fromUtf8("button_reverse_order"))
        self.horizontalLayout_24.addWidget(self.button_reverse_order)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem15)
        self.verticalLayout_24.addLayout(self.horizontalLayout_24)
        self.color_test_area = QtGui.QListWidget(self.groupBox_10)
        self.color_test_area.setDragEnabled(True)
        self.color_test_area.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.color_test_area.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.color_test_area.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.color_test_area.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.color_test_area.setMovement(QtGui.QListView.Snap)
        self.color_test_area.setObjectName(_fromUtf8("color_test_area"))
        self.verticalLayout_24.addWidget(self.color_test_area)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_37 = QtGui.QLabel(self.groupBox_10)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_23.addWidget(self.label_37)
        self.spin_number = QtGui.QSpinBox(self.groupBox_10)
        self.spin_number.setMinimum(1)
        self.spin_number.setProperty("value", 6)
        self.spin_number.setObjectName(_fromUtf8("spin_number"))
        self.horizontalLayout_23.addWidget(self.spin_number)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem16)
        self.verticalLayout_24.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_5.addWidget(self.groupBox_10)
        self.tab_widget.addTab(self.tab_colors, _fromUtf8(""))
        self.tab_view = QtGui.QWidget()
        self.tab_view.setObjectName(_fromUtf8("tab_view"))
        self.tab_widget.addTab(self.tab_view, _fromUtf8(""))
        self.verticalLayout_12.addWidget(self.tab_widget)
        self.label_3.setBuddy(self.table_categorical)
        self.label_5.setBuddy(self.table_numerical)
        self.label_16.setBuddy(self.combo_font_figure)

        self.retranslateUi(VisualizationDesigner)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VisualizationDesigner)

    def retranslateUi(self, VisualizationDesigner):
        VisualizationDesigner.setWindowTitle(_translate("VisualizationDesigner", "Visualization designer – Coquery", None))
        self.group_variables.setTitle(_translate("VisualizationDesigner", "&Available variables", None))
        self.label_3.setText(_translate("VisualizationDesigner", "&Categorical:", None))
        self.label_5.setText(_translate("VisualizationDesigner", "&Numeric:", None))
        self.group_data.setTitle(_translate("VisualizationDesigner", "&Data", None))
        self.label_7.setText(_translate("VisualizationDesigner", "X:", None))
        self.label_6.setText(_translate("VisualizationDesigner", "Y:", None))
        self.label_8.setText(_translate("VisualizationDesigner", "Z:", None))
        self.group_layout.setTitle(_translate("VisualizationDesigner", "&Grid layout", None))
        self.label_rows.setText(_translate("VisualizationDesigner", "Rows", None))
        self.label_columns.setText(_translate("VisualizationDesigner", "Columns", None))
        self.check_wrap_layout.setText(_translate("VisualizationDesigner", "&Wrap columns", None))
        self.group_legend.setTitle(_translate("VisualizationDesigner", "&Legend", None))
        self.check_show_legend.setText(_translate("VisualizationDesigner", "Show legend", None))
        self.label_13.setText(_translate("VisualizationDesigner", "Number of columns:", None))
        self.group_preview.setTitle(_translate("VisualizationDesigner", "Preview", None))
        self.group_figures.setTitle(_translate("VisualizationDesigner", "&Figure types", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_layout), _translate("VisualizationDesigner", "Design", None))
        self.label_16.setText(_translate("VisualizationDesigner", "&Figure font:", None))
        self.group_main.setTitle(_translate("VisualizationDesigner", "Main", None))
        self.label_11.setText(_translate("VisualizationDesigner", "Figure label:", None))
        self.edit_figure_title.setPlaceholderText(_translate("VisualizationDesigner", "Title", None))
        self.spin_size_main.setSuffix(_translate("VisualizationDesigner", " pt", None))
        self.group_x_axis.setTitle(_translate("VisualizationDesigner", "Data", None))
        self.edit_y_label.setPlaceholderText(_translate("VisualizationDesigner", "Label", None))
        self.label_17.setText(_translate("VisualizationDesigner", "Tick size:", None))
        self.label_14.setText(_translate("VisualizationDesigner", "Tick size:", None))
        self.edit_x_label.setPlaceholderText(_translate("VisualizationDesigner", "Label", None))
        self.spin_size_y_ticks.setSuffix(_translate("VisualizationDesigner", " pt", None))
        self.spin_size_x_ticks.setSuffix(_translate("VisualizationDesigner", " pt", None))
        self.spin_size_x_axis.setSuffix(_translate("VisualizationDesigner", " pt", None))
        self.spin_size_y_axis.setSuffix(_translate("VisualizationDesigner", " pt", None))
        self.label.setText(_translate("VisualizationDesigner", "Size:", None))
        self.label_2.setText(_translate("VisualizationDesigner", "Size:", None))
        self.group_legend_font.setTitle(_translate("VisualizationDesigner", "Legend", None))
        self.lineEdit.setPlaceholderText(_translate("VisualizationDesigner", "Legend", None))
        self.label_4.setText(_translate("VisualizationDesigner", "Size:", None))
        self.spin_size_legend_entries.setSuffix(_translate("VisualizationDesigner", " pt", None))
        self.label_19.setText(_translate("VisualizationDesigner", "Entry size:", None))
        self.spin_size_legend.setSuffix(_translate("VisualizationDesigner", " pt", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_fonts), _translate("VisualizationDesigner", "Labels", None))
        self.combo_sequential.setItemText(0, _translate("VisualizationDesigner", "Greys", None))
        self.combo_sequential.setItemText(1, _translate("VisualizationDesigner", "Reds", None))
        self.combo_sequential.setItemText(2, _translate("VisualizationDesigner", "Greens", None))
        self.combo_sequential.setItemText(3, _translate("VisualizationDesigner", "Blues", None))
        self.combo_sequential.setItemText(4, _translate("VisualizationDesigner", "Oranges", None))
        self.combo_sequential.setItemText(5, _translate("VisualizationDesigner", "Purples", None))
        self.combo_sequential.setItemText(6, _translate("VisualizationDesigner", "BuGn", None))
        self.combo_sequential.setItemText(7, _translate("VisualizationDesigner", "BuPu", None))
        self.combo_sequential.setItemText(8, _translate("VisualizationDesigner", "GnBu", None))
        self.combo_sequential.setItemText(9, _translate("VisualizationDesigner", "OrRd", None))
        self.combo_sequential.setItemText(10, _translate("VisualizationDesigner", "PuBu", None))
        self.combo_sequential.setItemText(11, _translate("VisualizationDesigner", "PuRd", None))
        self.combo_sequential.setItemText(12, _translate("VisualizationDesigner", "RdPu", None))
        self.combo_sequential.setItemText(13, _translate("VisualizationDesigner", "YlGn", None))
        self.combo_sequential.setItemText(14, _translate("VisualizationDesigner", "PuBuGn", None))
        self.combo_sequential.setItemText(15, _translate("VisualizationDesigner", "YlGnBu", None))
        self.combo_sequential.setItemText(16, _translate("VisualizationDesigner", "YlOrBr", None))
        self.combo_sequential.setItemText(17, _translate("VisualizationDesigner", "YlOrRd", None))
        self.radio_custom.setText(_translate("VisualizationDesigner", "Custom", None))
        self.radio_qualitative.setText(_translate("VisualizationDesigner", "Qualitative", None))
        self.combo_qualitative.setItemText(0, _translate("VisualizationDesigner", "Set1", None))
        self.combo_qualitative.setItemText(1, _translate("VisualizationDesigner", "Set2", None))
        self.combo_qualitative.setItemText(2, _translate("VisualizationDesigner", "Set3", None))
        self.combo_qualitative.setItemText(3, _translate("VisualizationDesigner", "Paired", None))
        self.combo_qualitative.setItemText(4, _translate("VisualizationDesigner", "Accent", None))
        self.combo_qualitative.setItemText(5, _translate("VisualizationDesigner", "Pastel1", None))
        self.combo_qualitative.setItemText(6, _translate("VisualizationDesigner", "Pastel2", None))
        self.combo_qualitative.setItemText(7, _translate("VisualizationDesigner", "Dark2", None))
        self.radio_diverging.setText(_translate("VisualizationDesigner", "Diverging", None))
        self.radio_sequential.setText(_translate("VisualizationDesigner", "Sequential", None))
        self.combo_diverging.setItemText(0, _translate("VisualizationDesigner", "RdBu", None))
        self.combo_diverging.setItemText(1, _translate("VisualizationDesigner", "RdGy", None))
        self.combo_diverging.setItemText(2, _translate("VisualizationDesigner", "PRGn", None))
        self.combo_diverging.setItemText(3, _translate("VisualizationDesigner", "PiYG", None))
        self.combo_diverging.setItemText(4, _translate("VisualizationDesigner", "BrBG", None))
        self.combo_diverging.setItemText(5, _translate("VisualizationDesigner", "RdYlBu", None))
        self.combo_diverging.setItemText(6, _translate("VisualizationDesigner", "RdYlGn", None))
        self.combo_diverging.setItemText(7, _translate("VisualizationDesigner", "Spectral", None))
        self.button_remove_custom.setText(_translate("VisualizationDesigner", "Remove", None))
        self.group_preview_colors.setTitle(_translate("VisualizationDesigner", "Preview", None))
        self.label_38.setText(_translate("VisualizationDesigner", "Click to modify color, drag to change order:", None))
        self.button_reverse_order.setText(_translate("VisualizationDesigner", "Reverse order", None))
        self.label_37.setText(_translate("VisualizationDesigner", "Number of colors:", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_colors), _translate("VisualizationDesigner", "Colors", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_view), _translate("VisualizationDesigner", "View", None))

from ..classes import CoqFeatureList, CoqFeatureTray

