# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualizationDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VisualizationDesigner(object):
    def setupUi(self, VisualizationDesigner):
        VisualizationDesigner.setObjectName("VisualizationDesigner")
        VisualizationDesigner.resize(800, 600)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(VisualizationDesigner)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tab_widget = QtWidgets.QTabWidget(VisualizationDesigner)
        self.tab_widget.setObjectName("tab_widget")
        self.tab_layout = QtWidgets.QWidget()
        self.tab_layout.setObjectName("tab_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_layout)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.group_variables = QtWidgets.QGroupBox(self.tab_layout)
        self.group_variables.setObjectName("group_variables")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.group_variables)
        self.verticalLayout_11.setSpacing(8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_dimensions = QtWidgets.QLabel(self.group_variables)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dimensions.sizePolicy().hasHeightForWidth())
        self.label_dimensions.setSizePolicy(sizePolicy)
        self.label_dimensions.setText("")
        self.label_dimensions.setObjectName("label_dimensions")
        self.verticalLayout_11.addWidget(self.label_dimensions)
        self.button_refresh_data = QtWidgets.QPushButton(self.group_variables)
        self.button_refresh_data.setObjectName("button_refresh_data")
        self.verticalLayout_11.addWidget(self.button_refresh_data)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.group_variables)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.table_categorical = CoqFeatureList(self.group_variables)
        self.table_categorical.setAlternatingRowColors(True)
        self.table_categorical.setObjectName("table_categorical")
        self.verticalLayout_2.addWidget(self.table_categorical)
        self.verticalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.group_variables)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.table_numerical = CoqFeatureList(self.group_variables)
        self.table_numerical.setAlternatingRowColors(True)
        self.table_numerical.setObjectName("table_numerical")
        self.verticalLayout_10.addWidget(self.table_numerical)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout.addWidget(self.group_variables)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.group_data = QtWidgets.QGroupBox(self.tab_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_data.sizePolicy().hasHeightForWidth())
        self.group_data.setSizePolicy(sizePolicy)
        self.group_data.setObjectName("group_data")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.group_data)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tray_data_x = CoqFeatureTray(self.group_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tray_data_x.sizePolicy().hasHeightForWidth())
        self.tray_data_x.setSizePolicy(sizePolicy)
        self.tray_data_x.setObjectName("tray_data_x")
        self.gridLayout_3.addWidget(self.tray_data_x, 0, 1, 3, 1)
        self.label_7 = QtWidgets.QLabel(self.group_data)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.button_clear_z = QtWidgets.QToolButton(self.group_data)
        self.button_clear_z.setText("")
        self.button_clear_z.setObjectName("button_clear_z")
        self.gridLayout_3.addWidget(self.button_clear_z, 7, 2, 1, 1)
        self.button_clear_y = QtWidgets.QToolButton(self.group_data)
        self.button_clear_y.setText("")
        self.button_clear_y.setObjectName("button_clear_y")
        self.gridLayout_3.addWidget(self.button_clear_y, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.group_data)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.group_data)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.tray_data_z = CoqFeatureTray(self.group_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tray_data_z.sizePolicy().hasHeightForWidth())
        self.tray_data_z.setSizePolicy(sizePolicy)
        self.tray_data_z.setObjectName("tray_data_z")
        self.gridLayout_3.addWidget(self.tray_data_z, 6, 1, 3, 1)
        self.tray_data_y = CoqFeatureTray(self.group_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tray_data_y.sizePolicy().hasHeightForWidth())
        self.tray_data_y.setSizePolicy(sizePolicy)
        self.tray_data_y.setObjectName("tray_data_y")
        self.gridLayout_3.addWidget(self.tray_data_y, 3, 1, 3, 1)
        self.button_clear_x = QtWidgets.QToolButton(self.group_data)
        self.button_clear_x.setText("")
        self.button_clear_x.setObjectName("button_clear_x")
        self.gridLayout_3.addWidget(self.button_clear_x, 1, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.verticalLayout_6.addWidget(self.group_data)
        self.group_layout = QtWidgets.QGroupBox(self.tab_layout)
        self.group_layout.setObjectName("group_layout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.group_layout)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(13, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        self.button_clear_columns = QtWidgets.QToolButton(self.group_layout)
        self.button_clear_columns.setText("")
        self.button_clear_columns.setObjectName("button_clear_columns")
        self.gridLayout.addWidget(self.button_clear_columns, 1, 3, 1, 1)
        self.button_clear_rows = QtWidgets.QToolButton(self.group_layout)
        self.button_clear_rows.setText("")
        self.button_clear_rows.setObjectName("button_clear_rows")
        self.gridLayout.addWidget(self.button_clear_rows, 4, 3, 1, 1)
        self.tray_columns = CoqFeatureTray(self.group_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tray_columns.sizePolicy().hasHeightForWidth())
        self.tray_columns.setSizePolicy(sizePolicy)
        self.tray_columns.setObjectName("tray_columns")
        self.gridLayout.addWidget(self.tray_columns, 0, 2, 3, 1)
        spacerItem2 = QtWidgets.QSpacerItem(13, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 3, 1, 1)
        self.tray_rows = CoqFeatureTray(self.group_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tray_rows.sizePolicy().hasHeightForWidth())
        self.tray_rows.setSizePolicy(sizePolicy)
        self.tray_rows.setObjectName("tray_rows")
        self.gridLayout.addWidget(self.tray_rows, 3, 2, 3, 1)
        self.label_rows = QtWidgets.QLabel(self.group_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rows.sizePolicy().hasHeightForWidth())
        self.label_rows.setSizePolicy(sizePolicy)
        self.label_rows.setObjectName("label_rows")
        self.gridLayout.addWidget(self.label_rows, 4, 1, 1, 1)
        self.icon_rows = QtWidgets.QLabel(self.group_layout)
        self.icon_rows.setText("")
        self.icon_rows.setObjectName("icon_rows")
        self.gridLayout.addWidget(self.icon_rows, 4, 0, 1, 1)
        self.icon_columns = QtWidgets.QLabel(self.group_layout)
        self.icon_columns.setText("")
        self.icon_columns.setObjectName("icon_columns")
        self.gridLayout.addWidget(self.icon_columns, 1, 0, 1, 1)
        self.label_columns = QtWidgets.QLabel(self.group_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_columns.sizePolicy().hasHeightForWidth())
        self.label_columns.setSizePolicy(sizePolicy)
        self.label_columns.setObjectName("label_columns")
        self.gridLayout.addWidget(self.label_columns, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(13, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.check_wrap_layout = QtWidgets.QCheckBox(self.group_layout)
        self.check_wrap_layout.setChecked(True)
        self.check_wrap_layout.setObjectName("check_wrap_layout")
        self.verticalLayout_5.addWidget(self.check_wrap_layout)
        self.verticalLayout_6.addWidget(self.group_layout)
        self.group_custom = QtWidgets.QGroupBox(self.tab_layout)
        self.group_custom.setObjectName("group_custom")
        self.layout_custom = QtWidgets.QVBoxLayout(self.group_custom)
        self.layout_custom.setObjectName("layout_custom")
        self.verticalLayout_6.addWidget(self.group_custom)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.verticalLayout_6.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.group_figures = QtWidgets.QGroupBox(self.tab_layout)
        self.group_figures.setObjectName("group_figures")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.group_figures)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.list_figures = QtWidgets.QListWidget(self.group_figures)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_figures.sizePolicy().hasHeightForWidth())
        self.list_figures.setSizePolicy(sizePolicy)
        self.list_figures.setMinimumSize(QtCore.QSize(200, 0))
        self.list_figures.setMaximumSize(QtCore.QSize(200, 16777215))
        self.list_figures.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_figures.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_figures.setProperty("showDropIndicator", False)
        self.list_figures.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.list_figures.setViewMode(QtWidgets.QListView.IconMode)
        self.list_figures.setObjectName("list_figures")
        self.verticalLayout_3.addWidget(self.list_figures)
        self.check_hide_unavailable = QtWidgets.QCheckBox(self.group_figures)
        self.check_hide_unavailable.setChecked(True)
        self.check_hide_unavailable.setObjectName("check_hide_unavailable")
        self.verticalLayout_3.addWidget(self.check_hide_unavailable)
        self.horizontalLayout.addWidget(self.group_figures)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.tab_widget.addTab(self.tab_layout, "")
        self.tab_fonts = QtWidgets.QWidget()
        self.tab_fonts.setObjectName("tab_fonts")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_fonts)
        self.verticalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.tab_fonts)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.combo_font_figure = QtWidgets.QFontComboBox(self.tab_fonts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_font_figure.sizePolicy().hasHeightForWidth())
        self.combo_font_figure.setSizePolicy(sizePolicy)
        self.combo_font_figure.setObjectName("combo_font_figure")
        self.horizontalLayout_9.addWidget(self.combo_font_figure)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.group_main = QtWidgets.QGroupBox(self.tab_fonts)
        self.group_main.setObjectName("group_main")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_main)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.edit_figure_title = QtWidgets.QLineEdit(self.group_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_figure_title.sizePolicy().hasHeightForWidth())
        self.edit_figure_title.setSizePolicy(sizePolicy)
        self.edit_figure_title.setInputMask("")
        self.edit_figure_title.setObjectName("edit_figure_title")
        self.gridLayout_5.addWidget(self.edit_figure_title, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.group_main)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.spin_size_title = QtWidgets.QSpinBox(self.group_main)
        self.spin_size_title.setMinimum(1)
        self.spin_size_title.setMaximum(96)
        self.spin_size_title.setObjectName("spin_size_title")
        self.gridLayout_5.addWidget(self.spin_size_title, 0, 2, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.verticalLayout_8.addWidget(self.group_main)
        self.group_x_axis = QtWidgets.QGroupBox(self.tab_fonts)
        self.group_x_axis.setObjectName("group_x_axis")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_x_axis)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.group_x_axis)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_x_label = QtWidgets.QLineEdit(self.group_x_axis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_x_label.sizePolicy().hasHeightForWidth())
        self.edit_x_label.setSizePolicy(sizePolicy)
        self.edit_x_label.setObjectName("edit_x_label")
        self.horizontalLayout_2.addWidget(self.edit_x_label)
        self.label = QtWidgets.QLabel(self.group_x_axis)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spin_size_x_label = QtWidgets.QSpinBox(self.group_x_axis)
        self.spin_size_x_label.setMinimum(1)
        self.spin_size_x_label.setMaximum(96)
        self.spin_size_x_label.setObjectName("spin_size_x_label")
        self.horizontalLayout_2.addWidget(self.spin_size_x_label)
        self.horizontalLayout_2.setStretch(0, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.group_x_axis)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.spin_size_x_ticklabels = QtWidgets.QSpinBox(self.group_x_axis)
        self.spin_size_x_ticklabels.setMinimum(1)
        self.spin_size_x_ticklabels.setMaximum(96)
        self.spin_size_x_ticklabels.setObjectName("spin_size_x_ticklabels")
        self.horizontalLayout_6.addWidget(self.spin_size_x_ticklabels)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.group_x_axis)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edit_y_label = QtWidgets.QLineEdit(self.group_x_axis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_y_label.sizePolicy().hasHeightForWidth())
        self.edit_y_label.setSizePolicy(sizePolicy)
        self.edit_y_label.setText("")
        self.edit_y_label.setObjectName("edit_y_label")
        self.horizontalLayout_3.addWidget(self.edit_y_label)
        self.label_2 = QtWidgets.QLabel(self.group_x_axis)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spin_size_y_label = QtWidgets.QSpinBox(self.group_x_axis)
        self.spin_size_y_label.setMinimum(1)
        self.spin_size_y_label.setMaximum(96)
        self.spin_size_y_label.setObjectName("spin_size_y_label")
        self.horizontalLayout_3.addWidget(self.spin_size_y_label)
        self.horizontalLayout_3.setStretch(0, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.group_x_axis)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.spin_size_y_ticklabels = QtWidgets.QSpinBox(self.group_x_axis)
        self.spin_size_y_ticklabels.setMinimum(1)
        self.spin_size_y_ticklabels.setMaximum(96)
        self.spin_size_y_ticklabels.setObjectName("spin_size_y_ticklabels")
        self.horizontalLayout_7.addWidget(self.spin_size_y_ticklabels)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout_8.addWidget(self.group_x_axis)
        self.group_legend_font = QtWidgets.QGroupBox(self.tab_fonts)
        self.group_legend_font.setObjectName("group_legend_font")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.group_legend_font)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.edit_legend_title = QtWidgets.QLineEdit(self.group_legend_font)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_legend_title.sizePolicy().hasHeightForWidth())
        self.edit_legend_title.setSizePolicy(sizePolicy)
        self.edit_legend_title.setObjectName("edit_legend_title")
        self.horizontalLayout_8.addWidget(self.edit_legend_title)
        self.label_4 = QtWidgets.QLabel(self.group_legend_font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.spin_size_legend = QtWidgets.QSpinBox(self.group_legend_font)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_size_legend.sizePolicy().hasHeightForWidth())
        self.spin_size_legend.setSizePolicy(sizePolicy)
        self.spin_size_legend.setMinimum(1)
        self.spin_size_legend.setMaximum(96)
        self.spin_size_legend.setObjectName("spin_size_legend")
        self.horizontalLayout_8.addWidget(self.spin_size_legend)
        self.horizontalLayout_8.setStretch(0, 1)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.check_show_legend = QtWidgets.QCheckBox(self.group_legend_font)
        self.check_show_legend.setChecked(True)
        self.check_show_legend.setObjectName("check_show_legend")
        self.horizontalLayout_4.addWidget(self.check_show_legend)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 0, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.group_legend_font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.spin_columns = QtWidgets.QSpinBox(self.group_legend_font)
        self.spin_columns.setMinimum(1)
        self.spin_columns.setMaximum(9)
        self.spin_columns.setProperty("value", 1)
        self.spin_columns.setObjectName("spin_columns")
        self.horizontalLayout_10.addWidget(self.spin_columns)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 0, 2, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.group_legend_font)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        self.spin_size_legend_entries = QtWidgets.QSpinBox(self.group_legend_font)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_size_legend_entries.sizePolicy().hasHeightForWidth())
        self.spin_size_legend_entries.setSizePolicy(sizePolicy)
        self.spin_size_legend_entries.setMinimum(1)
        self.spin_size_legend_entries.setMaximum(96)
        self.spin_size_legend_entries.setObjectName("spin_size_legend_entries")
        self.horizontalLayout_11.addWidget(self.spin_size_legend_entries)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.group_legend_font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_4)
        self.verticalLayout_8.addWidget(self.group_legend_font)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.tab_widget.addTab(self.tab_fonts, "")
        self.tab_colors = QtWidgets.QWidget()
        self.tab_colors.setObjectName("tab_colors")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_colors)
        self.horizontalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab_colors)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radio_custom = QtWidgets.QRadioButton(self.groupBox)
        self.radio_custom.setObjectName("radio_custom")
        self.gridLayout_6.addWidget(self.radio_custom, 5, 0, 1, 1)
        self.radio_qualitative = QtWidgets.QRadioButton(self.groupBox)
        self.radio_qualitative.setChecked(False)
        self.radio_qualitative.setObjectName("radio_qualitative")
        self.gridLayout_6.addWidget(self.radio_qualitative, 1, 0, 1, 1)
        self.radio_sequential = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_sequential.sizePolicy().hasHeightForWidth())
        self.radio_sequential.setSizePolicy(sizePolicy)
        self.radio_sequential.setObjectName("radio_sequential")
        self.gridLayout_6.addWidget(self.radio_sequential, 2, 0, 1, 1)
        self.check_reverse = QtWidgets.QCheckBox(self.groupBox)
        self.check_reverse.setObjectName("check_reverse")
        self.gridLayout_6.addWidget(self.check_reverse, 6, 0, 1, 1)
        self.combo_sequential = QtWidgets.QComboBox(self.groupBox)
        self.combo_sequential.setObjectName("combo_sequential")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.combo_sequential.addItem("")
        self.gridLayout_6.addWidget(self.combo_sequential, 2, 1, 1, 1)
        self.button_remove_custom = QtWidgets.QPushButton(self.groupBox)
        self.button_remove_custom.setObjectName("button_remove_custom")
        self.gridLayout_6.addWidget(self.button_remove_custom, 5, 2, 1, 1)
        self.combo_custom = QtWidgets.QComboBox(self.groupBox)
        self.combo_custom.setObjectName("combo_custom")
        self.gridLayout_6.addWidget(self.combo_custom, 5, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 7, 1, 1, 1)
        self.combo_qualitative = QtWidgets.QComboBox(self.groupBox)
        self.combo_qualitative.setObjectName("combo_qualitative")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.combo_qualitative.addItem("")
        self.gridLayout_6.addWidget(self.combo_qualitative, 1, 1, 1, 1)
        self.button_change_color = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_change_color.sizePolicy().hasHeightForWidth())
        self.button_change_color.setSizePolicy(sizePolicy)
        self.button_change_color.setObjectName("button_change_color")
        self.gridLayout_6.addWidget(self.button_change_color, 4, 1, 1, 1)
        self.radio_diverging = QtWidgets.QRadioButton(self.groupBox)
        self.radio_diverging.setObjectName("radio_diverging")
        self.gridLayout_6.addWidget(self.radio_diverging, 3, 0, 1, 1)
        self.combo_diverging = QtWidgets.QComboBox(self.groupBox)
        self.combo_diverging.setObjectName("combo_diverging")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.combo_diverging.addItem("")
        self.gridLayout_6.addWidget(self.combo_diverging, 3, 1, 1, 1)
        self.radio_single_color = QtWidgets.QRadioButton(self.groupBox)
        self.radio_single_color.setObjectName("radio_single_color")
        self.gridLayout_6.addWidget(self.radio_single_color, 4, 0, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.palette_preview = QtWidgets.QGroupBox(self.tab_colors)
        self.palette_preview.setObjectName("palette_preview")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.palette_preview)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_38 = QtWidgets.QLabel(self.palette_preview)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 0, 0, 1, 3)
        self.color_test_area = QtWidgets.QListWidget(self.palette_preview)
        self.color_test_area.setDragEnabled(True)
        self.color_test_area.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.color_test_area.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.color_test_area.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.color_test_area.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.color_test_area.setMovement(QtWidgets.QListView.Snap)
        self.color_test_area.setObjectName("color_test_area")
        self.gridLayout_7.addWidget(self.color_test_area, 1, 0, 1, 3)
        self.label_37 = QtWidgets.QLabel(self.palette_preview)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 2, 0, 1, 1)
        self.spin_number = QtWidgets.QSpinBox(self.palette_preview)
        self.spin_number.setMinimum(1)
        self.spin_number.setProperty("value", 6)
        self.spin_number.setObjectName("spin_number")
        self.gridLayout_7.addWidget(self.spin_number, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(136, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem7, 2, 2, 1, 1)
        self.horizontalLayout_5.addWidget(self.palette_preview)
        self.horizontalLayout_5.setStretch(0, 4)
        self.horizontalLayout_5.setStretch(1, 3)
        self.tab_widget.addTab(self.tab_colors, "")
        self.tab_margins = QtWidgets.QWidget()
        self.tab_margins.setObjectName("tab_margins")
        self.layout_margins = QtWidgets.QVBoxLayout(self.tab_margins)
        self.layout_margins.setContentsMargins(4, 4, 4, 4)
        self.layout_margins.setObjectName("layout_margins")
        self.label_15 = QtWidgets.QLabel(self.tab_margins)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.layout_margins.addWidget(self.label_15)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_margins.addItem(spacerItem8)
        self.tab_widget.addTab(self.tab_margins, "")
        self.verticalLayout_4.addWidget(self.tab_widget)
        self.label_3.setBuddy(self.table_categorical)
        self.label_5.setBuddy(self.table_numerical)
        self.label_16.setBuddy(self.combo_font_figure)
        self.label_11.setBuddy(self.edit_figure_title)
        self.label_9.setBuddy(self.edit_x_label)
        self.label.setBuddy(self.spin_size_x_label)
        self.label_14.setBuddy(self.spin_size_x_ticklabels)
        self.label_10.setBuddy(self.edit_y_label)
        self.label_2.setBuddy(self.spin_size_y_label)
        self.label_17.setBuddy(self.spin_size_y_ticklabels)
        self.label_13.setBuddy(self.spin_columns)
        self.label_19.setBuddy(self.spin_size_legend_entries)
        self.label_12.setBuddy(self.edit_legend_title)
        self.label_37.setBuddy(self.spin_number)

        self.retranslateUi(VisualizationDesigner)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VisualizationDesigner)
        VisualizationDesigner.setTabOrder(self.tab_widget, self.button_refresh_data)
        VisualizationDesigner.setTabOrder(self.button_refresh_data, self.table_categorical)
        VisualizationDesigner.setTabOrder(self.table_categorical, self.table_numerical)
        VisualizationDesigner.setTabOrder(self.table_numerical, self.button_clear_x)
        VisualizationDesigner.setTabOrder(self.button_clear_x, self.tray_data_x)
        VisualizationDesigner.setTabOrder(self.tray_data_x, self.button_clear_y)
        VisualizationDesigner.setTabOrder(self.button_clear_y, self.tray_data_y)
        VisualizationDesigner.setTabOrder(self.tray_data_y, self.button_clear_z)
        VisualizationDesigner.setTabOrder(self.button_clear_z, self.tray_data_z)
        VisualizationDesigner.setTabOrder(self.tray_data_z, self.button_clear_columns)
        VisualizationDesigner.setTabOrder(self.button_clear_columns, self.tray_columns)
        VisualizationDesigner.setTabOrder(self.tray_columns, self.button_clear_rows)
        VisualizationDesigner.setTabOrder(self.button_clear_rows, self.tray_rows)
        VisualizationDesigner.setTabOrder(self.tray_rows, self.check_wrap_layout)
        VisualizationDesigner.setTabOrder(self.check_wrap_layout, self.list_figures)
        VisualizationDesigner.setTabOrder(self.list_figures, self.check_hide_unavailable)
        VisualizationDesigner.setTabOrder(self.check_hide_unavailable, self.combo_font_figure)
        VisualizationDesigner.setTabOrder(self.combo_font_figure, self.edit_figure_title)
        VisualizationDesigner.setTabOrder(self.edit_figure_title, self.spin_size_title)
        VisualizationDesigner.setTabOrder(self.spin_size_title, self.edit_x_label)
        VisualizationDesigner.setTabOrder(self.edit_x_label, self.spin_size_x_label)
        VisualizationDesigner.setTabOrder(self.spin_size_x_label, self.spin_size_x_ticklabels)
        VisualizationDesigner.setTabOrder(self.spin_size_x_ticklabels, self.edit_y_label)
        VisualizationDesigner.setTabOrder(self.edit_y_label, self.spin_size_y_label)
        VisualizationDesigner.setTabOrder(self.spin_size_y_label, self.spin_size_y_ticklabels)
        VisualizationDesigner.setTabOrder(self.spin_size_y_ticklabels, self.check_show_legend)
        VisualizationDesigner.setTabOrder(self.check_show_legend, self.edit_legend_title)
        VisualizationDesigner.setTabOrder(self.edit_legend_title, self.spin_size_legend)
        VisualizationDesigner.setTabOrder(self.spin_size_legend, self.spin_columns)
        VisualizationDesigner.setTabOrder(self.spin_columns, self.spin_size_legend_entries)
        VisualizationDesigner.setTabOrder(self.spin_size_legend_entries, self.radio_qualitative)
        VisualizationDesigner.setTabOrder(self.radio_qualitative, self.combo_qualitative)
        VisualizationDesigner.setTabOrder(self.combo_qualitative, self.radio_sequential)
        VisualizationDesigner.setTabOrder(self.radio_sequential, self.combo_sequential)
        VisualizationDesigner.setTabOrder(self.combo_sequential, self.radio_diverging)
        VisualizationDesigner.setTabOrder(self.radio_diverging, self.combo_diverging)
        VisualizationDesigner.setTabOrder(self.combo_diverging, self.radio_single_color)
        VisualizationDesigner.setTabOrder(self.radio_single_color, self.button_change_color)
        VisualizationDesigner.setTabOrder(self.button_change_color, self.radio_custom)
        VisualizationDesigner.setTabOrder(self.radio_custom, self.combo_custom)
        VisualizationDesigner.setTabOrder(self.combo_custom, self.button_remove_custom)
        VisualizationDesigner.setTabOrder(self.button_remove_custom, self.check_reverse)
        VisualizationDesigner.setTabOrder(self.check_reverse, self.color_test_area)
        VisualizationDesigner.setTabOrder(self.color_test_area, self.spin_number)

    def retranslateUi(self, VisualizationDesigner):
        _translate = QtCore.QCoreApplication.translate
        VisualizationDesigner.setWindowTitle(_translate("VisualizationDesigner", "Visualization designer – Coquery"))
        self.group_variables.setTitle(_translate("VisualizationDesigner", "Data"))
        self.button_refresh_data.setText(_translate("VisualizationDesigner", "&Refresh data"))
        self.label_3.setText(_translate("VisualizationDesigner", "&Categorical:"))
        self.label_5.setText(_translate("VisualizationDesigner", "&Numeric:"))
        self.group_data.setTitle(_translate("VisualizationDesigner", "Dimensions"))
        self.label_7.setText(_translate("VisualizationDesigner", "X axis"))
        self.label_8.setText(_translate("VisualizationDesigner", "Color"))
        self.label_6.setText(_translate("VisualizationDesigner", "Y axis"))
        self.group_layout.setTitle(_translate("VisualizationDesigner", "Grid layout"))
        self.label_rows.setText(_translate("VisualizationDesigner", "Rows"))
        self.label_columns.setText(_translate("VisualizationDesigner", "Columns"))
        self.check_wrap_layout.setText(_translate("VisualizationDesigner", "&Wrap columns"))
        self.group_custom.setTitle(_translate("VisualizationDesigner", "Figure &options"))
        self.group_figures.setTitle(_translate("VisualizationDesigner", "&Figure types"))
        self.check_hide_unavailable.setText(_translate("VisualizationDesigner", "Hide &unavailable"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_layout), _translate("VisualizationDesigner", "&Design"))
        self.label_16.setText(_translate("VisualizationDesigner", "&Figure font:"))
        self.group_main.setTitle(_translate("VisualizationDesigner", "Main"))
        self.edit_figure_title.setPlaceholderText(_translate("VisualizationDesigner", "Title"))
        self.label_11.setText(_translate("VisualizationDesigner", "&Title:"))
        self.spin_size_title.setSuffix(_translate("VisualizationDesigner", " pt"))
        self.group_x_axis.setTitle(_translate("VisualizationDesigner", "Data"))
        self.label_9.setText(_translate("VisualizationDesigner", "&X axis:"))
        self.edit_x_label.setPlaceholderText(_translate("VisualizationDesigner", "Label"))
        self.label.setText(_translate("VisualizationDesigner", "&X label size:"))
        self.spin_size_x_label.setSuffix(_translate("VisualizationDesigner", " pt"))
        self.label_14.setText(_translate("VisualizationDesigner", "&X tick size:"))
        self.spin_size_x_ticklabels.setSuffix(_translate("VisualizationDesigner", " pt"))
        self.label_10.setText(_translate("VisualizationDesigner", "&Y axis:"))
        self.edit_y_label.setPlaceholderText(_translate("VisualizationDesigner", "Label"))
        self.label_2.setText(_translate("VisualizationDesigner", "&Y label size:"))
        self.spin_size_y_label.setSuffix(_translate("VisualizationDesigner", " pt"))
        self.label_17.setText(_translate("VisualizationDesigner", "&Y tick size:"))
        self.spin_size_y_ticklabels.setSuffix(_translate("VisualizationDesigner", " pt"))
        self.group_legend_font.setTitle(_translate("VisualizationDesigner", "Legend"))
        self.edit_legend_title.setPlaceholderText(_translate("VisualizationDesigner", "Legend"))
        self.label_4.setText(_translate("VisualizationDesigner", "Size:"))
        self.spin_size_legend.setSuffix(_translate("VisualizationDesigner", " pt"))
        self.check_show_legend.setText(_translate("VisualizationDesigner", "&Show legend"))
        self.label_13.setText(_translate("VisualizationDesigner", "&Number of columns:"))
        self.label_19.setText(_translate("VisualizationDesigner", "&Entry size:"))
        self.spin_size_legend_entries.setSuffix(_translate("VisualizationDesigner", " pt"))
        self.label_12.setText(_translate("VisualizationDesigner", "T&itle:"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_fonts), _translate("VisualizationDesigner", "&Labels"))
        self.groupBox.setTitle(_translate("VisualizationDesigner", "&Palettes"))
        self.radio_custom.setText(_translate("VisualizationDesigner", "&Custom"))
        self.radio_qualitative.setText(_translate("VisualizationDesigner", "&Qualitative"))
        self.radio_sequential.setText(_translate("VisualizationDesigner", "Sequential"))
        self.check_reverse.setText(_translate("VisualizationDesigner", "Re&verse palette"))
        self.combo_sequential.setItemText(0, _translate("VisualizationDesigner", "Greys"))
        self.combo_sequential.setItemText(1, _translate("VisualizationDesigner", "Reds"))
        self.combo_sequential.setItemText(2, _translate("VisualizationDesigner", "Greens"))
        self.combo_sequential.setItemText(3, _translate("VisualizationDesigner", "Blues"))
        self.combo_sequential.setItemText(4, _translate("VisualizationDesigner", "Oranges"))
        self.combo_sequential.setItemText(5, _translate("VisualizationDesigner", "Purples"))
        self.combo_sequential.setItemText(6, _translate("VisualizationDesigner", "BuGn"))
        self.combo_sequential.setItemText(7, _translate("VisualizationDesigner", "BuPu"))
        self.combo_sequential.setItemText(8, _translate("VisualizationDesigner", "GnBu"))
        self.combo_sequential.setItemText(9, _translate("VisualizationDesigner", "OrRd"))
        self.combo_sequential.setItemText(10, _translate("VisualizationDesigner", "PuBu"))
        self.combo_sequential.setItemText(11, _translate("VisualizationDesigner", "PuRd"))
        self.combo_sequential.setItemText(12, _translate("VisualizationDesigner", "RdPu"))
        self.combo_sequential.setItemText(13, _translate("VisualizationDesigner", "YlGn"))
        self.combo_sequential.setItemText(14, _translate("VisualizationDesigner", "PuBuGn"))
        self.combo_sequential.setItemText(15, _translate("VisualizationDesigner", "YlGnBu"))
        self.combo_sequential.setItemText(16, _translate("VisualizationDesigner", "YlOrBr"))
        self.combo_sequential.setItemText(17, _translate("VisualizationDesigner", "YlOrRd"))
        self.button_remove_custom.setText(_translate("VisualizationDesigner", "&Remove"))
        self.combo_qualitative.setItemText(0, _translate("VisualizationDesigner", "Set1"))
        self.combo_qualitative.setItemText(1, _translate("VisualizationDesigner", "Set2"))
        self.combo_qualitative.setItemText(2, _translate("VisualizationDesigner", "Set3"))
        self.combo_qualitative.setItemText(3, _translate("VisualizationDesigner", "Paired"))
        self.combo_qualitative.setItemText(4, _translate("VisualizationDesigner", "Accent"))
        self.combo_qualitative.setItemText(5, _translate("VisualizationDesigner", "Pastel1"))
        self.combo_qualitative.setItemText(6, _translate("VisualizationDesigner", "Pastel2"))
        self.combo_qualitative.setItemText(7, _translate("VisualizationDesigner", "Dark2"))
        self.button_change_color.setText(_translate("VisualizationDesigner", "Chan&ge"))
        self.radio_diverging.setText(_translate("VisualizationDesigner", "Diverging"))
        self.combo_diverging.setItemText(0, _translate("VisualizationDesigner", "RdBu"))
        self.combo_diverging.setItemText(1, _translate("VisualizationDesigner", "RdGy"))
        self.combo_diverging.setItemText(2, _translate("VisualizationDesigner", "PRGn"))
        self.combo_diverging.setItemText(3, _translate("VisualizationDesigner", "PiYG"))
        self.combo_diverging.setItemText(4, _translate("VisualizationDesigner", "BrBG"))
        self.combo_diverging.setItemText(5, _translate("VisualizationDesigner", "RdYlBu"))
        self.combo_diverging.setItemText(6, _translate("VisualizationDesigner", "RdYlGn"))
        self.combo_diverging.setItemText(7, _translate("VisualizationDesigner", "Spectral"))
        self.radio_single_color.setText(_translate("VisualizationDesigner", "&Single color"))
        self.label_38.setText(_translate("VisualizationDesigner", "Click to modify color, drag to change order:"))
        self.label_37.setText(_translate("VisualizationDesigner", "&Number of colors:"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_colors), _translate("VisualizationDesigner", "&Colors"))
        self.label_15.setText(_translate("VisualizationDesigner", "Plot a figure first."))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_margins), _translate("VisualizationDesigner", "&Margins"))

from ..classes import CoqFeatureList, CoqFeatureTray
