#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import sys

s = "".join(sys.stdin.readlines())
s = s.replace("from PyQt4 import QtCore, QtGui", 
                "from coquery.gui.pyqt_compat import QtCore, QtGui, frameShadow, frameShape")
s = s.replace("setFrameShadow(QtGui.QFrame.Raised)", 
                "setFrameShadow(frameShadow)")
s = s.replace("setFrameShape(QtGui.QFrame.StyledPanel)", 
                "setFrameShape(frameShape)")
print(s)