# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coquery_compact.ui'
#
# Created: Sun Sep  6 12:57:28 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from pyqt_compat import QtCore, QtGui, frameShadow

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(927, 732)
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.options_area = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.options_area.sizePolicy().hasHeightForWidth())
        self.options_area.setSizePolicy(sizePolicy)
        self.options_area.setFrameShape(QtGui.QFrame.NoFrame)
        self.options_area.setFrameShadow(frameShadow)
        self.options_area.setObjectName(_fromUtf8("options_area"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.options_area)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.box_corpus_select = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_corpus_select.sizePolicy().hasHeightForWidth())
        self.box_corpus_select.setSizePolicy(sizePolicy)
        self.box_corpus_select.setFrameShape(QtGui.QFrame.NoFrame)
        self.box_corpus_select.setFrameShadow(frameShadow)
        self.box_corpus_select.setObjectName(_fromUtf8("box_corpus_select"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.box_corpus_select)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.combo_corpus = QtGui.QComboBox(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_corpus.sizePolicy().hasHeightForWidth())
        self.combo_corpus.setSizePolicy(sizePolicy)
        self.combo_corpus.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.combo_corpus.setEditable(False)
        self.combo_corpus.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.combo_corpus.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.combo_corpus.setFrame(True)
        self.combo_corpus.setObjectName(_fromUtf8("combo_corpus"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.combo_corpus)
        self.label_9 = QtGui.QLabel(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.radio_mode_context = QtGui.QRadioButton(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_mode_context.sizePolicy().hasHeightForWidth())
        self.radio_mode_context.setSizePolicy(sizePolicy)
        self.radio_mode_context.setChecked(True)
        self.radio_mode_context.setObjectName(_fromUtf8("radio_mode_context"))
        self.verticalLayout_13.addWidget(self.radio_mode_context)
        self.radio_mode_tokens = QtGui.QRadioButton(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_mode_tokens.sizePolicy().hasHeightForWidth())
        self.radio_mode_tokens.setSizePolicy(sizePolicy)
        self.radio_mode_tokens.setObjectName(_fromUtf8("radio_mode_tokens"))
        self.verticalLayout_13.addWidget(self.radio_mode_tokens)
        self.radio_mode_collocations = QtGui.QRadioButton(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_mode_collocations.sizePolicy().hasHeightForWidth())
        self.radio_mode_collocations.setSizePolicy(sizePolicy)
        self.radio_mode_collocations.setObjectName(_fromUtf8("radio_mode_collocations"))
        self.verticalLayout_13.addWidget(self.radio_mode_collocations)
        self.radio_mode_frequency = QtGui.QRadioButton(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_mode_frequency.sizePolicy().hasHeightForWidth())
        self.radio_mode_frequency.setSizePolicy(sizePolicy)
        self.radio_mode_frequency.setObjectName(_fromUtf8("radio_mode_frequency"))
        self.verticalLayout_13.addWidget(self.radio_mode_frequency)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.verticalLayout_13)
        self.context_mode = QtGui.QLabel(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_mode.sizePolicy().hasHeightForWidth())
        self.context_mode.setSizePolicy(sizePolicy)
        self.context_mode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.context_mode.setObjectName(_fromUtf8("context_mode"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.context_mode)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.radio_context_mode_kwic = QtGui.QRadioButton(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_context_mode_kwic.sizePolicy().hasHeightForWidth())
        self.radio_context_mode_kwic.setSizePolicy(sizePolicy)
        self.radio_context_mode_kwic.setObjectName(_fromUtf8("radio_context_mode_kwic"))
        self.verticalLayout_11.addWidget(self.radio_context_mode_kwic)
        self.radio_context_mode_string = QtGui.QRadioButton(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_context_mode_string.sizePolicy().hasHeightForWidth())
        self.radio_context_mode_string.setSizePolicy(sizePolicy)
        self.radio_context_mode_string.setObjectName(_fromUtf8("radio_context_mode_string"))
        self.verticalLayout_11.addWidget(self.radio_context_mode_string)
        self.radio_context_mode_columns = QtGui.QRadioButton(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_context_mode_columns.sizePolicy().hasHeightForWidth())
        self.radio_context_mode_columns.setSizePolicy(sizePolicy)
        self.radio_context_mode_columns.setObjectName(_fromUtf8("radio_context_mode_columns"))
        self.verticalLayout_11.addWidget(self.radio_context_mode_columns)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.verticalLayout_11)
        self.horizontalLayout_5.addLayout(self.formLayout)
        self.verticalLayout_3.addWidget(self.box_corpus_select)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.context_left_span_label = QtGui.QLabel(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span_label.sizePolicy().hasHeightForWidth())
        self.context_left_span_label.setSizePolicy(sizePolicy)
        self.context_left_span_label.setObjectName(_fromUtf8("context_left_span_label"))
        self.horizontalLayout_11.addWidget(self.context_left_span_label)
        self.context_left_span = QtGui.QSpinBox(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span.sizePolicy().hasHeightForWidth())
        self.context_left_span.setSizePolicy(sizePolicy)
        self.context_left_span.setObjectName(_fromUtf8("context_left_span"))
        self.horizontalLayout_11.addWidget(self.context_left_span)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.context_right_span_label = QtGui.QLabel(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_right_span_label.sizePolicy().hasHeightForWidth())
        self.context_right_span_label.setSizePolicy(sizePolicy)
        self.context_right_span_label.setObjectName(_fromUtf8("context_right_span_label"))
        self.horizontalLayout_12.addWidget(self.context_right_span_label)
        self.context_right_span = QtGui.QSpinBox(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_right_span.sizePolicy().hasHeightForWidth())
        self.context_right_span.setSizePolicy(sizePolicy)
        self.context_right_span.setFrame(True)
        self.context_right_span.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.context_right_span.setObjectName(_fromUtf8("context_right_span"))
        self.horizontalLayout_12.addWidget(self.context_right_span)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.button_stopwords = QtGui.QPushButton(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stopwords.sizePolicy().hasHeightForWidth())
        self.button_stopwords.setSizePolicy(sizePolicy)
        self.button_stopwords.setObjectName(_fromUtf8("button_stopwords"))
        self.gridLayout.addWidget(self.button_stopwords, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.button_run_query = QtGui.QPushButton(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_run_query.sizePolicy().hasHeightForWidth())
        self.button_run_query.setSizePolicy(sizePolicy)
        self.button_run_query.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.button_run_query.setIcon(icon)
        self.button_run_query.setIconSize(QtCore.QSize(16, 16))
        self.button_run_query.setObjectName(_fromUtf8("button_run_query"))
        self.gridLayout.addWidget(self.button_run_query, 1, 0, 1, 1)
        self.progress_bar = QtGui.QProgressBar(self.options_area)
        self.progress_bar.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
        self.progress_bar.setSizePolicy(sizePolicy)
        self.progress_bar.setMaximum(1)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.progress_bar.setInvertedAppearance(True)
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        self.gridLayout.addWidget(self.progress_bar, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.box_input_settings = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_input_settings.sizePolicy().hasHeightForWidth())
        self.box_input_settings.setSizePolicy(sizePolicy)
        self.box_input_settings.setFrameShape(QtGui.QFrame.NoFrame)
        self.box_input_settings.setFrameShadow(frameShadow)
        self.box_input_settings.setObjectName(_fromUtf8("box_input_settings"))
        self.verticalLayout = QtGui.QVBoxLayout(self.box_input_settings)
        self.verticalLayout.setSpacing(-1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.edit_query_string = QtGui.QTextEdit(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_query_string.sizePolicy().hasHeightForWidth())
        self.edit_query_string.setSizePolicy(sizePolicy)
        self.edit_query_string.setObjectName(_fromUtf8("edit_query_string"))
        self.gridLayout_2.addWidget(self.edit_query_string, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1)
        self.radio_query_string = QtGui.QRadioButton(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_query_string.sizePolicy().hasHeightForWidth())
        self.radio_query_string.setSizePolicy(sizePolicy)
        self.radio_query_string.setText(_fromUtf8(""))
        self.radio_query_string.setChecked(True)
        self.radio_query_string.setObjectName(_fromUtf8("radio_query_string"))
        self.gridLayout_2.addWidget(self.radio_query_string, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.button_file_options = QtGui.QPushButton(self.box_input_settings)
        self.button_file_options.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_file_options.sizePolicy().hasHeightForWidth())
        self.button_file_options.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-properties"))
        self.button_file_options.setIcon(icon)
        self.button_file_options.setIconSize(QtCore.QSize(16, 16))
        self.button_file_options.setObjectName(_fromUtf8("button_file_options"))
        self.gridLayout_3.addWidget(self.button_file_options, 2, 2, 1, 1)
        self.radio_query_file = QtGui.QRadioButton(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_query_file.sizePolicy().hasHeightForWidth())
        self.radio_query_file.setSizePolicy(sizePolicy)
        self.radio_query_file.setText(_fromUtf8(""))
        self.radio_query_file.setObjectName(_fromUtf8("radio_query_file"))
        self.gridLayout_3.addWidget(self.radio_query_file, 1, 0, 1, 1)
        self.edit_file_name = QtGui.QLineEdit(self.box_input_settings)
        self.edit_file_name.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_file_name.sizePolicy().hasHeightForWidth())
        self.edit_file_name.setSizePolicy(sizePolicy)
        self.edit_file_name.setAccessibleDescription(_fromUtf8(""))
        self.edit_file_name.setObjectName(_fromUtf8("edit_file_name"))
        self.gridLayout_3.addWidget(self.edit_file_name, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 1, 1, 1)
        self.button_browse_file = QtGui.QPushButton(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_file.sizePolicy().hasHeightForWidth())
        self.button_browse_file.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.button_browse_file.setIcon(icon)
        self.button_browse_file.setIconSize(QtCore.QSize(16, 16))
        self.button_browse_file.setObjectName(_fromUtf8("button_browse_file"))
        self.gridLayout_3.addWidget(self.button_browse_file, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_7.addWidget(self.box_input_settings)
        self.output_settings = QtGui.QVBoxLayout()
        self.output_settings.setSpacing(4)
        self.output_settings.setObjectName(_fromUtf8("output_settings"))
        self.box_output_options = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_output_options.sizePolicy().hasHeightForWidth())
        self.box_output_options.setSizePolicy(sizePolicy)
        self.box_output_options.setFrameShape(QtGui.QFrame.NoFrame)
        self.box_output_options.setFrameShadow(frameShadow)
        self.box_output_options.setObjectName(_fromUtf8("box_output_options"))
        self.output_columns = QtGui.QVBoxLayout(self.box_output_options)
        self.output_columns.setSpacing(-1)
        self.output_columns.setMargin(0)
        self.output_columns.setObjectName(_fromUtf8("output_columns"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.box_output_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.button_add_link = QtGui.QPushButton(self.box_output_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_link.sizePolicy().hasHeightForWidth())
        self.button_add_link.setSizePolicy(sizePolicy)
        self.button_add_link.setWhatsThis(_fromUtf8(""))
        self.button_add_link.setText(_fromUtf8(""))
        self.button_add_link.setIconSize(QtCore.QSize(16, 16))
        self.button_add_link.setObjectName(_fromUtf8("button_add_link"))
        self.horizontalLayout_2.addWidget(self.button_add_link)
        self.button_remove_link = QtGui.QPushButton(self.box_output_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_remove_link.sizePolicy().hasHeightForWidth())
        self.button_remove_link.setSizePolicy(sizePolicy)
        self.button_remove_link.setText(_fromUtf8(""))
        self.button_remove_link.setIconSize(QtCore.QSize(16, 16))
        self.button_remove_link.setObjectName(_fromUtf8("button_remove_link"))
        self.horizontalLayout_2.addWidget(self.button_remove_link)
        self.horizontalLayout_2.setStretch(0, 1)
        self.output_columns.addLayout(self.horizontalLayout_2)
        self.options_list = QtGui.QVBoxLayout()
        self.options_list.setObjectName(_fromUtf8("options_list"))
        self.options_tree = QtGui.QTreeWidget(self.box_output_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options_tree.sizePolicy().hasHeightForWidth())
        self.options_tree.setSizePolicy(sizePolicy)
        self.options_tree.setObjectName(_fromUtf8("options_tree"))
        self.options_tree.headerItem().setText(0, _fromUtf8("1"))
        self.options_tree.header().setVisible(False)
        self.options_list.addWidget(self.options_tree)
        self.output_columns.addLayout(self.options_list)
        self.output_settings.addWidget(self.box_output_options)
        self.box_source_filter = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_source_filter.sizePolicy().hasHeightForWidth())
        self.box_source_filter.setSizePolicy(sizePolicy)
        self.box_source_filter.setFrameShape(QtGui.QFrame.NoFrame)
        self.box_source_filter.setFrameShadow(frameShadow)
        self.box_source_filter.setObjectName(_fromUtf8("box_source_filter"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.box_source_filter)
        self.verticalLayout_5.setSpacing(-1)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tag_cloud = QtGui.QWidget(self.box_source_filter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tag_cloud.sizePolicy().hasHeightForWidth())
        self.tag_cloud.setSizePolicy(sizePolicy)
        self.tag_cloud.setObjectName(_fromUtf8("tag_cloud"))
        self.tag_container = QtGui.QHBoxLayout(self.tag_cloud)
        self.tag_container.setSpacing(4)
        self.tag_container.setMargin(0)
        self.tag_container.setObjectName(_fromUtf8("tag_container"))
        self.verticalLayout_5.addWidget(self.tag_cloud)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.box_source_filter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.edit_query_filter = QtGui.QLineEdit(self.box_source_filter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_query_filter.sizePolicy().hasHeightForWidth())
        self.edit_query_filter.setSizePolicy(sizePolicy)
        self.edit_query_filter.setDragEnabled(True)
        self.edit_query_filter.setObjectName(_fromUtf8("edit_query_filter"))
        self.horizontalLayout.addWidget(self.edit_query_filter)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.output_settings.addWidget(self.box_source_filter)
        self.horizontalLayout_7.addLayout(self.output_settings)
        self.verticalLayout_4.addWidget(self.options_area)
        self.tabbed_views = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabbed_views.sizePolicy().hasHeightForWidth())
        self.tabbed_views.setSizePolicy(sizePolicy)
        self.tabbed_views.setTabPosition(QtGui.QTabWidget.South)
        self.tabbed_views.setIconSize(QtCore.QSize(16, 16))
        self.tabbed_views.setObjectName(_fromUtf8("tabbed_views"))
        self.results_tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results_tab.sizePolicy().hasHeightForWidth())
        self.results_tab.setSizePolicy(sizePolicy)
        self.results_tab.setObjectName(_fromUtf8("results_tab"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.results_tab)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.data_preview = QtGui.QTableView(self.results_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_preview.sizePolicy().hasHeightForWidth())
        self.data_preview.setSizePolicy(sizePolicy)
        self.data_preview.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.data_preview.setFrameShape(QtGui.QFrame.Box)
        self.data_preview.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.data_preview.setAlternatingRowColors(True)
        self.data_preview.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.data_preview.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.data_preview.setTextElideMode(QtCore.Qt.ElideRight)
        self.data_preview.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setSortingEnabled(True)
        self.data_preview.setObjectName(_fromUtf8("data_preview"))
        self.verticalLayout_9.addWidget(self.data_preview)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("table"))
        self.tabbed_views.addTab(self.results_tab, icon, _fromUtf8(""))
        self.log_tab = QtGui.QWidget()
        self.log_tab.setObjectName(_fromUtf8("log_tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.log_tab)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.log_table = QtGui.QTableView(self.log_tab)
        self.log_table.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.log_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.log_table.setSortingEnabled(True)
        self.log_table.setObjectName(_fromUtf8("log_table"))
        self.log_table.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.log_table)
        self.tabbed_views.addTab(self.log_tab, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabbed_views)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 927, 37))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        self.menuCorpus = QtGui.QMenu(self.menubar)
        self.menuCorpus.setObjectName(_fromUtf8("menuCorpus"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuAnalyse = QtGui.QMenu(self.menubar)
        self.menuAnalyse.setObjectName(_fromUtf8("menuAnalyse"))
        self.menuTime_data = QtGui.QMenu(self.menuAnalyse)
        self.menuTime_data.setObjectName(_fromUtf8("menuTime_data"))
        self.menuFrequencies = QtGui.QMenu(self.menuAnalyse)
        self.menuFrequencies.setObjectName(_fromUtf8("menuFrequencies"))
        self.menuFrequency_maps = QtGui.QMenu(self.menuAnalyse)
        self.menuFrequency_maps.setObjectName(_fromUtf8("menuFrequency_maps"))
        self.menuCorpus_locations = QtGui.QMenu(self.menuAnalyse)
        self.menuCorpus_locations.setObjectName(_fromUtf8("menuCorpus_locations"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_input_file = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.action_open_input_file.setIcon(icon)
        self.action_open_input_file.setObjectName(_fromUtf8("action_open_input_file"))
        self.action_save_results = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.action_save_results.setIcon(icon)
        self.action_save_results.setObjectName(_fromUtf8("action_save_results"))
        self.action_help = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-contents"))
        self.action_help.setIcon(icon)
        self.action_help.setObjectName(_fromUtf8("action_help"))
        self.action_about_coquery = QtGui.QAction(MainWindow)
        self.action_about_coquery.setObjectName(_fromUtf8("action_about_coquery"))
        self.actionDummy = QtGui.QAction(MainWindow)
        self.actionDummy.setObjectName(_fromUtf8("actionDummy"))
        self.action_distinct_tokens = QtGui.QAction(MainWindow)
        self.action_distinct_tokens.setObjectName(_fromUtf8("action_distinct_tokens"))
        self.action_frequency = QtGui.QAction(MainWindow)
        self.action_frequency.setObjectName(_fromUtf8("action_frequency"))
        self.action_all_tokens = QtGui.QAction(MainWindow)
        self.action_all_tokens.setObjectName(_fromUtf8("action_all_tokens"))
        self.action_statistics = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-statistics"))
        self.action_statistics.setIcon(icon)
        self.action_statistics.setObjectName(_fromUtf8("action_statistics"))
        self.action_mySQL_settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("server-database"))
        self.action_mySQL_settings.setIcon(icon)
        self.action_mySQL_settings.setObjectName(_fromUtf8("action_mySQL_settings"))
        self.action_options = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("configure"))
        self.action_options.setIcon(icon)
        self.action_options.setObjectName(_fromUtf8("action_options"))
        self.action_quit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.action_quit.setIcon(icon)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_build_corpus = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-new"))
        self.action_build_corpus.setIcon(icon)
        self.action_build_corpus.setObjectName(_fromUtf8("action_build_corpus"))
        self.action_remove_corpus = QtGui.QAction(MainWindow)
        self.action_remove_corpus.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-delete"))
        self.action_remove_corpus.setIcon(icon)
        self.action_remove_corpus.setObjectName(_fromUtf8("action_remove_corpus"))
        self.action_manage_corpus = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("server-database"))
        self.action_manage_corpus.setIcon(icon)
        self.action_manage_corpus.setObjectName(_fromUtf8("action_manage_corpus"))
        self.action_tree_map = QtGui.QAction(MainWindow)
        self.action_tree_map.setObjectName(_fromUtf8("action_tree_map"))
        self.action_heat_map = QtGui.QAction(MainWindow)
        self.action_heat_map.setEnabled(True)
        self.action_heat_map.setObjectName(_fromUtf8("action_heat_map"))
        self.action_word_cloud = QtGui.QAction(MainWindow)
        self.action_word_cloud.setEnabled(False)
        self.action_word_cloud.setObjectName(_fromUtf8("action_word_cloud"))
        self.action_barcode_plot = QtGui.QAction(MainWindow)
        self.action_barcode_plot.setObjectName(_fromUtf8("action_barcode_plot"))
        self.action_beeswarm_plot = QtGui.QAction(MainWindow)
        self.action_beeswarm_plot.setObjectName(_fromUtf8("action_beeswarm_plot"))
        self.action_barchart_plot = QtGui.QAction(MainWindow)
        self.action_barchart_plot.setObjectName(_fromUtf8("action_barchart_plot"))
        self.action_time_series_plot = QtGui.QAction(MainWindow)
        self.action_time_series_plot.setObjectName(_fromUtf8("action_time_series_plot"))
        self.action_corpus_documentation = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-browser"))
        self.action_corpus_documentation.setIcon(icon)
        self.action_corpus_documentation.setObjectName(_fromUtf8("action_corpus_documentation"))
        self.action_percentage_area_plot = QtGui.QAction(MainWindow)
        self.action_percentage_area_plot.setObjectName(_fromUtf8("action_percentage_area_plot"))
        self.action_stacked_area_plot = QtGui.QAction(MainWindow)
        self.action_stacked_area_plot.setObjectName(_fromUtf8("action_stacked_area_plot"))
        self.action_line_plot = QtGui.QAction(MainWindow)
        self.action_line_plot.setObjectName(_fromUtf8("action_line_plot"))
        self.actionStop_words = QtGui.QAction(MainWindow)
        self.actionStop_words.setObjectName(_fromUtf8("actionStop_words"))
        self.actionStop_words_2 = QtGui.QAction(MainWindow)
        self.actionStop_words_2.setObjectName(_fromUtf8("actionStop_words_2"))
        self.action_stacked_barchart_plot = QtGui.QAction(MainWindow)
        self.action_stacked_barchart_plot.setObjectName(_fromUtf8("action_stacked_barchart_plot"))
        self.action_Stacked_bars = QtGui.QAction(MainWindow)
        self.action_Stacked_bars.setObjectName(_fromUtf8("action_Stacked_bars"))
        self.menuFile.addAction(self.action_open_input_file)
        self.menuFile.addAction(self.action_save_results)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_quit)
        self.menuHilfe.addAction(self.action_help)
        self.menuHilfe.addSeparator()
        self.menuHilfe.addAction(self.action_about_coquery)
        self.menuCorpus.addAction(self.action_build_corpus)
        self.menuCorpus.addAction(self.action_manage_corpus)
        self.menuCorpus.addSeparator()
        self.menuCorpus.addAction(self.action_statistics)
        self.menuCorpus.addAction(self.action_corpus_documentation)
        self.menuSettings.addAction(self.action_mySQL_settings)
        self.menuSettings.addAction(self.action_options)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionStop_words_2)
        self.menuTime_data.addAction(self.action_percentage_area_plot)
        self.menuTime_data.addAction(self.action_stacked_area_plot)
        self.menuTime_data.addAction(self.action_line_plot)
        self.menuFrequencies.addAction(self.action_stacked_barchart_plot)
        self.menuFrequencies.addAction(self.action_Stacked_bars)
        self.menuFrequencies.addAction(self.action_barchart_plot)
        self.menuFrequency_maps.addAction(self.action_tree_map)
        self.menuFrequency_maps.addAction(self.action_heat_map)
        self.menuFrequency_maps.addAction(self.action_word_cloud)
        self.menuCorpus_locations.addAction(self.action_barcode_plot)
        self.menuCorpus_locations.addAction(self.action_beeswarm_plot)
        self.menuAnalyse.addAction(self.menuCorpus_locations.menuAction())
        self.menuAnalyse.addAction(self.menuFrequencies.menuAction())
        self.menuAnalyse.addAction(self.menuTime_data.menuAction())
        self.menuAnalyse.addAction(self.menuFrequency_maps.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCorpus.menuAction())
        self.menubar.addAction(self.menuAnalyse.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())
        self.label_5.setBuddy(self.combo_corpus)
        self.label_12.setBuddy(self.edit_query_string)
        self.label_8.setBuddy(self.edit_file_name)
        self.label_4.setBuddy(self.edit_query_filter)

        self.retranslateUi(MainWindow)
        self.tabbed_views.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Coquery", None))
        self.label_5.setText(_translate("MainWindow", "Corpus:", None))
        self.label_9.setText(_translate("MainWindow", "Mode:", None))
        self.radio_mode_context.setText(_translate("MainWindow", "&Distinct tokens", None))
        self.radio_mode_tokens.setText(_translate("MainWindow", "&All tokens", None))
        self.radio_mode_collocations.setText(_translate("MainWindow", "Collocations", None))
        self.radio_mode_frequency.setText(_translate("MainWindow", "&Frequency", None))
        self.context_mode.setText(_translate("MainWindow", "Context:", None))
        self.radio_context_mode_kwic.setText(_translate("MainWindow", "KWIC", None))
        self.radio_context_mode_string.setText(_translate("MainWindow", "Single string", None))
        self.radio_context_mode_columns.setText(_translate("MainWindow", "Columns", None))
        self.context_left_span_label.setText(_translate("MainWindow", "Left:", None))
        self.context_right_span_label.setText(_translate("MainWindow", "Right:", None))
        self.button_stopwords.setText(_translate("MainWindow", "Stop-words", None))
        self.button_run_query.setText(_translate("MainWindow", "&Query", None))
        self.label_12.setText(_translate("MainWindow", "Qu&ery strings:", None))
        self.button_file_options.setText(_translate("MainWindow", "O&ptions", None))
        self.button_file_options.setShortcut(_translate("MainWindow", "Alt+B", None))
        self.label_8.setText(_translate("MainWindow", "Q&uery file:", None))
        self.button_browse_file.setText(_translate("MainWindow", "&Open", None))
        self.button_browse_file.setShortcut(_translate("MainWindow", "Alt+B", None))
        self.label_2.setText(_translate("MainWindow", "Columns", None))
        self.button_add_link.setToolTip(_translate("MainWindow", "Link selected column to another corpus", None))
        self.button_remove_link.setToolTip(_translate("MainWindow", "Remove selected link", None))
        self.label_4.setText(_translate("MainWindow", "Filter", None))
        self.edit_query_filter.setPlaceholderText(_translate("MainWindow", "(e.g. Year > 1999)", None))
        self.tabbed_views.setTabText(self.tabbed_views.indexOf(self.results_tab), _translate("MainWindow", "Results", None))
        self.tabbed_views.setTabText(self.tabbed_views.indexOf(self.log_tab), _translate("MainWindow", "Log", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuHilfe.setTitle(_translate("MainWindow", "&Help", None))
        self.menuCorpus.setTitle(_translate("MainWindow", "&Corpus", None))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings", None))
        self.menuAnalyse.setTitle(_translate("MainWindow", "&Visualizations", None))
        self.menuTime_data.setTitle(_translate("MainWindow", "&Time data", None))
        self.menuFrequencies.setTitle(_translate("MainWindow", "&Bar charts", None))
        self.menuFrequency_maps.setTitle(_translate("MainWindow", "Frequency maps", None))
        self.menuCorpus_locations.setTitle(_translate("MainWindow", "&Corpus locations", None))
        self.action_open_input_file.setText(_translate("MainWindow", "&Open input file...", None))
        self.action_open_input_file.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_save_results.setText(_translate("MainWindow", "&Save results...", None))
        self.action_save_results.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_help.setText(_translate("MainWindow", "&Help", None))
        self.action_help.setShortcut(_translate("MainWindow", "F1", None))
        self.action_about_coquery.setText(_translate("MainWindow", "&About Coquery", None))
        self.actionDummy.setText(_translate("MainWindow", "Dummy", None))
        self.action_distinct_tokens.setText(_translate("MainWindow", "Distinct tokens", None))
        self.action_frequency.setText(_translate("MainWindow", "Frequency", None))
        self.action_all_tokens.setText(_translate("MainWindow", "All tokens", None))
        self.action_statistics.setText(_translate("MainWindow", "Corpus &statistics", None))
        self.action_mySQL_settings.setText(_translate("MainWindow", "&MySQL settings...", None))
        self.action_options.setText(_translate("MainWindow", "&Options...", None))
        self.action_quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_build_corpus.setText(_translate("MainWindow", "&Build new corpus...", None))
        self.action_build_corpus.setToolTip(_translate("MainWindow", "Build a new corpus from text files in a folder", None))
        self.action_remove_corpus.setText(_translate("MainWindow", "&Remove corpus...", None))
        self.action_remove_corpus.setToolTip(_translate("MainWindow", "Permanently and irrevocably remove corpus database", None))
        self.action_manage_corpus.setText(_translate("MainWindow", "&Manage corpora...", None))
        self.action_manage_corpus.setToolTip(_translate("MainWindow", "Install a corpus into a MySQL database", None))
        self.action_tree_map.setText(_translate("MainWindow", "&Tree map", None))
        self.action_heat_map.setText(_translate("MainWindow", "&Heat map", None))
        self.action_word_cloud.setText(_translate("MainWindow", "Word cloud", None))
        self.action_barcode_plot.setText(_translate("MainWindow", "&Barcode plot", None))
        self.action_beeswarm_plot.setText(_translate("MainWindow", "Bee&swarm plot", None))
        self.action_barchart_plot.setText(_translate("MainWindow", "&Bars", None))
        self.action_time_series_plot.setText(_translate("MainWindow", "T&ime series", None))
        self.action_corpus_documentation.setText(_translate("MainWindow", "Corpus &documentation...", None))
        self.action_percentage_area_plot.setText(_translate("MainWindow", "&Percentage areas", None))
        self.action_stacked_area_plot.setText(_translate("MainWindow", "&Stacked areas", None))
        self.action_line_plot.setText(_translate("MainWindow", "&Lines", None))
        self.actionStop_words.setText(_translate("MainWindow", "Stop words...", None))
        self.actionStop_words_2.setText(_translate("MainWindow", "&Stop words...", None))
        self.action_stacked_barchart_plot.setText(_translate("MainWindow", "&Percentage bars", None))
        self.action_Stacked_bars.setText(_translate("MainWindow", "&Stacked bars", None))


