# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coquery.ui'
#
# Created: Fri Oct 16 16:06:33 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from pyqt_compat import QtCore, QtGui, frameShadow

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(870, 490)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setFrameShadow(frameShadow)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.options_area = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.options_area.sizePolicy().hasHeightForWidth())
        self.options_area.setSizePolicy(sizePolicy)
        self.options_area.setFrameShape(QtGui.QFrame.NoFrame)
        self.options_area.setFrameShadow(frameShadow)
        self.options_area.setObjectName(_fromUtf8("options_area"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.options_area)
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setContentsMargins(4, 4, 4, 10)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.box_corpus_select = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_corpus_select.sizePolicy().hasHeightForWidth())
        self.box_corpus_select.setSizePolicy(sizePolicy)
        self.box_corpus_select.setFrameShape(QtGui.QFrame.StyledPanel)
        self.box_corpus_select.setFrameShadow(frameShadow)
        self.box_corpus_select.setObjectName(_fromUtf8("box_corpus_select"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.box_corpus_select)
        self.horizontalLayout_5.setContentsMargins(8, 6, 8, 6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.combo_corpus = QtGui.QComboBox(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_corpus.sizePolicy().hasHeightForWidth())
        self.combo_corpus.setSizePolicy(sizePolicy)
        self.combo_corpus.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.combo_corpus.setEditable(False)
        self.combo_corpus.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.combo_corpus.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.combo_corpus.setFrame(True)
        self.combo_corpus.setObjectName(_fromUtf8("combo_corpus"))
        self.horizontalLayout_5.addWidget(self.combo_corpus)
        self.verticalLayout_3.addWidget(self.box_corpus_select)
        self.box_context_mode = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_context_mode.sizePolicy().hasHeightForWidth())
        self.box_context_mode.setSizePolicy(sizePolicy)
        self.box_context_mode.setFrameShape(QtGui.QFrame.StyledPanel)
        self.box_context_mode.setFrameShadow(frameShadow)
        self.box_context_mode.setObjectName(_fromUtf8("box_context_mode"))
        self.gridLayout_6 = QtGui.QGridLayout(self.box_context_mode)
        self.gridLayout_6.setContentsMargins(8, 6, 8, 6)
        self.gridLayout_6.setHorizontalSpacing(16)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.context_mode = QtGui.QLabel(self.box_context_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_mode.sizePolicy().hasHeightForWidth())
        self.context_mode.setSizePolicy(sizePolicy)
        self.context_mode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.context_mode.setObjectName(_fromUtf8("context_mode"))
        self.gridLayout_6.addWidget(self.context_mode, 0, 0, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.radio_context_mode_kwic = QtGui.QRadioButton(self.box_context_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_context_mode_kwic.sizePolicy().hasHeightForWidth())
        self.radio_context_mode_kwic.setSizePolicy(sizePolicy)
        self.radio_context_mode_kwic.setObjectName(_fromUtf8("radio_context_mode_kwic"))
        self.verticalLayout_11.addWidget(self.radio_context_mode_kwic)
        self.radio_context_mode_string = QtGui.QRadioButton(self.box_context_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_context_mode_string.sizePolicy().hasHeightForWidth())
        self.radio_context_mode_string.setSizePolicy(sizePolicy)
        self.radio_context_mode_string.setObjectName(_fromUtf8("radio_context_mode_string"))
        self.verticalLayout_11.addWidget(self.radio_context_mode_string)
        self.radio_context_mode_columns = QtGui.QRadioButton(self.box_context_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_context_mode_columns.sizePolicy().hasHeightForWidth())
        self.radio_context_mode_columns.setSizePolicy(sizePolicy)
        self.radio_context_mode_columns.setObjectName(_fromUtf8("radio_context_mode_columns"))
        self.verticalLayout_11.addWidget(self.radio_context_mode_columns)
        self.gridLayout_6.addLayout(self.verticalLayout_11, 0, 1, 1, 1)
        self.context_left_span_label = QtGui.QLabel(self.box_context_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span_label.sizePolicy().hasHeightForWidth())
        self.context_left_span_label.setSizePolicy(sizePolicy)
        self.context_left_span_label.setObjectName(_fromUtf8("context_left_span_label"))
        self.gridLayout_6.addWidget(self.context_left_span_label, 1, 0, 1, 1)
        self.context_left_span_layout = QtGui.QHBoxLayout()
        self.context_left_span_layout.setSpacing(0)
        self.context_left_span_layout.setObjectName(_fromUtf8("context_left_span_layout"))
        self.context_left_span = QtGui.QSpinBox(self.box_context_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span.sizePolicy().hasHeightForWidth())
        self.context_left_span.setSizePolicy(sizePolicy)
        self.context_left_span.setObjectName(_fromUtf8("context_left_span"))
        self.context_left_span_layout.addWidget(self.context_left_span)
        spacerItem1 = QtGui.QSpacerItem(13, 1, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.context_left_span_layout.addItem(spacerItem1)
        self.gridLayout_6.addLayout(self.context_left_span_layout, 1, 1, 1, 1)
        self.context_right_span_label = QtGui.QLabel(self.box_context_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_right_span_label.sizePolicy().hasHeightForWidth())
        self.context_right_span_label.setSizePolicy(sizePolicy)
        self.context_right_span_label.setObjectName(_fromUtf8("context_right_span_label"))
        self.gridLayout_6.addWidget(self.context_right_span_label, 2, 0, 1, 1)
        self.context_right_span_layout = QtGui.QHBoxLayout()
        self.context_right_span_layout.setSpacing(0)
        self.context_right_span_layout.setObjectName(_fromUtf8("context_right_span_layout"))
        self.context_right_span = QtGui.QSpinBox(self.box_context_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_right_span.sizePolicy().hasHeightForWidth())
        self.context_right_span.setSizePolicy(sizePolicy)
        self.context_right_span.setFrame(True)
        self.context_right_span.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.context_right_span.setObjectName(_fromUtf8("context_right_span"))
        self.context_right_span_layout.addWidget(self.context_right_span)
        spacerItem2 = QtGui.QSpacerItem(13, 1, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.context_right_span_layout.addItem(spacerItem2)
        self.gridLayout_6.addLayout(self.context_right_span_layout, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.box_context_mode)
        spacerItem3 = QtGui.QSpacerItem(5, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.box_qer_buttons = QtGui.QGridLayout()
        self.box_qer_buttons.setHorizontalSpacing(20)
        self.box_qer_buttons.setVerticalSpacing(4)
        self.box_qer_buttons.setObjectName(_fromUtf8("box_qer_buttons"))
        self.progress_bar = QtGui.QProgressBar(self.options_area)
        self.progress_bar.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
        self.progress_bar.setSizePolicy(sizePolicy)
        self.progress_bar.setMaximum(1)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.progress_bar.setInvertedAppearance(True)
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        self.box_qer_buttons.addWidget(self.progress_bar, 2, 1, 1, 1)
        self.button_stopwords = QtGui.QPushButton(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stopwords.sizePolicy().hasHeightForWidth())
        self.button_stopwords.setSizePolicy(sizePolicy)
        self.button_stopwords.setObjectName(_fromUtf8("button_stopwords"))
        self.box_qer_buttons.addWidget(self.button_stopwords, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.box_qer_buttons.addItem(spacerItem4, 1, 1, 1, 1)
        self.button_run_query = QtGui.QPushButton(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_run_query.sizePolicy().hasHeightForWidth())
        self.button_run_query.setSizePolicy(sizePolicy)
        self.button_run_query.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.button_run_query.setIcon(icon)
        self.button_run_query.setAutoDefault(False)
        self.button_run_query.setDefault(True)
        self.button_run_query.setObjectName(_fromUtf8("button_run_query"))
        self.box_qer_buttons.addWidget(self.button_run_query, 2, 0, 1, 1)
        self.box_qer_buttons.setRowMinimumHeight(0, 1)
        self.verticalLayout_3.addLayout(self.box_qer_buttons)
        self.verticalLayout_3.setStretch(2, 1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.box_input_settings = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_input_settings.sizePolicy().hasHeightForWidth())
        self.box_input_settings.setSizePolicy(sizePolicy)
        self.box_input_settings.setFrameShape(QtGui.QFrame.StyledPanel)
        self.box_input_settings.setFrameShadow(frameShadow)
        self.box_input_settings.setObjectName(_fromUtf8("box_input_settings"))
        self.verticalLayout = QtGui.QVBoxLayout(self.box_input_settings)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(8, 6, 8, 6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.edit_query_string = QtGui.QTextEdit(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_query_string.sizePolicy().hasHeightForWidth())
        self.edit_query_string.setSizePolicy(sizePolicy)
        self.edit_query_string.setObjectName(_fromUtf8("edit_query_string"))
        self.gridLayout_2.addWidget(self.edit_query_string, 2, 1, 1, 1)
        self.radio_query_string = QtGui.QRadioButton(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_query_string.sizePolicy().hasHeightForWidth())
        self.radio_query_string.setSizePolicy(sizePolicy)
        self.radio_query_string.setText(_fromUtf8(""))
        self.radio_query_string.setChecked(True)
        self.radio_query_string.setObjectName(_fromUtf8("radio_query_string"))
        self.gridLayout_2.addWidget(self.radio_query_string, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setToolTip(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.context_query_syntax = QtGui.QLabel(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_query_syntax.sizePolicy().hasHeightForWidth())
        self.context_query_syntax.setSizePolicy(sizePolicy)
        self.context_query_syntax.setObjectName(_fromUtf8("context_query_syntax"))
        self.horizontalLayout_3.addWidget(self.context_query_syntax)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radio_query_file = QtGui.QRadioButton(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_query_file.sizePolicy().hasHeightForWidth())
        self.radio_query_file.setSizePolicy(sizePolicy)
        self.radio_query_file.setText(_fromUtf8(""))
        self.radio_query_file.setObjectName(_fromUtf8("radio_query_file"))
        self.gridLayout_3.addWidget(self.radio_query_file, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.edit_file_name = QtGui.QLineEdit(self.box_input_settings)
        self.edit_file_name.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_file_name.sizePolicy().hasHeightForWidth())
        self.edit_file_name.setSizePolicy(sizePolicy)
        self.edit_file_name.setAccessibleDescription(_fromUtf8(""))
        self.edit_file_name.setObjectName(_fromUtf8("edit_file_name"))
        self.gridLayout_3.addWidget(self.edit_file_name, 1, 1, 1, 1)
        self.button_file_options = QtGui.QPushButton(self.box_input_settings)
        self.button_file_options.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_file_options.sizePolicy().hasHeightForWidth())
        self.button_file_options.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-properties"))
        self.button_file_options.setIcon(icon)
        self.button_file_options.setObjectName(_fromUtf8("button_file_options"))
        self.gridLayout_3.addWidget(self.button_file_options, 1, 2, 1, 1)
        self.button_browse_file = QtGui.QPushButton(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_file.sizePolicy().hasHeightForWidth())
        self.button_browse_file.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.button_browse_file.setIcon(icon)
        self.button_browse_file.setObjectName(_fromUtf8("button_browse_file"))
        self.gridLayout_3.addWidget(self.button_browse_file, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout_7.addWidget(self.box_input_settings)
        self.output_settings = QtGui.QVBoxLayout()
        self.output_settings.setSpacing(16)
        self.output_settings.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.output_settings.setObjectName(_fromUtf8("output_settings"))
        self.box_output_options = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_output_options.sizePolicy().hasHeightForWidth())
        self.box_output_options.setSizePolicy(sizePolicy)
        self.box_output_options.setFrameShape(QtGui.QFrame.StyledPanel)
        self.box_output_options.setFrameShadow(frameShadow)
        self.box_output_options.setObjectName(_fromUtf8("box_output_options"))
        self.output_columns = QtGui.QVBoxLayout(self.box_output_options)
        self.output_columns.setSpacing(0)
        self.output_columns.setContentsMargins(8, 6, 8, 6)
        self.output_columns.setObjectName(_fromUtf8("output_columns"))
        self.label_2 = QtGui.QLabel(self.box_output_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.output_columns.addWidget(self.label_2)
        self.options_list = QtGui.QVBoxLayout()
        self.options_list.setSpacing(0)
        self.options_list.setObjectName(_fromUtf8("options_list"))
        self.options_tree = QtGui.QTreeWidget(self.box_output_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options_tree.sizePolicy().hasHeightForWidth())
        self.options_tree.setSizePolicy(sizePolicy)
        self.options_tree.setObjectName(_fromUtf8("options_tree"))
        self.options_tree.headerItem().setText(0, _fromUtf8("1"))
        self.options_tree.header().setVisible(False)
        self.options_list.addWidget(self.options_tree)
        self.output_columns.addLayout(self.options_list)
        self.output_settings.addWidget(self.box_output_options)
        self.box_source_filter = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_source_filter.sizePolicy().hasHeightForWidth())
        self.box_source_filter.setSizePolicy(sizePolicy)
        self.box_source_filter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.box_source_filter.setFrameShadow(frameShadow)
        self.box_source_filter.setObjectName(_fromUtf8("box_source_filter"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.box_source_filter)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(8, 6, 8, 6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tag_cloud = QtGui.QWidget(self.box_source_filter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tag_cloud.sizePolicy().hasHeightForWidth())
        self.tag_cloud.setSizePolicy(sizePolicy)
        self.tag_cloud.setObjectName(_fromUtf8("tag_cloud"))
        self.tag_container = QtGui.QHBoxLayout(self.tag_cloud)
        self.tag_container.setSpacing(4)
        self.tag_container.setMargin(0)
        self.tag_container.setObjectName(_fromUtf8("tag_container"))
        self.verticalLayout_5.addWidget(self.tag_cloud)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.box_source_filter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.edit_query_filter = QtGui.QLineEdit(self.box_source_filter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_query_filter.sizePolicy().hasHeightForWidth())
        self.edit_query_filter.setSizePolicy(sizePolicy)
        self.edit_query_filter.setDragEnabled(True)
        self.edit_query_filter.setObjectName(_fromUtf8("edit_query_filter"))
        self.horizontalLayout.addWidget(self.edit_query_filter)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.output_settings.addWidget(self.box_source_filter)
        self.output_settings.setStretch(0, 1)
        self.horizontalLayout_7.addLayout(self.output_settings)
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.splitter_2 = QtGui.QSplitter(self.layoutWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.data_preview = QtGui.QTableView(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_preview.sizePolicy().hasHeightForWidth())
        self.data_preview.setSizePolicy(sizePolicy)
        self.data_preview.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.data_preview.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.data_preview.setAlternatingRowColors(True)
        self.data_preview.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.data_preview.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.data_preview.setTextElideMode(QtCore.Qt.ElideRight)
        self.data_preview.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setSortingEnabled(True)
        self.data_preview.setObjectName(_fromUtf8("data_preview"))
        self.horizontalLayout_4.addWidget(self.splitter_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.box_aggregation_mode = QtGui.QFrame(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_aggregation_mode.sizePolicy().hasHeightForWidth())
        self.box_aggregation_mode.setSizePolicy(sizePolicy)
        self.box_aggregation_mode.setFrameShape(QtGui.QFrame.StyledPanel)
        self.box_aggregation_mode.setFrameShadow(frameShadow)
        self.box_aggregation_mode.setObjectName(_fromUtf8("box_aggregation_mode"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.box_aggregation_mode)
        self.verticalLayout_6.setSpacing(-1)
        self.verticalLayout_6.setContentsMargins(8, 6, 8, 6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_10 = QtGui.QLabel(self.box_aggregation_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_6.addWidget(self.label_10)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.radio_aggregate_none = QtGui.QRadioButton(self.box_aggregation_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_aggregate_none.sizePolicy().hasHeightForWidth())
        self.radio_aggregate_none.setSizePolicy(sizePolicy)
        self.radio_aggregate_none.setChecked(True)
        self.radio_aggregate_none.setObjectName(_fromUtf8("radio_aggregate_none"))
        self.verticalLayout_14.addWidget(self.radio_aggregate_none)
        self.radio_aggregate_frequencies = QtGui.QRadioButton(self.box_aggregation_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_aggregate_frequencies.sizePolicy().hasHeightForWidth())
        self.radio_aggregate_frequencies.setSizePolicy(sizePolicy)
        self.radio_aggregate_frequencies.setObjectName(_fromUtf8("radio_aggregate_frequencies"))
        self.verticalLayout_14.addWidget(self.radio_aggregate_frequencies)
        self.radio_aggregate_uniques = QtGui.QRadioButton(self.box_aggregation_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_aggregate_uniques.sizePolicy().hasHeightForWidth())
        self.radio_aggregate_uniques.setSizePolicy(sizePolicy)
        self.radio_aggregate_uniques.setChecked(False)
        self.radio_aggregate_uniques.setObjectName(_fromUtf8("radio_aggregate_uniques"))
        self.verticalLayout_14.addWidget(self.radio_aggregate_uniques)
        self.radio_aggregate_collocations = QtGui.QRadioButton(self.box_aggregation_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_aggregate_collocations.sizePolicy().hasHeightForWidth())
        self.radio_aggregate_collocations.setSizePolicy(sizePolicy)
        self.radio_aggregate_collocations.setObjectName(_fromUtf8("radio_aggregate_collocations"))
        self.verticalLayout_14.addWidget(self.radio_aggregate_collocations)
        self.verticalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_4.addWidget(self.box_aggregation_mode)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.verticalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        self.menuCorpus = QtGui.QMenu(self.menubar)
        self.menuCorpus.setObjectName(_fromUtf8("menuCorpus"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuAnalyse = QtGui.QMenu(self.menubar)
        self.menuAnalyse.setObjectName(_fromUtf8("menuAnalyse"))
        self.menuTime_data = QtGui.QMenu(self.menuAnalyse)
        self.menuTime_data.setObjectName(_fromUtf8("menuTime_data"))
        self.menuFrequency_maps = QtGui.QMenu(self.menuAnalyse)
        self.menuFrequency_maps.setObjectName(_fromUtf8("menuFrequency_maps"))
        self.menuCorpus_locations = QtGui.QMenu(self.menuAnalyse)
        self.menuCorpus_locations.setObjectName(_fromUtf8("menuCorpus_locations"))
        self.menuFrequencies = QtGui.QMenu(self.menuAnalyse)
        self.menuFrequencies.setObjectName(_fromUtf8("menuFrequencies"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_input_file = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.action_open_input_file.setIcon(icon)
        self.action_open_input_file.setObjectName(_fromUtf8("action_open_input_file"))
        self.action_save_results = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.action_save_results.setIcon(icon)
        self.action_save_results.setObjectName(_fromUtf8("action_save_results"))
        self.action_help = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-contents"))
        self.action_help.setIcon(icon)
        self.action_help.setObjectName(_fromUtf8("action_help"))
        self.action_about_coquery = QtGui.QAction(MainWindow)
        self.action_about_coquery.setObjectName(_fromUtf8("action_about_coquery"))
        self.actionDummy = QtGui.QAction(MainWindow)
        self.actionDummy.setObjectName(_fromUtf8("actionDummy"))
        self.action_distinct_tokens = QtGui.QAction(MainWindow)
        self.action_distinct_tokens.setObjectName(_fromUtf8("action_distinct_tokens"))
        self.action_frequency = QtGui.QAction(MainWindow)
        self.action_frequency.setObjectName(_fromUtf8("action_frequency"))
        self.action_all_tokens = QtGui.QAction(MainWindow)
        self.action_all_tokens.setObjectName(_fromUtf8("action_all_tokens"))
        self.action_statistics = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-statistics"))
        self.action_statistics.setIcon(icon)
        self.action_statistics.setObjectName(_fromUtf8("action_statistics"))
        self.action_mySQL_settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("server-database"))
        self.action_mySQL_settings.setIcon(icon)
        self.action_mySQL_settings.setObjectName(_fromUtf8("action_mySQL_settings"))
        self.action_settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("configure"))
        self.action_settings.setIcon(icon)
        self.action_settings.setObjectName(_fromUtf8("action_settings"))
        self.action_quit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.action_quit.setIcon(icon)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_build_corpus = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-new"))
        self.action_build_corpus.setIcon(icon)
        self.action_build_corpus.setObjectName(_fromUtf8("action_build_corpus"))
        self.action_remove_corpus = QtGui.QAction(MainWindow)
        self.action_remove_corpus.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-delete"))
        self.action_remove_corpus.setIcon(icon)
        self.action_remove_corpus.setObjectName(_fromUtf8("action_remove_corpus"))
        self.action_manage_corpus = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("server-database"))
        self.action_manage_corpus.setIcon(icon)
        self.action_manage_corpus.setObjectName(_fromUtf8("action_manage_corpus"))
        self.action_tree_map = QtGui.QAction(MainWindow)
        self.action_tree_map.setEnabled(False)
        self.action_tree_map.setObjectName(_fromUtf8("action_tree_map"))
        self.action_heat_map = QtGui.QAction(MainWindow)
        self.action_heat_map.setEnabled(True)
        self.action_heat_map.setObjectName(_fromUtf8("action_heat_map"))
        self.action_word_cloud = QtGui.QAction(MainWindow)
        self.action_word_cloud.setEnabled(False)
        self.action_word_cloud.setObjectName(_fromUtf8("action_word_cloud"))
        self.action_barcode_plot = QtGui.QAction(MainWindow)
        self.action_barcode_plot.setObjectName(_fromUtf8("action_barcode_plot"))
        self.action_beeswarm_plot = QtGui.QAction(MainWindow)
        self.action_beeswarm_plot.setObjectName(_fromUtf8("action_beeswarm_plot"))
        self.action_barchart_plot = QtGui.QAction(MainWindow)
        self.action_barchart_plot.setObjectName(_fromUtf8("action_barchart_plot"))
        self.action_time_series_plot = QtGui.QAction(MainWindow)
        self.action_time_series_plot.setObjectName(_fromUtf8("action_time_series_plot"))
        self.action_corpus_documentation = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-browser"))
        self.action_corpus_documentation.setIcon(icon)
        self.action_corpus_documentation.setObjectName(_fromUtf8("action_corpus_documentation"))
        self.action_percentage_area_plot = QtGui.QAction(MainWindow)
        self.action_percentage_area_plot.setObjectName(_fromUtf8("action_percentage_area_plot"))
        self.action_stacked_area_plot = QtGui.QAction(MainWindow)
        self.action_stacked_area_plot.setObjectName(_fromUtf8("action_stacked_area_plot"))
        self.action_line_plot = QtGui.QAction(MainWindow)
        self.action_line_plot.setObjectName(_fromUtf8("action_line_plot"))
        self.actionStop_words = QtGui.QAction(MainWindow)
        self.actionStop_words.setObjectName(_fromUtf8("actionStop_words"))
        self.actionStop_words_2 = QtGui.QAction(MainWindow)
        self.actionStop_words_2.setObjectName(_fromUtf8("actionStop_words_2"))
        self.action_stacked_barchart_plot = QtGui.QAction(MainWindow)
        self.action_stacked_barchart_plot.setObjectName(_fromUtf8("action_stacked_barchart_plot"))
        self.action_Stacked_bars = QtGui.QAction(MainWindow)
        self.action_Stacked_bars.setEnabled(False)
        self.action_Stacked_bars.setObjectName(_fromUtf8("action_Stacked_bars"))
        self.action_view_log = QtGui.QAction(MainWindow)
        self.action_view_log.setObjectName(_fromUtf8("action_view_log"))
        self.menuFile.addAction(self.action_open_input_file)
        self.menuFile.addAction(self.action_save_results)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_quit)
        self.menuHilfe.addAction(self.action_help)
        self.menuHilfe.addSeparator()
        self.menuHilfe.addAction(self.action_about_coquery)
        self.menuCorpus.addAction(self.action_build_corpus)
        self.menuCorpus.addAction(self.action_manage_corpus)
        self.menuCorpus.addSeparator()
        self.menuCorpus.addAction(self.action_statistics)
        self.menuCorpus.addAction(self.action_corpus_documentation)
        self.menuSettings.addAction(self.action_mySQL_settings)
        self.menuSettings.addAction(self.action_settings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.action_view_log)
        self.menuTime_data.addAction(self.action_percentage_area_plot)
        self.menuTime_data.addAction(self.action_stacked_area_plot)
        self.menuTime_data.addAction(self.action_line_plot)
        self.menuFrequency_maps.addAction(self.action_heat_map)
        self.menuFrequency_maps.addAction(self.action_tree_map)
        self.menuFrequency_maps.addAction(self.action_word_cloud)
        self.menuCorpus_locations.addAction(self.action_barcode_plot)
        self.menuCorpus_locations.addAction(self.action_beeswarm_plot)
        self.menuFrequencies.addAction(self.action_stacked_barchart_plot)
        self.menuFrequencies.addAction(self.action_Stacked_bars)
        self.menuFrequencies.addAction(self.action_barchart_plot)
        self.menuAnalyse.addAction(self.menuCorpus_locations.menuAction())
        self.menuAnalyse.addAction(self.menuFrequencies.menuAction())
        self.menuAnalyse.addAction(self.menuTime_data.menuAction())
        self.menuAnalyse.addAction(self.menuFrequency_maps.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCorpus.menuAction())
        self.menubar.addAction(self.menuAnalyse.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())
        self.label_5.setBuddy(self.combo_corpus)
        self.label.setBuddy(self.edit_query_string)
        self.label_8.setBuddy(self.edit_file_name)
        self.label_4.setBuddy(self.edit_query_filter)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Coquery", None))
        self.label_5.setText(_translate("MainWindow", "Corpus:", None))
        self.context_mode.setText(_translate("MainWindow", "Context mode:", None))
        self.radio_context_mode_kwic.setText(_translate("MainWindow", "KWIC", None))
        self.radio_context_mode_string.setText(_translate("MainWindow", "Single string", None))
        self.radio_context_mode_columns.setText(_translate("MainWindow", "Columns", None))
        self.context_left_span_label.setText(_translate("MainWindow", "Left context:", None))
        self.context_left_span.setSpecialValueText(_translate("MainWindow", "none", None))
        self.context_left_span.setSuffix(_translate("MainWindow", " words", None))
        self.context_right_span_label.setText(_translate("MainWindow", "Right context:", None))
        self.context_right_span.setSpecialValueText(_translate("MainWindow", "none", None))
        self.context_right_span.setSuffix(_translate("MainWindow", " words", None))
        self.button_stopwords.setText(_translate("MainWindow", "Stop-words...", None))
        self.button_run_query.setText(_translate("MainWindow", "&Query", None))
        self.label.setText(_translate("MainWindow", "&Enter query strings:", None))
        self.context_query_syntax.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter your query strings in this field. Coquery uses a syntax for query strings that is compatible to the syntax used by the BYU web corpora (e.g. COCA). For details, see <a href=\"http://corpus.byu.edu/coca/help/syntax_e.asp\"><span style=\" text-decoration: underline; color:#0057ae;\">http://corpus.byu.edu/coca/help/syntax_e.asp</span></a></p></body></html>", None))
        self.context_query_syntax.setText(_translate("MainWindow", "?", None))
        self.label_8.setText(_translate("MainWindow", "&Use query file:", None))
        self.button_file_options.setText(_translate("MainWindow", "O&ptions...", None))
        self.button_file_options.setShortcut(_translate("MainWindow", "Alt+B", None))
        self.button_browse_file.setText(_translate("MainWindow", "&Open", None))
        self.button_browse_file.setShortcut(_translate("MainWindow", "Alt+B", None))
        self.label_2.setText(_translate("MainWindow", "Output columns:", None))
        self.label_4.setText(_translate("MainWindow", "Filter:", None))
        self.edit_query_filter.setPlaceholderText(_translate("MainWindow", "(e.g. Year > 1999)", None))
        self.label_10.setText(_translate("MainWindow", "Aggregation:", None))
        self.radio_aggregate_none.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Do not aggregate the query results.</span></p><p>Every token that matches the query string is listed in the \'Query results\' table. </p></body></html>", None))
        self.radio_aggregate_none.setText(_translate("MainWindow", "&None", None))
        self.radio_aggregate_frequencies.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Show the frequency of each token.</span></p><p>\n"
"The number of occurrences of each token matching the query string is counted. The \'Query results\' table shows one row for each token, with the number of occurrences in the column \'Frequency\' . </p></body></html>", None))
        self.radio_aggregate_frequencies.setText(_translate("MainWindow", "&Frequency", None))
        self.radio_aggregate_uniques.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Show only distinct tokens.</span></p><p>The tokens matching the query string are aggregated so that duplicate matches are dropped. The \'Query results\' table shows only distinct tokens, and no duplicates. </p></body></html>", None))
        self.radio_aggregate_uniques.setText(_translate("MainWindow", "&Uniques", None))
        self.radio_aggregate_collocations.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Show collocations.</span></p><p>For the tokens matching the query string, the left and right context as defined by the user is also queried for collocate words. The \'Query results\' table shows one row for each collocate word, together with several collocation statistics. </p></body></html>", None))
        self.radio_aggregate_collocations.setText(_translate("MainWindow", "Collocations", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuHilfe.setTitle(_translate("MainWindow", "&Help", None))
        self.menuCorpus.setTitle(_translate("MainWindow", "&Corpus", None))
        self.menuSettings.setTitle(_translate("MainWindow", "&Preferences", None))
        self.menuAnalyse.setTitle(_translate("MainWindow", "&Visualizations", None))
        self.menuTime_data.setTitle(_translate("MainWindow", "&Time data", None))
        self.menuFrequency_maps.setTitle(_translate("MainWindow", "Frequency maps", None))
        self.menuCorpus_locations.setTitle(_translate("MainWindow", "&Corpus locations", None))
        self.menuFrequencies.setTitle(_translate("MainWindow", "&Bar charts", None))
        self.action_open_input_file.setText(_translate("MainWindow", "&Open input file...", None))
        self.action_open_input_file.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_save_results.setText(_translate("MainWindow", "&Save results...", None))
        self.action_save_results.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_help.setText(_translate("MainWindow", "&Help", None))
        self.action_help.setShortcut(_translate("MainWindow", "F1", None))
        self.action_about_coquery.setText(_translate("MainWindow", "&About Coquery", None))
        self.actionDummy.setText(_translate("MainWindow", "Dummy", None))
        self.action_distinct_tokens.setText(_translate("MainWindow", "Distinct tokens", None))
        self.action_frequency.setText(_translate("MainWindow", "Frequency", None))
        self.action_all_tokens.setText(_translate("MainWindow", "All tokens", None))
        self.action_statistics.setText(_translate("MainWindow", "Corpus &statistics", None))
        self.action_mySQL_settings.setText(_translate("MainWindow", "&MySQL settings...", None))
        self.action_settings.setText(_translate("MainWindow", "&Settings...", None))
        self.action_quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_build_corpus.setText(_translate("MainWindow", "&Build new corpus...", None))
        self.action_build_corpus.setToolTip(_translate("MainWindow", "Build a new corpus from text files in a folder", None))
        self.action_remove_corpus.setText(_translate("MainWindow", "&Remove corpus...", None))
        self.action_remove_corpus.setToolTip(_translate("MainWindow", "Permanently and irrevocably remove corpus database", None))
        self.action_manage_corpus.setText(_translate("MainWindow", "&Manage corpora...", None))
        self.action_manage_corpus.setToolTip(_translate("MainWindow", "Install a corpus into a MySQL database", None))
        self.action_tree_map.setText(_translate("MainWindow", "&Tree map", None))
        self.action_heat_map.setText(_translate("MainWindow", "&Heat map", None))
        self.action_word_cloud.setText(_translate("MainWindow", "Word cloud", None))
        self.action_barcode_plot.setText(_translate("MainWindow", "&Barcode plot", None))
        self.action_beeswarm_plot.setText(_translate("MainWindow", "Bee&swarm plot", None))
        self.action_barchart_plot.setText(_translate("MainWindow", "&Bars", None))
        self.action_time_series_plot.setText(_translate("MainWindow", "T&ime series", None))
        self.action_corpus_documentation.setText(_translate("MainWindow", "Corpus &documentation...", None))
        self.action_percentage_area_plot.setText(_translate("MainWindow", "&Percentage areas", None))
        self.action_stacked_area_plot.setText(_translate("MainWindow", "&Stacked areas", None))
        self.action_line_plot.setText(_translate("MainWindow", "&Lines", None))
        self.actionStop_words.setText(_translate("MainWindow", "Stop words...", None))
        self.actionStop_words_2.setText(_translate("MainWindow", "&Stop words...", None))
        self.action_stacked_barchart_plot.setText(_translate("MainWindow", "&Percentage bars", None))
        self.action_Stacked_bars.setText(_translate("MainWindow", "&Stacked bars", None))
        self.action_view_log.setText(_translate("MainWindow", "View log...", None))


