# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coquery.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(940, 640)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.options_area = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.options_area.sizePolicy().hasHeightForWidth())
        self.options_area.setSizePolicy(sizePolicy)
        self.options_area.setFrameShape(QtGui.QFrame.NoFrame)
        self.options_area.setFrameShadow(QtGui.QFrame.Raised)
        self.options_area.setObjectName(_fromUtf8("options_area"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.options_area)
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.general_settings = QtGui.QWidget(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_settings.sizePolicy().hasHeightForWidth())
        self.general_settings.setSizePolicy(sizePolicy)
        self.general_settings.setObjectName(_fromUtf8("general_settings"))
        self.corpus_settings = QtGui.QVBoxLayout(self.general_settings)
        self.corpus_settings.setSpacing(10)
        self.corpus_settings.setMargin(0)
        self.corpus_settings.setObjectName(_fromUtf8("corpus_settings"))
        self.frame = QtGui.QFrame(self.general_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setMargin(10)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.combo_corpus = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_corpus.sizePolicy().hasHeightForWidth())
        self.combo_corpus.setSizePolicy(sizePolicy)
        self.combo_corpus.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.combo_corpus.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.combo_corpus.setObjectName(_fromUtf8("combo_corpus"))
        self.horizontalLayout_5.addWidget(self.combo_corpus)
        self.corpus_settings.addWidget(self.frame)
        self.frame1 = QtGui.QFrame(self.general_settings)
        self.frame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame1.setObjectName(_fromUtf8("frame1"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame1)
        self.gridLayout_5.setMargin(10)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.radio_mode_context = QtGui.QRadioButton(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_mode_context.sizePolicy().hasHeightForWidth())
        self.radio_mode_context.setSizePolicy(sizePolicy)
        self.radio_mode_context.setChecked(True)
        self.radio_mode_context.setObjectName(_fromUtf8("radio_mode_context"))
        self.gridLayout_5.addWidget(self.radio_mode_context, 0, 2, 1, 1)
        self.radio_mode_frequency = QtGui.QRadioButton(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_mode_frequency.sizePolicy().hasHeightForWidth())
        self.radio_mode_frequency.setSizePolicy(sizePolicy)
        self.radio_mode_frequency.setObjectName(_fromUtf8("radio_mode_frequency"))
        self.gridLayout_5.addWidget(self.radio_mode_frequency, 2, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.radio_mode_tokens = QtGui.QRadioButton(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_mode_tokens.sizePolicy().hasHeightForWidth())
        self.radio_mode_tokens.setSizePolicy(sizePolicy)
        self.radio_mode_tokens.setObjectName(_fromUtf8("radio_mode_tokens"))
        self.gridLayout_5.addWidget(self.radio_mode_tokens, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 1, 1, 1)
        self.corpus_settings.addWidget(self.frame1)
        self.frame_3 = QtGui.QFrame(self.general_settings)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setMargin(10)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.context_left_span_label = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span_label.sizePolicy().hasHeightForWidth())
        self.context_left_span_label.setSizePolicy(sizePolicy)
        self.context_left_span_label.setObjectName(_fromUtf8("context_left_span_label"))
        self.horizontalLayout_9.addWidget(self.context_left_span_label)
        spacerItem2 = QtGui.QSpacerItem(13, 17, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.context_left_span = QtGui.QSpinBox(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span.sizePolicy().hasHeightForWidth())
        self.context_left_span.setSizePolicy(sizePolicy)
        self.context_left_span.setObjectName(_fromUtf8("context_left_span"))
        self.horizontalLayout_9.addWidget(self.context_left_span)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        spacerItem3 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.context_right_span = QtGui.QSpinBox(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_right_span.sizePolicy().hasHeightForWidth())
        self.context_right_span.setSizePolicy(sizePolicy)
        self.context_right_span.setFrame(True)
        self.context_right_span.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.context_right_span.setObjectName(_fromUtf8("context_right_span"))
        self.horizontalLayout_8.addWidget(self.context_right_span)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.context_words_as_columns = QtGui.QCheckBox(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_words_as_columns.sizePolicy().hasHeightForWidth())
        self.context_words_as_columns.setSizePolicy(sizePolicy)
        self.context_words_as_columns.setObjectName(_fromUtf8("context_words_as_columns"))
        self.horizontalLayout_10.addWidget(self.context_words_as_columns)
        spacerItem4 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.corpus_settings.addWidget(self.frame_3)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.corpus_settings.addItem(spacerItem5)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.corpus_settings.addItem(spacerItem6)
        self.progressBar = QtGui.QProgressBar(self.general_settings)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximum(1)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.corpus_settings.addWidget(self.progressBar)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.corpus_settings.addItem(spacerItem7)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.corpus_settings.addItem(spacerItem8)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton = QtGui.QPushButton(self.general_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_6.addWidget(self.pushButton)
        spacerItem9 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.pushButton_2 = QtGui.QPushButton(self.general_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setSizeIncrement(QtCore.QSize(0, 0))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("dialog-information"))
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.corpus_settings.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addWidget(self.general_settings)
        self.frame2 = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame2.setObjectName(_fromUtf8("frame2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame2)
        self.verticalLayout.setMargin(10)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radio_query_string = QtGui.QRadioButton(self.frame2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_query_string.sizePolicy().hasHeightForWidth())
        self.radio_query_string.setSizePolicy(sizePolicy)
        self.radio_query_string.setText(_fromUtf8(""))
        self.radio_query_string.setChecked(True)
        self.radio_query_string.setObjectName(_fromUtf8("radio_query_string"))
        self.gridLayout_2.addWidget(self.radio_query_string, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1)
        self.edit_query_string = QtGui.QTextEdit(self.frame2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_query_string.sizePolicy().hasHeightForWidth())
        self.edit_query_string.setSizePolicy(sizePolicy)
        self.edit_query_string.setObjectName(_fromUtf8("edit_query_string"))
        self.gridLayout_2.addWidget(self.edit_query_string, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radio_query_file = QtGui.QRadioButton(self.frame2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_query_file.sizePolicy().hasHeightForWidth())
        self.radio_query_file.setSizePolicy(sizePolicy)
        self.radio_query_file.setText(_fromUtf8(""))
        self.radio_query_file.setObjectName(_fromUtf8("radio_query_file"))
        self.gridLayout_3.addWidget(self.radio_query_file, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.button_file_options = QtGui.QPushButton(self.frame2)
        self.button_file_options.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_file_options.sizePolicy().hasHeightForWidth())
        self.button_file_options.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-properties"))
        self.button_file_options.setIcon(icon)
        self.button_file_options.setObjectName(_fromUtf8("button_file_options"))
        self.gridLayout_3.addWidget(self.button_file_options, 0, 2, 1, 1)
        self.edit_file_name = QtGui.QLineEdit(self.frame2)
        self.edit_file_name.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_file_name.sizePolicy().hasHeightForWidth())
        self.edit_file_name.setSizePolicy(sizePolicy)
        self.edit_file_name.setAccessibleDescription(_fromUtf8(""))
        self.edit_file_name.setInputMask(_fromUtf8(""))
        self.edit_file_name.setText(_fromUtf8(""))
        self.edit_file_name.setReadOnly(True)
        self.edit_file_name.setObjectName(_fromUtf8("edit_file_name"))
        self.gridLayout_3.addWidget(self.edit_file_name, 1, 1, 1, 1)
        self.button_browse_file = QtGui.QPushButton(self.frame2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_file.sizePolicy().hasHeightForWidth())
        self.button_browse_file.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.button_browse_file.setIcon(icon)
        self.button_browse_file.setObjectName(_fromUtf8("button_browse_file"))
        self.gridLayout_3.addWidget(self.button_browse_file, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_7.addWidget(self.frame2)
        self.options_setting = QtGui.QFrame(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options_setting.sizePolicy().hasHeightForWidth())
        self.options_setting.setSizePolicy(sizePolicy)
        self.options_setting.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.options_setting.setFrameShape(QtGui.QFrame.StyledPanel)
        self.options_setting.setFrameShadow(QtGui.QFrame.Raised)
        self.options_setting.setObjectName(_fromUtf8("options_setting"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.options_setting)
        self.verticalLayout_11.setMargin(10)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(self.options_setting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.scrollArea = QtGui.QScrollArea(self.options_setting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtGui.QFrame.Panel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 238, 573))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.word_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.word_separator.setFrameShape(QtGui.QFrame.HLine)
        self.word_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.word_separator.setObjectName(_fromUtf8("word_separator"))
        self.gridLayout_4.addWidget(self.word_separator, 3, 0, 1, 1)
        self.lemma_layout = QtGui.QVBoxLayout()
        self.lemma_layout.setObjectName(_fromUtf8("lemma_layout"))
        self.lemma_data_orth = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lemma_data_orth.sizePolicy().hasHeightForWidth())
        self.lemma_data_orth.setSizePolicy(sizePolicy)
        self.lemma_data_orth.setObjectName(_fromUtf8("lemma_data_orth"))
        self.lemma_layout.addWidget(self.lemma_data_orth)
        self.lemma_data_phon = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lemma_data_phon.sizePolicy().hasHeightForWidth())
        self.lemma_data_phon.setSizePolicy(sizePolicy)
        self.lemma_data_phon.setObjectName(_fromUtf8("lemma_data_phon"))
        self.lemma_layout.addWidget(self.lemma_data_phon)
        self.lemma_data_pos = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lemma_data_pos.sizePolicy().hasHeightForWidth())
        self.lemma_data_pos.setSizePolicy(sizePolicy)
        self.lemma_data_pos.setObjectName(_fromUtf8("lemma_data_pos"))
        self.lemma_layout.addWidget(self.lemma_data_pos)
        self.gridLayout_4.addLayout(self.lemma_layout, 4, 1, 1, 1)
        self.coquery_layout = QtGui.QVBoxLayout()
        self.coquery_layout.setObjectName(_fromUtf8("coquery_layout"))
        self.coquery_query_string = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coquery_query_string.sizePolicy().hasHeightForWidth())
        self.coquery_query_string.setSizePolicy(sizePolicy)
        self.coquery_query_string.setObjectName(_fromUtf8("coquery_query_string"))
        self.coquery_layout.addWidget(self.coquery_query_string)
        self.coquery_parameters = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coquery_parameters.sizePolicy().hasHeightForWidth())
        self.coquery_parameters.setSizePolicy(sizePolicy)
        self.coquery_parameters.setObjectName(_fromUtf8("coquery_parameters"))
        self.coquery_layout.addWidget(self.coquery_parameters)
        self.gridLayout_4.addLayout(self.coquery_layout, 0, 1, 1, 1)
        self.speaker_layout = QtGui.QVBoxLayout()
        self.speaker_layout.setObjectName(_fromUtf8("speaker_layout"))
        self.speaker_data_id = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speaker_data_id.sizePolicy().hasHeightForWidth())
        self.speaker_data_id.setSizePolicy(sizePolicy)
        self.speaker_data_id.setObjectName(_fromUtf8("speaker_data_id"))
        self.speaker_layout.addWidget(self.speaker_data_id)
        self.speaker_data_age = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speaker_data_age.sizePolicy().hasHeightForWidth())
        self.speaker_data_age.setSizePolicy(sizePolicy)
        self.speaker_data_age.setObjectName(_fromUtf8("speaker_data_age"))
        self.speaker_layout.addWidget(self.speaker_data_age)
        self.speaker_data_sex = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speaker_data_sex.sizePolicy().hasHeightForWidth())
        self.speaker_data_sex.setSizePolicy(sizePolicy)
        self.speaker_data_sex.setObjectName(_fromUtf8("speaker_data_sex"))
        self.speaker_layout.addWidget(self.speaker_data_sex)
        self.gridLayout_4.addLayout(self.speaker_layout, 10, 1, 1, 1)
        self.file_layout = QtGui.QVBoxLayout()
        self.file_layout.setObjectName(_fromUtf8("file_layout"))
        self.file_data_name = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_data_name.sizePolicy().hasHeightForWidth())
        self.file_data_name.setSizePolicy(sizePolicy)
        self.file_data_name.setObjectName(_fromUtf8("file_data_name"))
        self.file_layout.addWidget(self.file_data_name)
        self.file_data_path = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_data_path.sizePolicy().hasHeightForWidth())
        self.file_data_path.setSizePolicy(sizePolicy)
        self.file_data_path.setObjectName(_fromUtf8("file_data_path"))
        self.file_layout.addWidget(self.file_data_path)
        self.gridLayout_4.addLayout(self.file_layout, 8, 1, 1, 1)
        self.file_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.file_separator.setFrameShape(QtGui.QFrame.HLine)
        self.file_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.file_separator.setObjectName(_fromUtf8("file_separator"))
        self.gridLayout_4.addWidget(self.file_separator, 9, 0, 1, 1)
        self.word_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_label.sizePolicy().hasHeightForWidth())
        self.word_label.setSizePolicy(sizePolicy)
        self.word_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.word_label.setObjectName(_fromUtf8("word_label"))
        self.gridLayout_4.addWidget(self.word_label, 2, 0, 1, 1)
        self.word_layout = QtGui.QVBoxLayout()
        self.word_layout.setObjectName(_fromUtf8("word_layout"))
        self.word_data_orth = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_data_orth.sizePolicy().hasHeightForWidth())
        self.word_data_orth.setSizePolicy(sizePolicy)
        self.word_data_orth.setObjectName(_fromUtf8("word_data_orth"))
        self.word_layout.addWidget(self.word_data_orth)
        self.word_data_phon = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_data_phon.sizePolicy().hasHeightForWidth())
        self.word_data_phon.setSizePolicy(sizePolicy)
        self.word_data_phon.setObjectName(_fromUtf8("word_data_phon"))
        self.word_layout.addWidget(self.word_data_phon)
        self.word_data_pos = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_data_pos.sizePolicy().hasHeightForWidth())
        self.word_data_pos.setSizePolicy(sizePolicy)
        self.word_data_pos.setObjectName(_fromUtf8("word_data_pos"))
        self.word_layout.addWidget(self.word_data_pos)
        self.gridLayout_4.addLayout(self.word_layout, 2, 1, 1, 1)
        self.source_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_label.sizePolicy().hasHeightForWidth())
        self.source_label.setSizePolicy(sizePolicy)
        self.source_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.source_label.setObjectName(_fromUtf8("source_label"))
        self.gridLayout_4.addWidget(self.source_label, 6, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.time_data_start = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_data_start.sizePolicy().hasHeightForWidth())
        self.time_data_start.setSizePolicy(sizePolicy)
        self.time_data_start.setObjectName(_fromUtf8("time_data_start"))
        self.verticalLayout_5.addWidget(self.time_data_start)
        self.time_data_end = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_data_end.sizePolicy().hasHeightForWidth())
        self.time_data_end.setSizePolicy(sizePolicy)
        self.time_data_end.setObjectName(_fromUtf8("time_data_end"))
        self.verticalLayout_5.addWidget(self.time_data_end)
        self.time_data_dur = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_data_dur.sizePolicy().hasHeightForWidth())
        self.time_data_dur.setSizePolicy(sizePolicy)
        self.time_data_dur.setObjectName(_fromUtf8("time_data_dur"))
        self.verticalLayout_5.addWidget(self.time_data_dur)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 12, 1, 1, 1)
        self.time_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_label.sizePolicy().hasHeightForWidth())
        self.time_label.setSizePolicy(sizePolicy)
        self.time_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.time_label.setObjectName(_fromUtf8("time_label"))
        self.gridLayout_4.addWidget(self.time_label, 12, 0, 1, 1)
        self.speaker_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.speaker_separator.setFrameShape(QtGui.QFrame.HLine)
        self.speaker_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.speaker_separator.setObjectName(_fromUtf8("speaker_separator"))
        self.gridLayout_4.addWidget(self.speaker_separator, 11, 0, 1, 1)
        self.lemma_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.lemma_separator.setFrameShape(QtGui.QFrame.HLine)
        self.lemma_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.lemma_separator.setObjectName(_fromUtf8("lemma_separator"))
        self.gridLayout_4.addWidget(self.lemma_separator, 5, 0, 1, 1)
        self.speaker_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speaker_label.sizePolicy().hasHeightForWidth())
        self.speaker_label.setSizePolicy(sizePolicy)
        self.speaker_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.speaker_label.setObjectName(_fromUtf8("speaker_label"))
        self.gridLayout_4.addWidget(self.speaker_label, 10, 0, 1, 1)
        self.lemma_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lemma_label.sizePolicy().hasHeightForWidth())
        self.lemma_label.setSizePolicy(sizePolicy)
        self.lemma_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lemma_label.setObjectName(_fromUtf8("lemma_label"))
        self.gridLayout_4.addWidget(self.lemma_label, 4, 0, 1, 1)
        self.coquery_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.coquery_separator.setFrameShape(QtGui.QFrame.HLine)
        self.coquery_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.coquery_separator.setObjectName(_fromUtf8("coquery_separator"))
        self.gridLayout_4.addWidget(self.coquery_separator, 1, 0, 1, 1)
        self.file_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_label.sizePolicy().hasHeightForWidth())
        self.file_label.setSizePolicy(sizePolicy)
        self.file_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.file_label.setObjectName(_fromUtf8("file_label"))
        self.gridLayout_4.addWidget(self.file_label, 8, 0, 1, 1)
        self.source_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.source_separator.setFrameShape(QtGui.QFrame.HLine)
        self.source_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.source_separator.setObjectName(_fromUtf8("source_separator"))
        self.gridLayout_4.addWidget(self.source_separator, 7, 0, 1, 1)
        self.time_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.time_separator.setFrameShape(QtGui.QFrame.HLine)
        self.time_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.time_separator.setObjectName(_fromUtf8("time_separator"))
        self.gridLayout_4.addWidget(self.time_separator, 14, 0, 1, 1)
        self.coquery_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coquery_label.sizePolicy().hasHeightForWidth())
        self.coquery_label.setSizePolicy(sizePolicy)
        self.coquery_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.coquery_label.setObjectName(_fromUtf8("coquery_label"))
        self.gridLayout_4.addWidget(self.coquery_label, 0, 0, 1, 1)
        self.source_layout = QtGui.QVBoxLayout()
        self.source_layout.setObjectName(_fromUtf8("source_layout"))
        self.source_id = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_id.sizePolicy().hasHeightForWidth())
        self.source_id.setSizePolicy(sizePolicy)
        self.source_id.setObjectName(_fromUtf8("source_id"))
        self.source_layout.addWidget(self.source_id)
        self.source_data_year = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_data_year.sizePolicy().hasHeightForWidth())
        self.source_data_year.setSizePolicy(sizePolicy)
        self.source_data_year.setObjectName(_fromUtf8("source_data_year"))
        self.source_layout.addWidget(self.source_data_year)
        self.source_data_genre = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_data_genre.sizePolicy().hasHeightForWidth())
        self.source_data_genre.setSizePolicy(sizePolicy)
        self.source_data_genre.setObjectName(_fromUtf8("source_data_genre"))
        self.source_layout.addWidget(self.source_data_genre)
        self.source_data_title = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_data_title.sizePolicy().hasHeightForWidth())
        self.source_data_title.setSizePolicy(sizePolicy)
        self.source_data_title.setObjectName(_fromUtf8("source_data_title"))
        self.source_layout.addWidget(self.source_data_title)
        self.gridLayout_4.addLayout(self.source_layout, 6, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.gridLayout_4.addItem(spacerItem10, 13, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_11.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7.addWidget(self.options_setting)
        self.verticalLayout_9.addWidget(self.options_area)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.results_tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results_tab.sizePolicy().hasHeightForWidth())
        self.results_tab.setSizePolicy(sizePolicy)
        self.results_tab.setObjectName(_fromUtf8("results_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.results_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.data_preview = QtGui.QTableView(self.results_tab)
        self.data_preview.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.data_preview.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.data_preview.setAlternatingRowColors(True)
        self.data_preview.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.data_preview.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.data_preview.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.data_preview.setSortingEnabled(True)
        self.data_preview.setObjectName(_fromUtf8("data_preview"))
        self.verticalLayout_4.addWidget(self.data_preview)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.results_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.file_size = QtGui.QLabel(self.results_tab)
        self.file_size.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.file_size.setObjectName(_fromUtf8("file_size"))
        self.horizontalLayout_4.addWidget(self.file_size)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, 10, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.results_tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.row_numbers = QtGui.QLabel(self.results_tab)
        self.row_numbers.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.row_numbers.setObjectName(_fromUtf8("row_numbers"))
        self.horizontalLayout_3.addWidget(self.row_numbers)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.results_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.label_time = QtGui.QLabel(self.results_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time.sizePolicy().hasHeightForWidth())
        self.label_time.setSizePolicy(sizePolicy)
        self.label_time.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_time.setObjectName(_fromUtf8("label_time"))
        self.horizontalLayout_2.addWidget(self.label_time)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.results_tab, _fromUtf8(""))
        self.log_tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_tab.sizePolicy().hasHeightForWidth())
        self.log_tab.setSizePolicy(sizePolicy)
        self.log_tab.setObjectName(_fromUtf8("log_tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.log_tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.viewing_area = QtGui.QTextBrowser(self.log_tab)
        self.viewing_area.setFrameShadow(QtGui.QFrame.Sunken)
        self.viewing_area.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.viewing_area.setAcceptRichText(False)
        self.viewing_area.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.viewing_area.setObjectName(_fromUtf8("viewing_area"))
        self.verticalLayout_2.addWidget(self.viewing_area)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.log_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.log_file_path = QtGui.QLabel(self.log_tab)
        self.log_file_path.setObjectName(_fromUtf8("log_file_path"))
        self.horizontalLayout.addWidget(self.log_file_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.log_tab, _fromUtf8(""))
        self.verticalLayout_9.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        self.menuCorpus = QtGui.QMenu(self.menubar)
        self.menuCorpus.setObjectName(_fromUtf8("menuCorpus"))
        self.menuChoose_corpus = QtGui.QMenu(self.menuCorpus)
        self.menuChoose_corpus.setObjectName(_fromUtf8("menuChoose_corpus"))
        self.menuQuery_mode = QtGui.QMenu(self.menuCorpus)
        self.menuQuery_mode.setObjectName(_fromUtf8("menuQuery_mode"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open_input_file = QtGui.QAction(MainWindow)
        self.action_Open_input_file.setObjectName(_fromUtf8("action_Open_input_file"))
        self.actionSave_results = QtGui.QAction(MainWindow)
        self.actionSave_results.setObjectName(_fromUtf8("actionSave_results"))
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionHelop = QtGui.QAction(MainWindow)
        self.actionHelop.setObjectName(_fromUtf8("actionHelop"))
        self.actionAbout_Coquery = QtGui.QAction(MainWindow)
        self.actionAbout_Coquery.setObjectName(_fromUtf8("actionAbout_Coquery"))
        self.actionDummy = QtGui.QAction(MainWindow)
        self.actionDummy.setObjectName(_fromUtf8("actionDummy"))
        self.actionDistinct_tokens = QtGui.QAction(MainWindow)
        self.actionDistinct_tokens.setObjectName(_fromUtf8("actionDistinct_tokens"))
        self.actionFrequency = QtGui.QAction(MainWindow)
        self.actionFrequency.setObjectName(_fromUtf8("actionFrequency"))
        self.actionAll_tokens = QtGui.QAction(MainWindow)
        self.actionAll_tokens.setObjectName(_fromUtf8("actionAll_tokens"))
        self.actionStatistics = QtGui.QAction(MainWindow)
        self.actionStatistics.setObjectName(_fromUtf8("actionStatistics"))
        self.actionStatistics_2 = QtGui.QAction(MainWindow)
        self.actionStatistics_2.setObjectName(_fromUtf8("actionStatistics_2"))
        self.actionMySQL_settings = QtGui.QAction(MainWindow)
        self.actionMySQL_settings.setObjectName(_fromUtf8("actionMySQL_settings"))
        self.actionOptions = QtGui.QAction(MainWindow)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.menuFile.addAction(self.action_Open_input_file)
        self.menuFile.addAction(self.actionSave_results)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHilfe.addAction(self.actionHelop)
        self.menuHilfe.addSeparator()
        self.menuHilfe.addAction(self.actionAbout_Coquery)
        self.menuChoose_corpus.addAction(self.actionDummy)
        self.menuQuery_mode.addAction(self.actionDistinct_tokens)
        self.menuQuery_mode.addAction(self.actionFrequency)
        self.menuQuery_mode.addAction(self.actionAll_tokens)
        self.menuCorpus.addAction(self.menuChoose_corpus.menuAction())
        self.menuCorpus.addAction(self.menuQuery_mode.menuAction())
        self.menuCorpus.addAction(self.actionStatistics_2)
        self.menuSettings.addAction(self.actionMySQL_settings)
        self.menuSettings.addAction(self.actionOptions)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCorpus.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())
        self.label_5.setBuddy(self.general_settings)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Coquery", None))
        self.label_5.setText(_translate("MainWindow", "Use corpus:", None))
        self.radio_mode_context.setText(_translate("MainWindow", "&Distinct tokens", None))
        self.radio_mode_frequency.setText(_translate("MainWindow", "&Frequency", None))
        self.label_6.setText(_translate("MainWindow", "Query mode", None))
        self.radio_mode_tokens.setText(_translate("MainWindow", "&All tokens", None))
        self.context_left_span_label.setText(_translate("MainWindow", "Left context::", None))
        self.context_left_span.setSpecialValueText(_translate("MainWindow", "none", None))
        self.context_left_span.setSuffix(_translate("MainWindow", " words", None))
        self.label_7.setText(_translate("MainWindow", "Right context::", None))
        self.context_right_span.setSpecialValueText(_translate("MainWindow", "none", None))
        self.context_right_span.setSuffix(_translate("MainWindow", " words", None))
        self.context_words_as_columns.setText(_translate("MainWindow", "Words as columns (KWIC)", None))
        self.progressBar.setFormat(_translate("MainWindow", "Ready.", None))
        self.pushButton.setText(_translate("MainWindow", "Query", None))
        self.pushButton_2.setText(_translate("MainWindow", "Statistics", None))
        self.label_12.setText(_translate("MainWindow", "Enter query strings:", None))
        self.label_8.setText(_translate("MainWindow", "Use query file:", None))
        self.button_file_options.setText(_translate("MainWindow", "O&ptions...", None))
        self.button_file_options.setShortcut(_translate("MainWindow", "Alt+B", None))
        self.edit_file_name.setPlaceholderText(_translate("MainWindow", "(no file selected)", None))
        self.button_browse_file.setText(_translate("MainWindow", "&Open", None))
        self.button_browse_file.setShortcut(_translate("MainWindow", "Alt+B", None))
        self.label_9.setText(_translate("MainWindow", "Output columns", None))
        self.lemma_data_orth.setText(_translate("MainWindow", "Orthographic form", None))
        self.lemma_data_phon.setText(_translate("MainWindow", "Phonological form", None))
        self.lemma_data_pos.setText(_translate("MainWindow", "Part-of-speech", None))
        self.coquery_query_string.setText(_translate("MainWindow", "Query string", None))
        self.coquery_parameters.setText(_translate("MainWindow", "Search parameters", None))
        self.speaker_data_id.setText(_translate("MainWindow", "Identifier", None))
        self.speaker_data_age.setText(_translate("MainWindow", "Age", None))
        self.speaker_data_sex.setText(_translate("MainWindow", "Sex", None))
        self.file_data_name.setText(_translate("MainWindow", "File name", None))
        self.file_data_path.setText(_translate("MainWindow", "File path", None))
        self.word_label.setText(_translate("MainWindow", "Word-form", None))
        self.word_data_orth.setText(_translate("MainWindow", "Orthographic form", None))
        self.word_data_phon.setText(_translate("MainWindow", "Phonological form", None))
        self.word_data_pos.setText(_translate("MainWindow", "Part-of-speech", None))
        self.source_label.setText(_translate("MainWindow", "Source", None))
        self.time_data_start.setText(_translate("MainWindow", "Starting time", None))
        self.time_data_end.setText(_translate("MainWindow", "End time", None))
        self.time_data_dur.setText(_translate("MainWindow", "Duration", None))
        self.time_label.setText(_translate("MainWindow", "Time", None))
        self.speaker_label.setText(_translate("MainWindow", "Speaker", None))
        self.lemma_label.setText(_translate("MainWindow", "Lemma", None))
        self.file_label.setText(_translate("MainWindow", "File", None))
        self.coquery_label.setText(_translate("MainWindow", "General", None))
        self.source_id.setText(_translate("MainWindow", "Identifier", None))
        self.source_data_year.setText(_translate("MainWindow", "Year", None))
        self.source_data_genre.setText(_translate("MainWindow", "Genre", None))
        self.source_data_title.setText(_translate("MainWindow", "Title", None))
        self.label_3.setText(_translate("MainWindow", "File size:", None))
        self.file_size.setText(_translate("MainWindow", "TextLabel", None))
        self.label_2.setText(_translate("MainWindow", "Number of rows:", None))
        self.row_numbers.setText(_translate("MainWindow", "TextLabel", None))
        self.label.setText(_translate("MainWindow", "Query duration:", None))
        self.label_time.setText(_translate("MainWindow", "hh:mm:ss", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.results_tab), _translate("MainWindow", "Results view", None))
        self.viewing_area.setDocumentTitle(_translate("MainWindow", "Log file", None))
        self.label_4.setText(_translate("MainWindow", "Log file:", None))
        self.log_file_path.setText(_translate("MainWindow", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log_tab), _translate("MainWindow", "Log file", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHilfe.setTitle(_translate("MainWindow", "Help", None))
        self.menuCorpus.setTitle(_translate("MainWindow", "Corpus", None))
        self.menuChoose_corpus.setTitle(_translate("MainWindow", "Choose corpus...", None))
        self.menuQuery_mode.setTitle(_translate("MainWindow", "Query mode", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.action_Open_input_file.setText(_translate("MainWindow", "&Open input file...", None))
        self.actionSave_results.setText(_translate("MainWindow", "Save results...", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionHelop.setText(_translate("MainWindow", "Help", None))
        self.actionAbout_Coquery.setText(_translate("MainWindow", "About Coquery", None))
        self.actionDummy.setText(_translate("MainWindow", "Dummy", None))
        self.actionDistinct_tokens.setText(_translate("MainWindow", "Distinct tokens", None))
        self.actionFrequency.setText(_translate("MainWindow", "Frequency", None))
        self.actionAll_tokens.setText(_translate("MainWindow", "All tokens", None))
        self.actionStatistics.setText(_translate("MainWindow", "Statistics", None))
        self.actionStatistics_2.setText(_translate("MainWindow", "Statistics", None))
        self.actionMySQL_settings.setText(_translate("MainWindow", "MySQL settings...", None))
        self.actionOptions.setText(_translate("MainWindow", "Options...", None))

