# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'figureOptions.ui'
#
# Created: Thu Oct 15 13:52:10 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from pyqt_compat import QtCore, QtGui, frameShadow

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FigureOptions(object):
    def setupUi(self, FigureOptions):
        FigureOptions.setObjectName(_fromUtf8("FigureOptions"))
        FigureOptions.resize(400, 480)
        self.gridLayout = QtGui.QGridLayout(FigureOptions)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(FigureOptions)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(FigureOptions)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_labels = QtGui.QWidget()
        self.tab_labels.setObjectName(_fromUtf8("tab_labels"))
        self.formLayout = QtGui.QFormLayout(self.tab_labels)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.tab_labels)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_main = QtGui.QLineEdit(self.tab_labels)
        self.label_main.setObjectName(_fromUtf8("label_main"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_main)
        self.label_6 = QtGui.QLabel(self.tab_labels)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_x_axis = QtGui.QLineEdit(self.tab_labels)
        self.label_x_axis.setObjectName(_fromUtf8("label_x_axis"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_x_axis)
        self.label_7 = QtGui.QLabel(self.tab_labels)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_y_axis = QtGui.QLineEdit(self.tab_labels)
        self.label_y_axis.setObjectName(_fromUtf8("label_y_axis"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_y_axis)
        self.label_8 = QtGui.QLabel(self.tab_labels)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_legend = QtGui.QLineEdit(self.tab_labels)
        self.label_legend.setObjectName(_fromUtf8("label_legend"))
        self.verticalLayout_4.addWidget(self.label_legend)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_13 = QtGui.QLabel(self.tab_labels)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_7.addWidget(self.label_13)
        self.spin_columns = QtGui.QSpinBox(self.tab_labels)
        self.spin_columns.setMinimum(1)
        self.spin_columns.setMaximum(9)
        self.spin_columns.setProperty("value", 1)
        self.spin_columns.setObjectName(_fromUtf8("spin_columns"))
        self.horizontalLayout_7.addWidget(self.spin_columns)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_labels, _fromUtf8(""))
        self.tab_fonts = QtGui.QWidget()
        self.tab_fonts.setObjectName(_fromUtf8("tab_fonts"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_fonts)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setHorizontalSpacing(8)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.combo_sequential = QtGui.QComboBox(self.tab_fonts)
        self.combo_sequential.setObjectName(_fromUtf8("combo_sequential"))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.combo_sequential.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.combo_sequential, 1, 1, 1, 1)
        self.combo_qualitative = QtGui.QComboBox(self.tab_fonts)
        self.combo_qualitative.setObjectName(_fromUtf8("combo_qualitative"))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.combo_qualitative.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.combo_qualitative, 0, 1, 1, 1)
        self.combo_custom = QtGui.QComboBox(self.tab_fonts)
        self.combo_custom.setObjectName(_fromUtf8("combo_custom"))
        self.gridLayout_6.addWidget(self.combo_custom, 3, 1, 1, 1)
        self.radio_diverging = QtGui.QRadioButton(self.tab_fonts)
        self.radio_diverging.setObjectName(_fromUtf8("radio_diverging"))
        self.gridLayout_6.addWidget(self.radio_diverging, 2, 0, 1, 1)
        self.combo_diverging = QtGui.QComboBox(self.tab_fonts)
        self.combo_diverging.setObjectName(_fromUtf8("combo_diverging"))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.combo_diverging.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.combo_diverging, 2, 1, 1, 1)
        self.radio_qualitative = QtGui.QRadioButton(self.tab_fonts)
        self.radio_qualitative.setChecked(True)
        self.radio_qualitative.setObjectName(_fromUtf8("radio_qualitative"))
        self.gridLayout_6.addWidget(self.radio_qualitative, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 3, 4, 1, 1)
        self.radio_sequential = QtGui.QRadioButton(self.tab_fonts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_sequential.sizePolicy().hasHeightForWidth())
        self.radio_sequential.setSizePolicy(sizePolicy)
        self.radio_sequential.setObjectName(_fromUtf8("radio_sequential"))
        self.gridLayout_6.addWidget(self.radio_sequential, 1, 0, 1, 1)
        self.button_edit_sequential = QtGui.QPushButton(self.tab_fonts)
        self.button_edit_sequential.setObjectName(_fromUtf8("button_edit_sequential"))
        self.gridLayout_6.addWidget(self.button_edit_sequential, 1, 2, 1, 1)
        self.button_edit_qualitative = QtGui.QPushButton(self.tab_fonts)
        self.button_edit_qualitative.setObjectName(_fromUtf8("button_edit_qualitative"))
        self.gridLayout_6.addWidget(self.button_edit_qualitative, 0, 2, 1, 1)
        self.radio_custom = QtGui.QRadioButton(self.tab_fonts)
        self.radio_custom.setObjectName(_fromUtf8("radio_custom"))
        self.gridLayout_6.addWidget(self.radio_custom, 3, 0, 1, 1)
        self.button_edit_diverging = QtGui.QPushButton(self.tab_fonts)
        self.button_edit_diverging.setObjectName(_fromUtf8("button_edit_diverging"))
        self.gridLayout_6.addWidget(self.button_edit_diverging, 2, 2, 1, 1)
        self.button_edit_custom = QtGui.QPushButton(self.tab_fonts)
        self.button_edit_custom.setObjectName(_fromUtf8("button_edit_custom"))
        self.gridLayout_6.addWidget(self.button_edit_custom, 3, 2, 1, 1)
        self.button_remove_custom = QtGui.QPushButton(self.tab_fonts)
        self.button_remove_custom.setObjectName(_fromUtf8("button_remove_custom"))
        self.gridLayout_6.addWidget(self.button_remove_custom, 3, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.tab_fonts)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spin_number = QtGui.QSpinBox(self.tab_fonts)
        self.spin_number.setMinimum(1)
        self.spin_number.setProperty("value", 6)
        self.spin_number.setObjectName(_fromUtf8("spin_number"))
        self.horizontalLayout_6.addWidget(self.spin_number)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.check_reverse = QtGui.QCheckBox(self.tab_fonts)
        self.check_reverse.setObjectName(_fromUtf8("check_reverse"))
        self.verticalLayout_3.addWidget(self.check_reverse)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.color_test_area = QtGui.QListWidget(self.tab_fonts)
        self.color_test_area.setDragEnabled(True)
        self.color_test_area.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.color_test_area.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.color_test_area.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.color_test_area.setMovement(QtGui.QListView.Snap)
        self.color_test_area.setObjectName(_fromUtf8("color_test_area"))
        self.verticalLayout_3.addWidget(self.color_test_area)
        self.tabWidget.addTab(self.tab_fonts, _fromUtf8(""))
        self.tab_colors = QtGui.QWidget()
        self.tab_colors.setObjectName(_fromUtf8("tab_colors"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_colors)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.tab_colors)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 362))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.group_main = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_main.setObjectName(_fromUtf8("group_main"))
        self.gridLayout_2 = QtGui.QGridLayout(self.group_main)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.group_main)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_sample_main = QtGui.QLabel(self.group_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_main.sizePolicy().hasHeightForWidth())
        self.label_sample_main.setSizePolicy(sizePolicy)
        self.label_sample_main.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_sample_main.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sample_main.setObjectName(_fromUtf8("label_sample_main"))
        self.horizontalLayout.addWidget(self.label_sample_main)
        self.button_select_main = QtGui.QPushButton(self.group_main)
        self.button_select_main.setObjectName(_fromUtf8("button_select_main"))
        self.horizontalLayout.addWidget(self.button_select_main)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.group_main)
        self.group_x_axis = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_x_axis.setObjectName(_fromUtf8("group_x_axis"))
        self.gridLayout_3 = QtGui.QGridLayout(self.group_x_axis)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.group_x_axis)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_sample_x = QtGui.QLabel(self.group_x_axis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_x.sizePolicy().hasHeightForWidth())
        self.label_sample_x.setSizePolicy(sizePolicy)
        self.label_sample_x.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_sample_x.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sample_x.setObjectName(_fromUtf8("label_sample_x"))
        self.horizontalLayout_2.addWidget(self.label_sample_x)
        self.button_select_x = QtGui.QPushButton(self.group_x_axis)
        self.button_select_x.setObjectName(_fromUtf8("button_select_x"))
        self.horizontalLayout_2.addWidget(self.button_select_x)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.group_x_axis)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_sample_x_ticks = QtGui.QLabel(self.group_x_axis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_x_ticks.sizePolicy().hasHeightForWidth())
        self.label_sample_x_ticks.setSizePolicy(sizePolicy)
        self.label_sample_x_ticks.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_sample_x_ticks.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sample_x_ticks.setObjectName(_fromUtf8("label_sample_x_ticks"))
        self.horizontalLayout_4.addWidget(self.label_sample_x_ticks)
        self.button_select_x_ticks = QtGui.QPushButton(self.group_x_axis)
        self.button_select_x_ticks.setObjectName(_fromUtf8("button_select_x_ticks"))
        self.horizontalLayout_4.addWidget(self.button_select_x_ticks)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.group_x_axis)
        self.group_y_axis = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_y_axis.setObjectName(_fromUtf8("group_y_axis"))
        self.gridLayout_4 = QtGui.QGridLayout(self.group_y_axis)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_9 = QtGui.QLabel(self.group_y_axis)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_sample_y = QtGui.QLabel(self.group_y_axis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_y.sizePolicy().hasHeightForWidth())
        self.label_sample_y.setSizePolicy(sizePolicy)
        self.label_sample_y.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_sample_y.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sample_y.setObjectName(_fromUtf8("label_sample_y"))
        self.horizontalLayout_3.addWidget(self.label_sample_y)
        self.button_select_y = QtGui.QPushButton(self.group_y_axis)
        self.button_select_y.setObjectName(_fromUtf8("button_select_y"))
        self.horizontalLayout_3.addWidget(self.button_select_y)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.group_y_axis)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_sample_y_ticks = QtGui.QLabel(self.group_y_axis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_y_ticks.sizePolicy().hasHeightForWidth())
        self.label_sample_y_ticks.setSizePolicy(sizePolicy)
        self.label_sample_y_ticks.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_sample_y_ticks.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sample_y_ticks.setObjectName(_fromUtf8("label_sample_y_ticks"))
        self.horizontalLayout_5.addWidget(self.label_sample_y_ticks)
        self.button_select_y_ticks = QtGui.QPushButton(self.group_y_axis)
        self.button_select_y_ticks.setObjectName(_fromUtf8("button_select_y_ticks"))
        self.horizontalLayout_5.addWidget(self.button_select_y_ticks)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.group_y_axis)
        self.group_legend = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_legend.setObjectName(_fromUtf8("group_legend"))
        self.gridLayout_5 = QtGui.QGridLayout(self.group_legend)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_11 = QtGui.QLabel(self.group_legend)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_sample_legend = QtGui.QLabel(self.group_legend)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_legend.sizePolicy().hasHeightForWidth())
        self.label_sample_legend.setSizePolicy(sizePolicy)
        self.label_sample_legend.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_sample_legend.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sample_legend.setObjectName(_fromUtf8("label_sample_legend"))
        self.horizontalLayout_12.addWidget(self.label_sample_legend)
        self.button_select_legend = QtGui.QPushButton(self.group_legend)
        self.button_select_legend.setObjectName(_fromUtf8("button_select_legend"))
        self.horizontalLayout_12.addWidget(self.button_select_legend)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.group_legend)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_sample_legend_entries = QtGui.QLabel(self.group_legend)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_legend_entries.sizePolicy().hasHeightForWidth())
        self.label_sample_legend_entries.setSizePolicy(sizePolicy)
        self.label_sample_legend_entries.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_sample_legend_entries.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sample_legend_entries.setObjectName(_fromUtf8("label_sample_legend_entries"))
        self.horizontalLayout_13.addWidget(self.label_sample_legend_entries)
        self.button_select_legend_entries = QtGui.QPushButton(self.group_legend)
        self.button_select_legend_entries.setObjectName(_fromUtf8("button_select_legend_entries"))
        self.horizontalLayout_13.addWidget(self.button_select_legend_entries)
        self.gridLayout_5.addLayout(self.horizontalLayout_13, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.group_legend)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.pushButton = QtGui.QPushButton(self.tab_colors)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_11.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        spacerItem4 = QtGui.QSpacerItem(20, 220, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout.setStretch(2, 1)
        self.tabWidget.addTab(self.tab_colors, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.label_4.setBuddy(self.spin_number)

        self.retranslateUi(FigureOptions)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), FigureOptions.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), FigureOptions.reject)
        QtCore.QMetaObject.connectSlotsByName(FigureOptions)

    def retranslateUi(self, FigureOptions):
        FigureOptions.setWindowTitle(_translate("FigureOptions", "Figure options – Coquery", None))
        self.label_5.setText(_translate("FigureOptions", "Main", None))
        self.label_6.setText(_translate("FigureOptions", "X axis", None))
        self.label_7.setText(_translate("FigureOptions", "Y axis", None))
        self.label_8.setText(_translate("FigureOptions", "Legend", None))
        self.label_13.setText(_translate("FigureOptions", "Number of columns in legend:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_labels), _translate("FigureOptions", "Labels", None))
        self.combo_sequential.setItemText(0, _translate("FigureOptions", "Greys", None))
        self.combo_sequential.setItemText(1, _translate("FigureOptions", "Reds", None))
        self.combo_sequential.setItemText(2, _translate("FigureOptions", "Greens", None))
        self.combo_sequential.setItemText(3, _translate("FigureOptions", "Blues", None))
        self.combo_sequential.setItemText(4, _translate("FigureOptions", "Oranges", None))
        self.combo_sequential.setItemText(5, _translate("FigureOptions", "Purples", None))
        self.combo_sequential.setItemText(6, _translate("FigureOptions", "BuGn", None))
        self.combo_sequential.setItemText(7, _translate("FigureOptions", "BuPu", None))
        self.combo_sequential.setItemText(8, _translate("FigureOptions", "GnBu", None))
        self.combo_sequential.setItemText(9, _translate("FigureOptions", "OrRd", None))
        self.combo_sequential.setItemText(10, _translate("FigureOptions", "PuBu", None))
        self.combo_sequential.setItemText(11, _translate("FigureOptions", "PuRd", None))
        self.combo_sequential.setItemText(12, _translate("FigureOptions", "RdPu", None))
        self.combo_sequential.setItemText(13, _translate("FigureOptions", "YlGn", None))
        self.combo_sequential.setItemText(14, _translate("FigureOptions", "PuBuGn", None))
        self.combo_sequential.setItemText(15, _translate("FigureOptions", "YlGnBu", None))
        self.combo_sequential.setItemText(16, _translate("FigureOptions", "YlOrBr", None))
        self.combo_sequential.setItemText(17, _translate("FigureOptions", "YlOrRd", None))
        self.combo_qualitative.setItemText(0, _translate("FigureOptions", "Set1", None))
        self.combo_qualitative.setItemText(1, _translate("FigureOptions", "Set2", None))
        self.combo_qualitative.setItemText(2, _translate("FigureOptions", "Set3", None))
        self.combo_qualitative.setItemText(3, _translate("FigureOptions", "Paired", None))
        self.combo_qualitative.setItemText(4, _translate("FigureOptions", "Accent", None))
        self.combo_qualitative.setItemText(5, _translate("FigureOptions", "Pastel1", None))
        self.combo_qualitative.setItemText(6, _translate("FigureOptions", "Pastel2", None))
        self.combo_qualitative.setItemText(7, _translate("FigureOptions", "Dark2", None))
        self.radio_diverging.setText(_translate("FigureOptions", "Diverging", None))
        self.combo_diverging.setItemText(0, _translate("FigureOptions", "RdBu", None))
        self.combo_diverging.setItemText(1, _translate("FigureOptions", "RdGy", None))
        self.combo_diverging.setItemText(2, _translate("FigureOptions", "PRGn", None))
        self.combo_diverging.setItemText(3, _translate("FigureOptions", "PiYG", None))
        self.combo_diverging.setItemText(4, _translate("FigureOptions", "BrBG", None))
        self.combo_diverging.setItemText(5, _translate("FigureOptions", "RdYlBu", None))
        self.combo_diverging.setItemText(6, _translate("FigureOptions", "RdYlGn", None))
        self.combo_diverging.setItemText(7, _translate("FigureOptions", "Spectral", None))
        self.radio_qualitative.setText(_translate("FigureOptions", "Qualitative", None))
        self.radio_sequential.setText(_translate("FigureOptions", "Sequential", None))
        self.button_edit_sequential.setText(_translate("FigureOptions", "Edit", None))
        self.button_edit_qualitative.setText(_translate("FigureOptions", "Edit", None))
        self.radio_custom.setText(_translate("FigureOptions", "Custom", None))
        self.button_edit_diverging.setText(_translate("FigureOptions", "Edit", None))
        self.button_edit_custom.setText(_translate("FigureOptions", "Edit", None))
        self.button_remove_custom.setText(_translate("FigureOptions", "Remove", None))
        self.label_4.setText(_translate("FigureOptions", "Number of colors:", None))
        self.check_reverse.setText(_translate("FigureOptions", "Reverse palette order", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fonts), _translate("FigureOptions", "Colors", None))
        self.group_main.setTitle(_translate("FigureOptions", "Main", None))
        self.label.setText(_translate("FigureOptions", "Label", None))
        self.label_sample_main.setText(_translate("FigureOptions", "Default font", None))
        self.button_select_main.setText(_translate("FigureOptions", "Select...", None))
        self.group_x_axis.setTitle(_translate("FigureOptions", "X axis", None))
        self.label_2.setText(_translate("FigureOptions", "Label", None))
        self.label_sample_x.setText(_translate("FigureOptions", "Default font", None))
        self.button_select_x.setText(_translate("FigureOptions", "Select...", None))
        self.label_3.setText(_translate("FigureOptions", "Ticks", None))
        self.label_sample_x_ticks.setText(_translate("FigureOptions", "Default font", None))
        self.button_select_x_ticks.setText(_translate("FigureOptions", "Select...", None))
        self.group_y_axis.setTitle(_translate("FigureOptions", "Y axis", None))
        self.label_9.setText(_translate("FigureOptions", "Label", None))
        self.label_sample_y.setText(_translate("FigureOptions", "Default font", None))
        self.button_select_y.setText(_translate("FigureOptions", "Select...", None))
        self.label_10.setText(_translate("FigureOptions", "Ticks", None))
        self.label_sample_y_ticks.setText(_translate("FigureOptions", "Default font", None))
        self.button_select_y_ticks.setText(_translate("FigureOptions", "Select...", None))
        self.group_legend.setTitle(_translate("FigureOptions", "Legend", None))
        self.label_11.setText(_translate("FigureOptions", "Label", None))
        self.label_sample_legend.setText(_translate("FigureOptions", "Default font", None))
        self.button_select_legend.setText(_translate("FigureOptions", "Select...", None))
        self.label_12.setText(_translate("FigureOptions", "Entries", None))
        self.label_sample_legend_entries.setText(_translate("FigureOptions", "Default font", None))
        self.button_select_legend_entries.setText(_translate("FigureOptions", "Select...", None))
        self.pushButton.setText(_translate("FigureOptions", "Select font for all...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_colors), _translate("FigureOptions", "Fonts", None))


