# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'results.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_resultsDialog(object):
    def setupUi(self, resultsDialog):
        resultsDialog.setObjectName(_fromUtf8("resultsDialog"))
        resultsDialog.resize(800, 600)
        self.verticalLayout = QtGui.QVBoxLayout(resultsDialog)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setContentsMargins(10, 4, 10, 4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.data_preview = QtGui.QTableView(resultsDialog)
        self.data_preview.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.data_preview.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.data_preview.setAlternatingRowColors(True)
        self.data_preview.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.data_preview.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.data_preview.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.data_preview.setSortingEnabled(True)
        self.data_preview.setObjectName(_fromUtf8("data_preview"))
        self.verticalLayout.addWidget(self.data_preview)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, 10, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(resultsDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.row_numbers = QtGui.QLabel(resultsDialog)
        self.row_numbers.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.row_numbers.setObjectName(_fromUtf8("row_numbers"))
        self.horizontalLayout_3.addWidget(self.row_numbers)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(resultsDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.file_size = QtGui.QLabel(resultsDialog)
        self.file_size.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.file_size.setObjectName(_fromUtf8("file_size"))
        self.horizontalLayout_4.addWidget(self.file_size)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.button_browse = QtGui.QPushButton(resultsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse.sizePolicy().hasHeightForWidth())
        self.button_browse.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.button_browse.setIcon(icon)
        self.button_browse.setObjectName(_fromUtf8("button_browse"))
        self.horizontalLayout_5.addWidget(self.button_browse)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line = QtGui.QFrame(resultsDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(resultsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.label_time = QtGui.QLabel(resultsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time.sizePolicy().hasHeightForWidth())
        self.label_time.setSizePolicy(sizePolicy)
        self.label_time.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_time.setObjectName(_fromUtf8("label_time"))
        self.horizontalLayout_2.addWidget(self.label_time)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.button_logfile = QtGui.QPushButton(resultsDialog)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("dialog-information"))
        self.button_logfile.setIcon(icon)
        self.button_logfile.setObjectName(_fromUtf8("button_logfile"))
        self.horizontalLayout.addWidget(self.button_logfile)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_quit = QtGui.QPushButton(resultsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_quit.sizePolicy().hasHeightForWidth())
        self.button_quit.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.button_quit.setIcon(icon)
        self.button_quit.setObjectName(_fromUtf8("button_quit"))
        self.horizontalLayout.addWidget(self.button_quit)
        self.button_restart = QtGui.QPushButton(resultsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_restart.sizePolicy().hasHeightForWidth())
        self.button_restart.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-revert"))
        self.button_restart.setIcon(icon)
        self.button_restart.setObjectName(_fromUtf8("button_restart"))
        self.horizontalLayout.addWidget(self.button_restart)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(resultsDialog)
        QtCore.QMetaObject.connectSlotsByName(resultsDialog)

    def retranslateUi(self, resultsDialog):
        resultsDialog.setWindowTitle(_translate("resultsDialog", "Coquery – Results", None))
        self.label_2.setText(_translate("resultsDialog", "Number of rows:", None))
        self.row_numbers.setText(_translate("resultsDialog", "TextLabel", None))
        self.label_3.setText(_translate("resultsDialog", "File size:", None))
        self.file_size.setText(_translate("resultsDialog", "TextLabel", None))
        self.button_browse.setText(_translate("resultsDialog", "Save", None))
        self.label.setText(_translate("resultsDialog", "Query duration:", None))
        self.label_time.setText(_translate("resultsDialog", "hh:mm:ss", None))
        self.button_logfile.setText(_translate("resultsDialog", "View log...", None))
        self.button_quit.setText(_translate("resultsDialog", "Quit", None))
        self.button_restart.setText(_translate("resultsDialog", "Start again", None))

