# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Fri Oct  2 12:06:52 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from pyqt_compat import QtCore, QtGui, frameShadow

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName(_fromUtf8("SettingsDialog"))
        SettingsDialog.resize(640, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtGui.QVBoxLayout(SettingsDialog)
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setContentsMargins(4, -1, 4, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame = QtGui.QFrame(SettingsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(frameShadow)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(8, 6, 8, 6)
        self.gridLayout_2.setHorizontalSpacing(8)
        self.gridLayout_2.setVerticalSpacing(20)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.check_ask_on_quit = QtGui.QCheckBox(self.frame)
        self.check_ask_on_quit.setObjectName(_fromUtf8("check_ask_on_quit"))
        self.verticalLayout_2.addWidget(self.check_ask_on_quit)
        self.check_save_query_string = QtGui.QCheckBox(self.frame)
        self.check_save_query_string.setObjectName(_fromUtf8("check_save_query_string"))
        self.verticalLayout_2.addWidget(self.check_save_query_string)
        self.check_save_query_file = QtGui.QCheckBox(self.frame)
        self.check_save_query_file.setObjectName(_fromUtf8("check_save_query_file"))
        self.verticalLayout_2.addWidget(self.check_save_query_file)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.check_ignore_case = QtGui.QCheckBox(self.frame)
        self.check_ignore_case.setObjectName(_fromUtf8("check_ignore_case"))
        self.verticalLayout.addWidget(self.check_ignore_case)
        self.check_ignore_punctuation = QtGui.QCheckBox(self.frame)
        self.check_ignore_punctuation.setObjectName(_fromUtf8("check_ignore_punctuation"))
        self.verticalLayout.addWidget(self.check_ignore_punctuation)
        self.check_experimental = QtGui.QCheckBox(self.frame)
        self.check_experimental.setObjectName(_fromUtf8("check_experimental"))
        self.verticalLayout.addWidget(self.check_experimental)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.spin_digits = QtGui.QSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_digits.sizePolicy().hasHeightForWidth())
        self.spin_digits.setSizePolicy(sizePolicy)
        self.spin_digits.setProperty("value", 3)
        self.spin_digits.setObjectName(_fromUtf8("spin_digits"))
        self.horizontalLayout.addWidget(self.spin_digits)
        self.label_3 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.check_align_quantified = QtGui.QCheckBox(self.frame)
        self.check_align_quantified.setObjectName(_fromUtf8("check_align_quantified"))
        self.verticalLayout_4.addWidget(self.check_align_quantified)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 2, 1, 1, 1)
        self.frame_addon_paths = QtGui.QFrame(self.frame)
        self.frame_addon_paths.setObjectName(_fromUtf8("frame_addon_paths"))
        self.gridLayout = QtGui.QGridLayout(self.frame_addon_paths)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.frame_addon_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.button_lemma_path = QtGui.QPushButton(self.frame_addon_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_lemma_path.sizePolicy().hasHeightForWidth())
        self.button_lemma_path.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("folder"))
        self.button_lemma_path.setIcon(icon)
        self.button_lemma_path.setObjectName(_fromUtf8("button_lemma_path"))
        self.gridLayout.addWidget(self.button_lemma_path, 0, 2, 1, 1)
        self.edit_installer_path = QtGui.QLineEdit(self.frame_addon_paths)
        self.edit_installer_path.setObjectName(_fromUtf8("edit_installer_path"))
        self.gridLayout.addWidget(self.edit_installer_path, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_addon_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.edit_visualizer_path = QtGui.QLineEdit(self.frame_addon_paths)
        self.edit_visualizer_path.setObjectName(_fromUtf8("edit_visualizer_path"))
        self.gridLayout.addWidget(self.edit_visualizer_path, 1, 1, 1, 1)
        self.button_lemma_path_3 = QtGui.QPushButton(self.frame_addon_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_lemma_path_3.sizePolicy().hasHeightForWidth())
        self.button_lemma_path_3.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("folder"))
        self.button_lemma_path_3.setIcon(icon)
        self.button_lemma_path_3.setObjectName(_fromUtf8("button_lemma_path_3"))
        self.gridLayout.addWidget(self.button_lemma_path_3, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_addon_paths, 3, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.label.setBuddy(self.spin_digits)

        self.retranslateUi(SettingsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings – Coquery", None))
        self.label_6.setText(_translate("SettingsDialog", "Query results:", None))
        self.check_ask_on_quit.setText(_translate("SettingsDialog", "Ask if &unsaved results should be saved upon exit", None))
        self.check_save_query_string.setText(_translate("SettingsDialog", "Save last query &string in configuration file", None))
        self.check_save_query_file.setText(_translate("SettingsDialog", "Save last query &file in configuration file", None))
        self.label_7.setText(_translate("SettingsDialog", "Add-on paths:", None))
        self.label_5.setText(_translate("SettingsDialog", "During queries:", None))
        self.label_4.setText(_translate("SettingsDialog", "Exiting:", None))
        self.check_ignore_case.setText(_translate("SettingsDialog", "Ignore &case", None))
        self.check_ignore_punctuation.setText(_translate("SettingsDialog", "Ignore &punctuation in contexts", None))
        self.check_experimental.setText(_translate("SettingsDialog", "Use &experimental features (MAY BE UNSTABLE!)", None))
        self.label.setText(_translate("SettingsDialog", "&Display ", None))
        self.spin_digits.setSuffix(_translate("SettingsDialog", " digit(s)", None))
        self.label_3.setText(_translate("SettingsDialog", "after decimal point", None))
        self.check_align_quantified.setText(_translate("SettingsDialog", "Align &quantified token columns", None))
        self.label_2.setText(_translate("SettingsDialog", "Corpus &installers: ", None))
        self.button_lemma_path.setText(_translate("SettingsDialog", "&Browse", None))
        self.button_lemma_path.setShortcut(_translate("SettingsDialog", "Alt+B", None))
        self.label_9.setText(_translate("SettingsDialog", "&Visualizers:", None))
        self.button_lemma_path_3.setText(_translate("SettingsDialog", "B&rowse", None))
        self.button_lemma_path_3.setShortcut(_translate("SettingsDialog", "Alt+B", None))


