# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!


from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName(_fromUtf8("Wizard"))
        Wizard.setWindowModality(QtCore.Qt.ApplicationModal)
        Wizard.resize(800, 600)
        Wizard.setMinimumSize(QtCore.QSize(259, 588))
        Wizard.setOptions(QtGui.QWizard.CancelButtonOnLeft)
        self.CorpusSelection = QtGui.QWizardPage()
        self.CorpusSelection.setObjectName(_fromUtf8("CorpusSelection"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.CorpusSelection)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_2 = QtGui.QFrame(self.CorpusSelection)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setMargin(10)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.Logo = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Logo.sizePolicy().hasHeightForWidth())
        self.Logo.setSizePolicy(sizePolicy)
        self.Logo.setMinimumSize(QtCore.QSize(200, 0))
        self.Logo.setText(_fromUtf8(""))
        self.Logo.setPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/logo.png")))
        self.Logo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Logo.setObjectName(_fromUtf8("Logo"))
        self.horizontalLayout_4.addWidget(self.Logo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.line_5 = QtGui.QFrame(self.frame_2)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_3.addWidget(self.line_5)
        self.widget = QtGui.QWidget(self.frame_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.combo_corpus = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_corpus.sizePolicy().hasHeightForWidth())
        self.combo_corpus.setSizePolicy(sizePolicy)
        self.combo_corpus.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.combo_corpus.setObjectName(_fromUtf8("combo_corpus"))
        self.horizontalLayout.addWidget(self.combo_corpus)
        self.verticalLayout_3.addWidget(self.widget)
        self.line = QtGui.QFrame(self.frame_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radio_mode_context = QtGui.QRadioButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_mode_context.sizePolicy().hasHeightForWidth())
        self.radio_mode_context.setSizePolicy(sizePolicy)
        self.radio_mode_context.setChecked(True)
        self.radio_mode_context.setObjectName(_fromUtf8("radio_mode_context"))
        self.gridLayout_3.addWidget(self.radio_mode_context, 0, 1, 1, 1)
        self.radio_mode_statistics = QtGui.QRadioButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_mode_statistics.sizePolicy().hasHeightForWidth())
        self.radio_mode_statistics.setSizePolicy(sizePolicy)
        self.radio_mode_statistics.setObjectName(_fromUtf8("radio_mode_statistics"))
        self.gridLayout_3.addWidget(self.radio_mode_statistics, 3, 1, 1, 1)
        self.radio_mode_frequency = QtGui.QRadioButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_mode_frequency.sizePolicy().hasHeightForWidth())
        self.radio_mode_frequency.setSizePolicy(sizePolicy)
        self.radio_mode_frequency.setObjectName(_fromUtf8("radio_mode_frequency"))
        self.gridLayout_3.addWidget(self.radio_mode_frequency, 1, 1, 1, 1)
        self.radio_mode_tokens = QtGui.QRadioButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_mode_tokens.sizePolicy().hasHeightForWidth())
        self.radio_mode_tokens.setSizePolicy(sizePolicy)
        self.radio_mode_tokens.setObjectName(_fromUtf8("radio_mode_tokens"))
        self.gridLayout_3.addWidget(self.radio_mode_tokens, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addWidget(self.frame_2)
        Wizard.addPage(self.CorpusSelection)
        self.InputSelection = QtGui.QWizardPage()
        self.InputSelection.setObjectName(_fromUtf8("InputSelection"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.InputSelection)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.frame = QtGui.QFrame(self.InputSelection)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setMargin(10)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_8.addWidget(self.label_4)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radio_query_string = QtGui.QRadioButton(self.frame)
        self.radio_query_string.setText(_fromUtf8(""))
        self.radio_query_string.setChecked(True)
        self.radio_query_string.setObjectName(_fromUtf8("radio_query_string"))
        self.gridLayout_2.addWidget(self.radio_query_string, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1)
        self.edit_query_string = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_query_string.sizePolicy().hasHeightForWidth())
        self.edit_query_string.setSizePolicy(sizePolicy)
        self.edit_query_string.setObjectName(_fromUtf8("edit_query_string"))
        self.gridLayout_2.addWidget(self.edit_query_string, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radio_query_file = QtGui.QRadioButton(self.frame)
        self.radio_query_file.setText(_fromUtf8(""))
        self.radio_query_file.setObjectName(_fromUtf8("radio_query_file"))
        self.gridLayout.addWidget(self.radio_query_file, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.edit_file_name = QtGui.QLineEdit(self.frame)
        self.edit_file_name.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_file_name.sizePolicy().hasHeightForWidth())
        self.edit_file_name.setSizePolicy(sizePolicy)
        self.edit_file_name.setObjectName(_fromUtf8("edit_file_name"))
        self.gridLayout.addWidget(self.edit_file_name, 1, 1, 1, 1)
        self.button_browse_file = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_file.sizePolicy().hasHeightForWidth())
        self.button_browse_file.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.button_browse_file.setIcon(icon)
        self.button_browse_file.setObjectName(_fromUtf8("button_browse_file"))
        self.gridLayout.addWidget(self.button_browse_file, 1, 2, 1, 1)
        self.button_file_options = QtGui.QPushButton(self.frame)
        self.button_file_options.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_file_options.sizePolicy().hasHeightForWidth())
        self.button_file_options.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-properties"))
        self.button_file_options.setIcon(icon)
        self.button_file_options.setObjectName(_fromUtf8("button_file_options"))
        self.gridLayout.addWidget(self.button_file_options, 2, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.verticalLayout_10.addWidget(self.frame)
        Wizard.addPage(self.InputSelection)
        self.wizardPage = QtGui.QWizardPage()
        self.wizardPage.setObjectName(_fromUtf8("wizardPage"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.wizardPage)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame_3 = QtGui.QFrame(self.wizardPage)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setMargin(10)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.scrollArea = QtGui.QScrollArea(self.frame_3)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 353, 670))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_11.setMargin(10)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setContentsMargins(20, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(20)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.file_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.file_separator.setFrameShape(QtGui.QFrame.HLine)
        self.file_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.file_separator.setObjectName(_fromUtf8("file_separator"))
        self.gridLayout_4.addWidget(self.file_separator, 9, 0, 1, 1)
        self.word_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.word_separator.setFrameShape(QtGui.QFrame.HLine)
        self.word_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.word_separator.setObjectName(_fromUtf8("word_separator"))
        self.gridLayout_4.addWidget(self.word_separator, 3, 0, 1, 1)
        self.coquery_layout = QtGui.QVBoxLayout()
        self.coquery_layout.setObjectName(_fromUtf8("coquery_layout"))
        self.coquery_query_string = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coquery_query_string.sizePolicy().hasHeightForWidth())
        self.coquery_query_string.setSizePolicy(sizePolicy)
        self.coquery_query_string.setObjectName(_fromUtf8("coquery_query_string"))
        self.coquery_layout.addWidget(self.coquery_query_string)
        self.coquery_parameters = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coquery_parameters.sizePolicy().hasHeightForWidth())
        self.coquery_parameters.setSizePolicy(sizePolicy)
        self.coquery_parameters.setObjectName(_fromUtf8("coquery_parameters"))
        self.coquery_layout.addWidget(self.coquery_parameters)
        self.gridLayout_4.addLayout(self.coquery_layout, 0, 1, 1, 1)
        self.source_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_label.sizePolicy().hasHeightForWidth())
        self.source_label.setSizePolicy(sizePolicy)
        self.source_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.source_label.setObjectName(_fromUtf8("source_label"))
        self.gridLayout_4.addWidget(self.source_label, 6, 0, 1, 1)
        self.speaker_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.speaker_separator.setFrameShape(QtGui.QFrame.HLine)
        self.speaker_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.speaker_separator.setObjectName(_fromUtf8("speaker_separator"))
        self.gridLayout_4.addWidget(self.speaker_separator, 11, 0, 1, 1)
        self.coquery_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.coquery_separator.setFrameShape(QtGui.QFrame.HLine)
        self.coquery_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.coquery_separator.setObjectName(_fromUtf8("coquery_separator"))
        self.gridLayout_4.addWidget(self.coquery_separator, 1, 0, 1, 1)
        self.source_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.source_separator.setFrameShape(QtGui.QFrame.HLine)
        self.source_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.source_separator.setObjectName(_fromUtf8("source_separator"))
        self.gridLayout_4.addWidget(self.source_separator, 7, 0, 1, 1)
        self.lemma_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.lemma_separator.setFrameShape(QtGui.QFrame.HLine)
        self.lemma_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.lemma_separator.setObjectName(_fromUtf8("lemma_separator"))
        self.gridLayout_4.addWidget(self.lemma_separator, 5, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.time_data_start = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_data_start.sizePolicy().hasHeightForWidth())
        self.time_data_start.setSizePolicy(sizePolicy)
        self.time_data_start.setObjectName(_fromUtf8("time_data_start"))
        self.verticalLayout_5.addWidget(self.time_data_start)
        self.time_data_end = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_data_end.sizePolicy().hasHeightForWidth())
        self.time_data_end.setSizePolicy(sizePolicy)
        self.time_data_end.setObjectName(_fromUtf8("time_data_end"))
        self.verticalLayout_5.addWidget(self.time_data_end)
        self.time_data_dur = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_data_dur.sizePolicy().hasHeightForWidth())
        self.time_data_dur.setSizePolicy(sizePolicy)
        self.time_data_dur.setObjectName(_fromUtf8("time_data_dur"))
        self.verticalLayout_5.addWidget(self.time_data_dur)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 12, 1, 1, 1)
        self.source_layout = QtGui.QVBoxLayout()
        self.source_layout.setObjectName(_fromUtf8("source_layout"))
        self.source_id = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_id.sizePolicy().hasHeightForWidth())
        self.source_id.setSizePolicy(sizePolicy)
        self.source_id.setObjectName(_fromUtf8("source_id"))
        self.source_layout.addWidget(self.source_id)
        self.source_data_year = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_data_year.sizePolicy().hasHeightForWidth())
        self.source_data_year.setSizePolicy(sizePolicy)
        self.source_data_year.setObjectName(_fromUtf8("source_data_year"))
        self.source_layout.addWidget(self.source_data_year)
        self.source_data_genre = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_data_genre.sizePolicy().hasHeightForWidth())
        self.source_data_genre.setSizePolicy(sizePolicy)
        self.source_data_genre.setObjectName(_fromUtf8("source_data_genre"))
        self.source_layout.addWidget(self.source_data_genre)
        self.source_data_title = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_data_title.sizePolicy().hasHeightForWidth())
        self.source_data_title.setSizePolicy(sizePolicy)
        self.source_data_title.setObjectName(_fromUtf8("source_data_title"))
        self.source_layout.addWidget(self.source_data_title)
        self.gridLayout_4.addLayout(self.source_layout, 6, 1, 1, 1)
        self.time_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_label.sizePolicy().hasHeightForWidth())
        self.time_label.setSizePolicy(sizePolicy)
        self.time_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.time_label.setObjectName(_fromUtf8("time_label"))
        self.gridLayout_4.addWidget(self.time_label, 12, 0, 1, 1)
        self.speaker_layout = QtGui.QVBoxLayout()
        self.speaker_layout.setObjectName(_fromUtf8("speaker_layout"))
        self.speaker_data_id = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speaker_data_id.sizePolicy().hasHeightForWidth())
        self.speaker_data_id.setSizePolicy(sizePolicy)
        self.speaker_data_id.setObjectName(_fromUtf8("speaker_data_id"))
        self.speaker_layout.addWidget(self.speaker_data_id)
        self.speaker_data_age = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speaker_data_age.sizePolicy().hasHeightForWidth())
        self.speaker_data_age.setSizePolicy(sizePolicy)
        self.speaker_data_age.setObjectName(_fromUtf8("speaker_data_age"))
        self.speaker_layout.addWidget(self.speaker_data_age)
        self.speaker_data_sex = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speaker_data_sex.sizePolicy().hasHeightForWidth())
        self.speaker_data_sex.setSizePolicy(sizePolicy)
        self.speaker_data_sex.setObjectName(_fromUtf8("speaker_data_sex"))
        self.speaker_layout.addWidget(self.speaker_data_sex)
        self.gridLayout_4.addLayout(self.speaker_layout, 10, 1, 1, 1)
        self.context_layout = QtGui.QVBoxLayout()
        self.context_layout.setObjectName(_fromUtf8("context_layout"))
        self.context_left_span_layout = QtGui.QHBoxLayout()
        self.context_left_span_layout.setObjectName(_fromUtf8("context_left_span_layout"))
        self.context_left_span = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span.sizePolicy().hasHeightForWidth())
        self.context_left_span.setSizePolicy(sizePolicy)
        self.context_left_span.setObjectName(_fromUtf8("context_left_span"))
        self.context_left_span_layout.addWidget(self.context_left_span)
        self.context_left_span_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span_label.sizePolicy().hasHeightForWidth())
        self.context_left_span_label.setSizePolicy(sizePolicy)
        self.context_left_span_label.setObjectName(_fromUtf8("context_left_span_label"))
        self.context_left_span_layout.addWidget(self.context_left_span_label)
        self.context_layout.addLayout(self.context_left_span_layout)
        self.context_right_span_layout = QtGui.QHBoxLayout()
        self.context_right_span_layout.setObjectName(_fromUtf8("context_right_span_layout"))
        self.context_right_span = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_right_span.sizePolicy().hasHeightForWidth())
        self.context_right_span.setSizePolicy(sizePolicy)
        self.context_right_span.setObjectName(_fromUtf8("context_right_span"))
        self.context_right_span_layout.addWidget(self.context_right_span)
        self.context_right_span_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_right_span_label.sizePolicy().hasHeightForWidth())
        self.context_right_span_label.setSizePolicy(sizePolicy)
        self.context_right_span_label.setObjectName(_fromUtf8("context_right_span_label"))
        self.context_right_span_layout.addWidget(self.context_right_span_label)
        self.context_layout.addLayout(self.context_right_span_layout)
        self.context_words_as_columns = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_words_as_columns.sizePolicy().hasHeightForWidth())
        self.context_words_as_columns.setSizePolicy(sizePolicy)
        self.context_words_as_columns.setObjectName(_fromUtf8("context_words_as_columns"))
        self.context_layout.addWidget(self.context_words_as_columns)
        self.gridLayout_4.addLayout(self.context_layout, 14, 1, 1, 1)
        self.speaker_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speaker_label.sizePolicy().hasHeightForWidth())
        self.speaker_label.setSizePolicy(sizePolicy)
        self.speaker_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.speaker_label.setObjectName(_fromUtf8("speaker_label"))
        self.gridLayout_4.addWidget(self.speaker_label, 10, 0, 1, 1)
        self.file_layout = QtGui.QVBoxLayout()
        self.file_layout.setObjectName(_fromUtf8("file_layout"))
        self.file_data_name = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_data_name.sizePolicy().hasHeightForWidth())
        self.file_data_name.setSizePolicy(sizePolicy)
        self.file_data_name.setObjectName(_fromUtf8("file_data_name"))
        self.file_layout.addWidget(self.file_data_name)
        self.file_data_path = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_data_path.sizePolicy().hasHeightForWidth())
        self.file_data_path.setSizePolicy(sizePolicy)
        self.file_data_path.setObjectName(_fromUtf8("file_data_path"))
        self.file_layout.addWidget(self.file_data_path)
        self.gridLayout_4.addLayout(self.file_layout, 8, 1, 1, 1)
        self.word_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_label.sizePolicy().hasHeightForWidth())
        self.word_label.setSizePolicy(sizePolicy)
        self.word_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.word_label.setObjectName(_fromUtf8("word_label"))
        self.gridLayout_4.addWidget(self.word_label, 2, 0, 1, 1)
        self.word_layout = QtGui.QVBoxLayout()
        self.word_layout.setObjectName(_fromUtf8("word_layout"))
        self.word_data_orth = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_data_orth.sizePolicy().hasHeightForWidth())
        self.word_data_orth.setSizePolicy(sizePolicy)
        self.word_data_orth.setObjectName(_fromUtf8("word_data_orth"))
        self.word_layout.addWidget(self.word_data_orth)
        self.word_data_phon = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_data_phon.sizePolicy().hasHeightForWidth())
        self.word_data_phon.setSizePolicy(sizePolicy)
        self.word_data_phon.setObjectName(_fromUtf8("word_data_phon"))
        self.word_layout.addWidget(self.word_data_phon)
        self.word_data_pos = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_data_pos.sizePolicy().hasHeightForWidth())
        self.word_data_pos.setSizePolicy(sizePolicy)
        self.word_data_pos.setObjectName(_fromUtf8("word_data_pos"))
        self.word_layout.addWidget(self.word_data_pos)
        self.gridLayout_4.addLayout(self.word_layout, 2, 1, 1, 1)
        self.lemma_layout = QtGui.QVBoxLayout()
        self.lemma_layout.setObjectName(_fromUtf8("lemma_layout"))
        self.lemma_data_orth = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lemma_data_orth.sizePolicy().hasHeightForWidth())
        self.lemma_data_orth.setSizePolicy(sizePolicy)
        self.lemma_data_orth.setObjectName(_fromUtf8("lemma_data_orth"))
        self.lemma_layout.addWidget(self.lemma_data_orth)
        self.lemma_data_phon = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lemma_data_phon.sizePolicy().hasHeightForWidth())
        self.lemma_data_phon.setSizePolicy(sizePolicy)
        self.lemma_data_phon.setObjectName(_fromUtf8("lemma_data_phon"))
        self.lemma_layout.addWidget(self.lemma_data_phon)
        self.lemma_data_pos = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lemma_data_pos.sizePolicy().hasHeightForWidth())
        self.lemma_data_pos.setSizePolicy(sizePolicy)
        self.lemma_data_pos.setObjectName(_fromUtf8("lemma_data_pos"))
        self.lemma_layout.addWidget(self.lemma_data_pos)
        self.gridLayout_4.addLayout(self.lemma_layout, 4, 1, 1, 1)
        self.lemma_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lemma_label.sizePolicy().hasHeightForWidth())
        self.lemma_label.setSizePolicy(sizePolicy)
        self.lemma_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lemma_label.setObjectName(_fromUtf8("lemma_label"))
        self.gridLayout_4.addWidget(self.lemma_label, 4, 0, 1, 1)
        self.coquery_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coquery_label.sizePolicy().hasHeightForWidth())
        self.coquery_label.setSizePolicy(sizePolicy)
        self.coquery_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.coquery_label.setObjectName(_fromUtf8("coquery_label"))
        self.gridLayout_4.addWidget(self.coquery_label, 0, 0, 1, 1)
        self.context_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_label.sizePolicy().hasHeightForWidth())
        self.context_label.setSizePolicy(sizePolicy)
        self.context_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.context_label.setObjectName(_fromUtf8("context_label"))
        self.gridLayout_4.addWidget(self.context_label, 14, 0, 1, 1)
        self.file_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_label.sizePolicy().hasHeightForWidth())
        self.file_label.setSizePolicy(sizePolicy)
        self.file_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.file_label.setObjectName(_fromUtf8("file_label"))
        self.gridLayout_4.addWidget(self.file_label, 8, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 15, 0, 1, 1)
        self.time_separator = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.time_separator.setFrameShape(QtGui.QFrame.HLine)
        self.time_separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.time_separator.setObjectName(_fromUtf8("time_separator"))
        self.gridLayout_4.addWidget(self.time_separator, 13, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.verticalLayout_7.addWidget(self.frame_3)
        Wizard.addPage(self.wizardPage)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(_translate("Wizard", "Coquery", None))
        self.label_7.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-weight:600;\">Coquery 0.9</span></p><p><span style=\" font-weight:600;\">The corpus query tool</span></p><p>(c) 2015 Gero Kunter</p><p><br/><a href=\"https://bitbucket.org/gkunter/coquery\"><span style=\" text-decoration: underline; color:#0057ae;\">BitBucket page</span></a></p><p>Visit <a href=\"https://twitter.com/CoqueryTool\">@CoqueryTool</a> on Twitter</p></body></html>", None))
        self.label.setText(_translate("Wizard", "Use corpus:", None))
        self.radio_mode_context.setText(_translate("Wizard", "&Distinct tokens", None))
        self.radio_mode_statistics.setText(_translate("Wizard", "&Statistics", None))
        self.radio_mode_frequency.setText(_translate("Wizard", "&Frequency", None))
        self.radio_mode_tokens.setText(_translate("Wizard", "&All tokens", None))
        self.label_6.setText(_translate("Wizard", "Choose query mode:", None))
        self.label_4.setText(_translate("Wizard", "Query source", None))
        self.label_12.setText(_translate("Wizard", "&Use query string:", None))
        self.label_8.setText(_translate("Wizard", "Read queries from &file:", None))
        self.button_browse_file.setText(_translate("Wizard", "&Open", None))
        self.button_browse_file.setShortcut(_translate("Wizard", "Alt+B", None))
        self.button_file_options.setText(_translate("Wizard", "O&ptions...", None))
        self.button_file_options.setShortcut(_translate("Wizard", "Alt+B", None))
        self.label_2.setText(_translate("Wizard", "Choose output columns", None))
        self.coquery_query_string.setText(_translate("Wizard", "Query string", None))
        self.coquery_parameters.setText(_translate("Wizard", "Search parameters", None))
        self.source_label.setText(_translate("Wizard", "Source features", None))
        self.time_data_start.setText(_translate("Wizard", "Starting time", None))
        self.time_data_end.setText(_translate("Wizard", "End time", None))
        self.time_data_dur.setText(_translate("Wizard", "Duration", None))
        self.source_id.setText(_translate("Wizard", "Identifier", None))
        self.source_data_year.setText(_translate("Wizard", "Year", None))
        self.source_data_genre.setText(_translate("Wizard", "Genre", None))
        self.source_data_title.setText(_translate("Wizard", "Title", None))
        self.time_label.setText(_translate("Wizard", "Time features", None))
        self.speaker_data_id.setText(_translate("Wizard", "Identifier", None))
        self.speaker_data_age.setText(_translate("Wizard", "Age", None))
        self.speaker_data_sex.setText(_translate("Wizard", "Sex", None))
        self.context_left_span_label.setText(_translate("Wizard", "words in left context", None))
        self.context_right_span_label.setText(_translate("Wizard", "words in right context", None))
        self.context_words_as_columns.setText(_translate("Wizard", "Words as columns", None))
        self.speaker_label.setText(_translate("Wizard", "Speaker features", None))
        self.file_data_name.setText(_translate("Wizard", "File name", None))
        self.file_data_path.setText(_translate("Wizard", "File path", None))
        self.word_label.setText(_translate("Wizard", "Word features", None))
        self.word_data_orth.setText(_translate("Wizard", "Orthographic form", None))
        self.word_data_phon.setText(_translate("Wizard", "Phonological form", None))
        self.word_data_pos.setText(_translate("Wizard", "Part-of-speech", None))
        self.lemma_data_orth.setText(_translate("Wizard", "Orthographic form", None))
        self.lemma_data_phon.setText(_translate("Wizard", "Phonological form", None))
        self.lemma_data_pos.setText(_translate("Wizard", "Part-of-speech", None))
        self.lemma_label.setText(_translate("Wizard", "Lemma features", None))
        self.coquery_label.setText(_translate("Wizard", "Coquery features", None))
        self.context_label.setText(_translate("Wizard", "Context features", None))
        self.file_label.setText(_translate("Wizard", "File features", None))
